### ISSUE TITLE
Infer

### ISSUE THREAD

**Issue by ChristianEschen** [vqdang/hover_net#10]
Hi

I have successfully used your repository for training the network.

I could use some help to run infer.py

What exactly should I use for 
        self.inf_data_list = [
            ['../../../data/NUC_Kumar/train-set/orig_split/', 'XXXX', 'valid_diff'],?=

**Comment by vqdang** [comment]
`self.inf_data_list` is a list of parent directories where each contains the sub-directories having the images you want to run the inference on. Using
```
a = [['data/Kumar/', 'XXXX', 'valid_same', 'valid_diff'],  ['data/CPM17/', '', '']]
```
as an example. the code will first run the inference for all images in the `valid_diff` and `valid_same` folder within `data/Kumar` and save it into a directory name `XXXX`. Hence, prediction for images in `valid_same` are stored in `'%s/XXXX/valid_same'/ %s self.save_dir`
Then it will run all images within `data/CPM17` and save the output in `self.save_dir`

**Comment by simongraham** [comment]
Closing this issue now due to inactivity. Please reopen if you still have any queries relating to running the inference code.

**Comment by Ghulam111** [comment]
@ChristianEschen  can you explain what changes you made in code to run training and help me run this code too

**Comment by haiqinzhong** [comment]
> @ChristianEschen can you explain what changes you made in code to run training and help me run this code too

Were you run? can you tell me what changes you made if you have run? I have try it two months,and as a rookie, I haven't run yet.
