### ISSUE TITLE
Chunk overlap resolution

### ISSUE THREAD

**Issue by jjhbw** [vqdang/hover_net#102]
Hi all,

Really impressed with this project! I'm studying it to see if my lab can use it.

One question that came to mind is how chunk/tile level cell predictions are aggregated into a WSI-level map of cells.

As I understand it, probability maps are generated for each 164x164 patch, which are subsequently assembled into 2048x2048 tiles. These tiles are then postprocessed using the Sobel+watershed routine, resulting in cell shape and nucleus location predictions.

What I dont understand yet is how the cell predictions of these tiles are assembled into a WSI-level cell map. How do you avoid artefacts and incomplete cells at the borders of each tile?

I tried studying the code and paper but this part eluded me.

Thanks in advance!

**Comment by vqdang** [comment]
Hi, thanks for using our work.

To answer your question, to avoid the artifact, imagine you draw all the tile upon the source WSI. We can then visually see that any nuclei lay at the boundary between tiles will be cut (artifacts). We know that will happen with absolute certainty. So to fix this, we only need to perform the post proc again along the bounday (defined as `ambiguous region` in the post proc script parameter). We start by removing nuclei ***within*** the ambigous region, then ovewrite them with new result from reapplying the post proc. Note that this only makes senses if the post proc behave deterministicly  for given a full nuclei raw prediction map (which it does). Hence, we will need to do the post proc in 3 phases
1. Normal postproc tiling.
2. Redo postproc for ambiguous regions along the tile boundary. (this will narrow the ambiguous to the cross section)
3. Redo postproc for ambiguous regions at the cross section between tiles.

Tile position for 3 phase is obtained from 
https://github.com/vqdang/hover_net/blob/be8ae2d621bfbddefd97591ef9df39252e108df9/infer/wsi.py#L92
https://github.com/vqdang/hover_net/blob/be8ae2d621bfbddefd97591ef9df39252e108df9/infer/wsi.py#L563
While the fixing at (2) and (3) is at
https://github.com/vqdang/hover_net/blob/be8ae2d621bfbddefd97591ef9df39252e108df9/infer/wsi.py#L602

>I tried studying the code and paper but this part eluded me.

This is more about engineering problem so we didnt include in the paper.

**Comment by jjhbw** [comment]
Very interesting, thanks for summarising! Understandable that it isn't described in the paper.
