### ISSUE TITLE
Image tiles don't output a png overlay of nuclear boundaries on top of original RGB image

### ISSUE THREAD

**Issue by dufan175** [vqdang/hover_net#105]
First of all thank you for the code .After I ran ./run_tile.sh , did not generate  a png overlay of nuclear boundaries on top of original RGB image,the generated image is still the original image .Can you tell me where I should modify to get the png overlay of nuclear boundaries on top of original RGB image.Thank you!

**Comment by simongraham** [comment]
Have you looked into the mat file to ensure that the results are not empty?

**Comment by dufan175** [comment]
> Have you looked into the mat file to ensure that the results are not empty?

I use the CoNSeP dataset and the mat file in it is normal

**Comment by vqdang** [comment]
Hi @dufan175 , did you use our provided https://github.com/vqdang/hover_net/blob/master/run_tile.sh ? You should have an folder called `overlay` which contains the the overlaid prediction.
