### ISSUE TITLE
Training Category Setting

### ISSUE THREAD

**Issue by zerodohero** [vqdang/hover_net#106]
Hello, my training data has 8 categories, how should I modify the following two lines of code?

ann_type[(ann_type == 3) | (ann_type == 4)] = 3
ann_type[(ann_type == 5) | (ann_type == 6) | (ann_type == 7)] = 4

**Comment by simongraham** [comment]
Hi @zerodohero ,

This is used because we group categories together in CoNSeP. For example, muscle cells, fibroblasts and endothelial cells are grouped into one category. The above performs that grouping. Therefore it is dataset specific. You may comment this part out if using your own dataset.

**Comment by zerodohero** [comment]
Hello, would this code be commented out if I didn't group small classes into big classes, and all the classes are parallel

**Comment by simongraham** [comment]
Yes exactly. And if you wanted to group classes together, then instead of commenting you may modify the above code segment.
