### ISSUE TITLE
how to run infenence

### ISSUE THREAD

**Issue by haiqinzhong** [vqdang/hover_net#108]
Dear @vqdang and @simongraham ,
 I run the code with the command: sh run_tile.sh ,but it told me that the model path not found.
my run_tile.sh like below:
**python run_infer.py \
--gpu='0' \
--nr_types=5 \
--type_info_path=type_info.json \
--batch_size=64 \
--model_mode=original \
--model_path=/logs/01/net_epoch=49.tar \
--nr_inference_workers=8 \
--nr_post_proc_workers=16 \
tile \
--input_dir=dataset/CoNSeP/Test/Images/ \
--output_dir=dataset/sample_tiles/pred/ \
--draw_dot \
--save_qupath** 
the model_path is the weight I got after training. Is it right? and how to solve?

**Comment by JiaYuHang** [comment]
sh run_tile.sh.That's it.and I have got a question about the metrics.I trained the network and didn't change anything.but the quantification of this classification is very low.
Fm id only 0.208.Why is that.

**Comment by haiqinzhong** [comment]
@JiaYuHang , can you give your inference command for me? as your question,it may be m is too little. and you can ask the author

**Comment by haiqinzhong** [comment]
@simongraham  @vqdang  , I think I know the error, because I comment a line --mode_path, and write a new mode_path. now it can run. 
but when it run, it get a new error:
**Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.**
and it don't stop or continue run

**Comment by JiaYuHang** [comment]
@haiqinzhong 
![image](https://user-images.githubusercontent.com/58177651/111251640-99256a00-864a-11eb-925d-def7b8070654.png)
That's it.Yours should be lacking '/'.
@vqdang tihs is my inference 
![image](https://user-images.githubusercontent.com/58177651/111251841-f8837a00-864a-11eb-9a53-eb30951df8b6.png)
the The Fm score was particularly low .and  this code is run
![image](https://user-images.githubusercontent.com/58177651/111252005-3385ad80-864b-11eb-8b4e-be9515a040b2.png)
and tihs is my valid_tp_dice_1
![image](https://user-images.githubusercontent.com/58177651/111252079-5adc7a80-864b-11eb-9ef7-eccc4dfc63d1.png)
so why is my Fm so low.

**Comment by JiaYuHang** [comment]
@haiqinzhong Can I add WeChat to you ? I'd like to discuss this problem with you.

**Comment by haiqinzhong** [comment]
@JiaYuHang , yeah

**Comment by vqdang** [comment]
@haiqinzhong Seem to come from the pytorch package itself.
https://github.com/pytorch/pytorch/issues/37377
Which pytorch version are you using? I suggest trying to either downgrade (not less than 1.2) or move to 1.6 or 1.7. The code should work normally even with 1.7, as least I tested that internally.

**Comment by vqdang** [comment]
@JiaYuHang I suggest you pick another checkpoint first. Best dice value doesnt directly correspond to higher Fm or any F.  As for Fm itself, because the #instances there are so little., It is not strange to see it widely fluctuate, It also contains more variation within it too (m=miscellaneous).  If you check the front page of the repos, here is our results on pytorch

Platform | F1d | F1e | F1i | F1s | F1m
-- | -- | -- | -- | -- | --
TensorFlow | 0.748 | 0.635 | 0.631 | 0.566 | 0.426
PyTorch | 0.756 | 0.636 | 0.559 | 0.557 | 0.348

**Comment by JiaYuHang** [comment]
@vqdang Thank you very much.I have found the problem.

**Comment by haiqinzhong** [comment]
@vqdang thanks for your reply, and sorry to reply you so late. I use the version 1.6 which you advise in [https://github.com/vqdang/hover_net/blob/master/README.md](url) and I solve the problem by add `os.environ['MKL_THREADING_LAYER'] = 'GNU'`, though I don't know why it can work after I add it.

**Comment by simongraham** [comment]
Please also note that for the miscellaneous class, there are necrotic nuclei and a bunch of other nuclei types that didn't fit into 'epithelial', 'inflammatory' and 'spindle-shaped' classes. There is no real clinical significance of predicting this class, but it was just kind of used as a dumping class for what was left. Therefore, please don't worry too much about the performance of miscellaneous. On a further note, necrotic nuclei in misc class are extremely small and so a single pixel difference can have quite a large effect on the score. This is another reason that this class can be sensitive to variation between checkpoints. 

I am closing this issue now as all of the above topics should have been resolved :)
