### ISSUE TITLE
how to Use SC-CNN to train CoNSeP datase

### ISSUE THREAD

**Issue by haiqinzhong** [vqdang/hover_net#110]
hello, I want to reproduce the classification result on SC-CNN, but I can't find the code and it doesn't in your code. Can you help me how did you implement SC-CNN to train the datasets?

**Comment by simongraham** [comment]
Hi @haiqinzhong ,

Unfortunately we do not have **publicly available** code for SC-CNN, but you are welcome to implement it yourself.

**Comment by haiqinzhong** [comment]
@simongraham ，how about mask_rcnn? whether I should change the dataset? I can't find the mask image.
