### ISSUE TITLE
Monusac model channel settings 

### ISSUE THREAD

**Issue by TEPPEIKNS** [vqdang/hover_net#111]
I applied the [monusac checkpoint](https://drive.google.com/file/d/13qkxDqv7CUqxN-l5CpeFVmc24mDw6CeV/view?usp=sharing
) but it seems like the model output 5 cell types.
I think monusac has only 4 cell types "Epithelial", "Lymphocyte", "Macrophage" and "Neutrophil".
I set the background is white color `["background", [255,   255,  255]]`, but the model segmented some circle areas as background.
Why does the model segment circle area as background ? Is it just miss prediction ?

**Run command**
```
!python run_infer.py \
--nr_types=5 \
--type_info_path=PATH_TO_JSON \
--batch_size=48 \
--model_mode=fast \
--model_path=PATH_TO_hovernet_fast_monusac_type_tf2pytorch.tar \
--nr_inference_workers=16 \
--nr_post_proc_workers=16 \
tile \
--input_dir=PATH_TO_IMAGES \
--output_dir=PATH_TO_OUT

```

**json file**
```
{
    "0" : ["background", [255,   255,  255]],
    "1" : ["Epithelial", [255,   0,   0]],
    "2" : ["Lymphocyte", [0  , 255,   0]],
    "3" : ["Macrophage", [0  ,   0, 255]],
    "4" : ["Neutrophil", [255, 255,   0]]
}

```

**Result**
![image](https://user-images.githubusercontent.com/5231107/113154738-461afc00-9273-11eb-8898-ede4ddaa4704.png)

**Comment by vqdang** [comment]
>I set the background is white color ["background", [255, 255, 255]], but the model segmented some circle areas as background.
Why does the model segment circle area as background ? Is it just miss prediction ?

It is misprediction. In fact, `background` correspond to no typing label detected in the `type segmentation map`, although the network could detect instance there basing on the `hover map`.  

For detail, the typing is done on the semantic segmentation map of nuclei type, so when prediciting N class of nuclei type, you always have N+1 class, with the addtional one be the `background/notype` category (for example, epi vs stromal becomes epi vs stromal vs background). Hence, this is why you see 5 channel in the raw prediction of MoNuSac models.

**Comment by simongraham** [comment]
In short, this may happen because of the nature of our independent decoder branches that Dang described above. You may simply ignore the background nuclei in any downstream applications. I am closing this issue as this should have cleared things up, but feel free to reopen if there is still confusion 👍🏼
