### ISSUE TITLE
No Mean and STD used

### ISSUE THREAD

**Issue by geetankr** [vqdang/hover_net#112]
Hi, I noticed that the code only normalizes the input image to 0-1 range during the forward function in net_desc.py

Is there are the reason why a Mean and STD is not used?
`img = ((img - self.MEAN[None, None, :]) / self.STD[None, None, :])`

**Comment by simongraham** [comment]
Hi @geetankr ,

There is no specific reason for not standardising the input in the way that you described. This was just did this for simplicity. You are welcome to try standardising the input to see if there are any noticeable differences in the results. I suspect that the difference would be negligible.
