### ISSUE TITLE
pannuke dataset

### ISSUE THREAD

**Issue by haiqinzhong** [vqdang/hover_net#113]
hi, @simongraham  and @vqdang , I'm try to use the pannuke dataset in hovernet, and after I downkoad the dataset, I found it different with consep dataset. So, how can I convert the pannuke dataset, and let it like the consep dataset. 
Hope you can teach me.

**Comment by haiqinzhong** [comment]
@simongraham  ，@vqdang  I maybe have convert the pannuke dataset. But while I training , the fifth class didn't in `raw_data["true_tp"]` [https://github.com/vqdang/hover_net/blob/abf6d891357393b651b954203647331602919bb6/models/hovernet/run_desc.py#L300](url), and it have in pred_tp . Of course, it also have the fifth class in the dataset. can you tell me why?

**Comment by simongraham** [comment]
Hi @haiqinzhong  - the patches are pre-extracted for PanNuke. Therefore, you should not need to apply `extract_patches.py`, but you will need to make sure that the data is in the correct format. Please look at the CoNSeP data format to see how the data is stored. All the information is contained within the README file.

**Comment by haiqinzhong** [comment]
yeah, I know. Thank you.

**Comment by vqdang** [comment]
@haiqinzhong for training on pannuke, commenting out the affine transformation.

**Comment by kiven1213** [comment]
> 嗨@haiqinzhong - 这些补丁是为 PanNuke 预先提取的。因此，您不需要申请`extract_patches.py`，但您需要确保数据格式正确。请查看 CoNSeP 数据格式以了解数据的存储方式。所有信息都包含在自述文件中。



> 嗨，@simongraham 和@vqdang，我尝试在hovernet 中使用 pannuke 数据集，在我下载数据集后，我发现它与 consep 数据集不同。那么，我该如何转换 pannuke 数据集，让它像 consep 数据集一样。
> 希望你能教教我。

**Comment by kiven1213** [comment]
@haiqinzhong Hello, now I am going to use this code to train the Pannuke data set. May I ask if you have finished the training? I would like to know if there is anything I should pay attention to when using the Pannuke data set? In terms of code use, I want to ask what steps are needed.
