### ISSUE TITLE
`remove_small_objects`

### ISSUE THREAD

**Issue by AliOlamat** [vqdang/hover_net#117]
Hi all, first of all, I would like to thank you for this great work.

here I have one question regarding the warning: `remove_small_objects`, Can you explain to us why do we face such a warning, even if it's not affecting the training process?
"
Processing:|#4                                                                                                 |2/147[00:00<01:17,1.87it/s]
/.../hover_net/models/hovernet/targets.py:36: UserWarning: Only one label was provided to `remove_small_objects`. Did you mean to use a boolean array?
  crop_ann = morph.remove_small_objects(crop_ann, min_size=30)
"

**Comment by simongraham** [comment]
This is because remove small objects expects a labelled array as input. In other words a 2D array with N objects with pixels ranging from 0 (background) to N. Now, when there is one object in the array the warning message will be thrown because it expects that a labelled image should have N > 1. This is not an error, but expected behaviour.

**Comment by AliOlamat** [comment]
Thank you very much, I got it now.
I have another question regarding the performance, how can point some metrics like ACCURACY, LOSS .. to be drawn with respect to epoch #?

**Comment by simongraham** [comment]
I'm sorry, but I didn't quite understand the question - could you reword it please? Are you asking where in the code do we calculate loss and metrics?

**Comment by AliOlamat** [comment]
> I'm sorry, but I didn't quite understand the question - could you reword it please? Are you asking where in the code do we calculate loss and metrics?

Thank you very much, I got it now.
I have another question regarding the training performance!
how can I find and display some performance-metrics like ACCURACY, LOSS ...?

**Comment by simongraham** [comment]
[This script](https://github.com/vqdang/hover_net/blob/master/models/hovernet/run_desc.py) computes the forward pass through the network and computes the loss and the metrics. The loss is calculated [here](https://github.com/vqdang/hover_net/blob/master/models/hovernet/run_desc.py#L69) and the metrics are calculated during training and validation from [here](https://github.com/vqdang/hover_net/blob/master/models/hovernet/run_desc.py#L277).
