### ISSUE TITLE
Fine-tune classification branch

### ISSUE THREAD

**Issue by jeroenmollink** [vqdang/hover_net#118]
Thanks for sharing this great repository, the results look really promising! On our own data, the segmentations look great and capture almost all nuclei. I was wondering if there are any options for fine-tuning the classification branch? We'd like the model to learn slightly different classes than those are present in the current datasets, but leave the segmentation part untouched as it already performs great. 

I can imagine it would be possible to freeze the parameters of certain layers through `params.requires_grad=False`. 

Also, it would be great if the nucleus type annotations can be provided as nuclei centroid coordinates rather than nuclei contours.

Any thoughts?

Thanks!

Jeroen

**Comment by simongraham** [comment]
Hi @jeroenmollink ,

Thanks for this - this is a good question and makes sense that you may want to fine-tune the classification branch. We will put this on to our to do list to add to the repository, but can't promise that it will be done imminently.

In terms of the nuclear annotations, we return both the contours and the centroids. The contours are returned to enable subsequent morphological analysis.
