### ISSUE TITLE
pretained model

### ISSUE THREAD

**Issue by f-thirty** [vqdang/hover_net#119]
After the pre-training model is downloaded, it shows that the file is damaged and cannot be decompressed,Could  you put a link to a pre-trained model again?

**Comment by f-thirty** [comment]
Our data set is a 3D data set with a channel number of 1. After reading your article, I think the idea is great, but I haven't figured out how to apply your method to our 3D data set. How should I apply it?

**Comment by jeroenmollink** [comment]
You can load the .tar files directly in the model, do not decompress them.

**Comment by simongraham** [comment]
Yes, exactly - like @jeroenmollink mentioned, the model path should point directly to the tar file. 

In answer to your question regarding a 3D hover-net - this is out the scope of this work but if you do pursue it further then please do keep us updated :)
