### ISSUE TITLE
The downloaded pretrained weights is broken

### ISSUE THREAD

**Issue by Frances1996** [vqdang/hover_net#120]
Hello, thanks for providing this code. 
When I tried this on my data, I found I cannot download the pretrained Preact-ResNet50 weights. It is reminded broken every time I downloaded it. Please give another link, Thanks a lot!

**Comment by simongraham** [comment]
Hi @Frances1996 ,

I just downloaded the weights again to check and nothing is broken. Maybe you are trying to unzip the `.tar` file? You need to directly provide the path to the downloaded file without unzipping and it will work.

**Comment by simongraham** [comment]
Closing this as it should have solved the issue.
