### ISSUE TITLE
compute stats.py {TYPE MODE !!!}

### ISSUE THREAD

**Issue by AliOlamat** [vqdang/hover_net#121]
Hi all, I get an error like this when I try to compute metrics for classification **(i.e. mode==type)** but it works when I set the mode to **instances**???

_(hovernet) DDD:/hover_net$ **python compute_stats.py --mode=type --**pred_dir='/media/hover_net/Output_predFiles/testImages/mat' --true_dir='/media/hover_net/dataset/Test/Labels'
Traceback (most recent call last):
  File "compute_stats.py", line 247, in <module>
    run_nuclei_type_stat(args.pred_dir, args.true_dir)
  File "compute_stats.py", line 103, in run_nuclei_type_stat
    paired_all = np.concatenate(paired_all, axis=0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate_

**Comment by vqdang** [comment]
Did you use a model with typing to make the prediction? And which dataset is this?

**Comment by AliOlamat** [comment]
yes , i used Consep dataset with nr_types=5 and original mode. I was able to get the instances metrics but I couldn't do that with the types.

**Comment by MTalhaAbdullah** [comment]
> yes , i used Consep dataset with nr_types=5 and original mode. I was able to get the instances metrics but I couldn't do that with the types.

I have the same issue. Did you find any solution? I am unable to compute_stats for ConSeP dataset.
