### ISSUE TITLE
Error(s) in loading state_dict for HoVerNet: Unexpected key(s) in state_dict: 

### ISSUE THREAD

**Issue by Filoudataset** [vqdang/hover_net#122]
Hello,
First of all, congratulations on this impressive work.
I have a problem using « run_infer.py »
Here is my config:
- Win10
- cuda 10.1
- python 3.6.12
- pytoch 1.6.0

I downloaded and renamed the model weights and  I placed them in the base directory
my command line is:
« python run_infer.py --gpu=0 --model_path=HVN_fast_monusac.tar --model_mode=fast tile --input_dir=C:/Users/rocha/HVN_infer_depart --output_dir=C:/Users/rocha/HVN_infer_arrivee »

and I get this error:

(HVN_pytorch_2) C:\Users\rocha\HVN_pytorch_2>python run_infer.py --gpu=0 --model_path=HVN_original_consep.tar --model_mode=original tile --input_dir=C:/Users/rocha/HVN_infer_depart --output_dir=C:/Users/rocha/HVN_infer_arrivee
|2021-05-21|09:47:15.687| [INFO] .... Detect #GPUS: 1
Traceback (most recent call last):
  File "run_infer.py", line 181, in <module>
    infer = InferManager(**method_args)
  File "C:\Users\rocha\HVN_pytorch_2\infer\base.py", line 27, in __init__
    self.__load_model()
  File "C:\Users\rocha\HVN_pytorch_2\infer\base.py", line 68, in __load_model
    net.load_state_dict(saved_state_dict, strict=True)
  File "G:\anaconda\envs\HVN_pytorch_2\lib\site-packages\torch\nn\modules\module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for HoVerNet:
        Unexpected key(s) in state_dict: "decoder.tp.u3.dense.blk_bna.bn.running_var", "decoder.tp.u3.dense.blk_bna.bn.running_mean", "decoder.tp.u3.dense.units.7.preact_bna/bn.running_mean", "decoder.tp.u3.dense.units.7.preact_bna/bn.weight", "decoder.tp.u3.dense.units.7.preact_bna/bn.bias", "decoder.tp.u3.dense.units.7.conv1/bn.running_var", "decoder.tp.u3.dense.units.7.conv1/bn.running_mean", "decoder.tp.u3.dense.units.7.conv1/bn.weight", "decoder.tp.u3.dense.units.6.preact_bna/bn.running_mean", "decoder.tp.u3.dense.units.6.preact_bna/bn.bias", "decoder.tp.u3.dense.units.5.preact_bna/bn.bias", "decoder.tp.u3.dense.units.5.conv2.weight", "decoder.tp.u3.dense.units.5.conv1/bn.running_var", "decoder.tp.u3.dense.units.5.conv1/bn.running_mean", "decoder.tp.u3.dense.units.4.preact_bna/bn.running_var", "decoder.tp.u3.dense.units.4.preact_bna/bn.weight", "decoder.tp.u3.dense.units.4.conv1/bn.running_var", "decoder.tp.u3.dense.units.4.conv1/bn.running_mean", "decoder.tp.u3.dense.units.3.preact_bna/bn.running_mean", "decoder.tp.u3.dense.units.3.preact_bna/bn.weight", "decoder.tp.u3.dense.units.3.conv1/bn.running_var", "decoder.tp.u3.dense.units.2.preact_bna/bn.weight", "decoder.tp.u3.dense.units.2.preact_bna/bn.bias", "decoder.tp.u3.dense.units.2.conv1/bn.running_mean", "decoder.tp.u3.dense.units.2.conv1/bn.weight", "decoder.tp.u3.dense.units.2.conv1.weight", "decoder.tp.u3.dense.units.1.preact_bna/bn.running_mean", "decoder.tp.u3.dense.units.1.conv2.weight", "decoder.tp.u3.dense.units.1.conv1/bn.running_mean", "decoder.tp.u3.dense.units.1.conv1/bn.weight", "decoder.tp.u3.dense.units.1.conv1/bn.bias", "decoder.tp.u3.dense.units.1.conv1.weight", "decoder.tp.u3.dense.units.0.preact_bna/bn.running_mean", "decoder.tp.u3.dense.units.4.conv1/bn.bias", "decoder.tp.u3.dense.units.0.preact_bna/bn.weight", "decoder.tp.u3.dense.units.0.conv1/bn.running_var", "decoder.tp.u3.dense.units.0.conv1/bn.bias", "decoder.tp.u3.dense.units.3.conv2.weight", "decoder.tp.u3.convf.weight", "decoder.tp.u3.conva.weight", "decoder.tp.u2.dense.blk_bna.bn.running_var", "decoder.tp.u2.dense.blk_bna.bn.weight", "decoder.tp.u2.dense.blk_bna.bn.bias", "decoder.tp.u2.dense.units.3.preact_bna/bn.running_var", "decoder.tp.u3.dense.units.4.preact_bna/bn.bias", "decoder.tp.u2.dense.units.3.conv1/bn.bias", "decoder.tp.u3.dense.units.4.conv1.weight", "decoder.tp.u2.dense.units.2.preact_bna/bn.running_mean", "decoder.tp.u2.dense.units.2.preact_bna/bn.weight", "decoder.tp.u2.dense.units.2.preact_bna/bn.bias", "decoder.tp.u2.dense.units.2.conv2.weight", "decoder.tp.u2.dense.units.2.conv1/bn.running_var", "decoder.tp.u2.dense.units.2.conv1/bn.bias", "decoder.tp.u2.dense.units.1.conv2.weight", "decoder.tp.u2.dense.units.1.conv1/bn.running_var", "decoder.tp.u2.dense.units.1.conv1.weight", "decoder.tp.u2.dense.units.0.preact_bna/bn.running_var", "decoder.tp.u2.dense.units.0.preact_bna/bn.running_mean", "decoder.tp.u2.dense.units.0.preact_bna/bn.bias", "decoder.tp.u2.dense.units.0.conv2.weight", "decoder.tp.u3.dense.units.5.preact_bna/bn.running_var", "decoder.tp.u2.dense.units.0.conv1/bn.weight", "decoder.tp.u2.dense.units.0.conv1/bn.bias", "decoder.tp.u2.dense.units.2.conv1/bn.weight", "decoder.tp.u2.convf.weight", "decoder.tp.u1.conva.weight", "decoder.tp.u0.bn.running_var", "decoder.tp.u0.bn.bias", "decoder.tp.u2.dense.units.1.conv1/bn.running_mean", "decoder.tp.u3.dense.units.6.conv1/bn.weight", "decoder.tp.u3.dense.units.5.conv1.weight", "decoder.tp.u2.conva.weight", "decoder.tp.u2.dense.units.2.conv1/bn.running_mean", "decoder.tp.u3.dense.units.0.conv2.weight", "decoder.tp.u3.dense.blk_bna.bn.weight", "decoder.tp.u3.dense.units.1.conv1/bn.running_var", "decoder.tp.u3.dense.units.6.conv2.weight", "decoder.tp.u3.dense.units.4.preact_bna/bn.running_mean", "decoder.tp.u2.dense.units.0.conv1/bn.running_var", "decoder.tp.u3.dense.units.4.conv2.weight", "decoder.tp.u2.dense.units.3.preact_bna/bn.running_mean", "decoder.tp.u3.dense.units.5.conv1/bn.bias", "decoder.tp.u2.dense.units.1.preact_bna/bn.weight", "decoder.tp.u3.dense.units.0.conv1.weight", "decoder.tp.u3.dense.units.6.preact_bna/bn.running_var", "decoder.tp.u2.dense.units.1.preact_bna/bn.running_mean", "decoder.tp.u2.dense.units.0.conv1/bn.running_mean", "decoder.tp.u2.dense.units.3.conv1.weight", "decoder.tp.u3.dense.units.6.preact_bna/bn.weight", "decoder.tp.u3.dense.units.5.conv1/bn.weight", "decoder.tp.u3.dense.units.6.conv1.weight", "decoder.tp.u3.dense.units.4.conv1/bn.weight", "decoder.tp.u0.bn.running_mean", "decoder.tp.u3.dense.units.0.conv1/bn.weight", "decoder.tp.u2.dense.units.1.conv1/bn.weight", "decoder.tp.u3.dense.units.5.preact_bna/bn.weight", "decoder.tp.u3.dense.units.6.conv1/bn.bias", "decoder.tp.u3.dense.units.3.preact_bna/bn.bias", "decoder.tp.u3.dense.units.2.conv1/bn.bias", "decoder.tp.u2.dense.units.1.conv1/bn.bias", "decoder.tp.u3.dense.blk_bna.bn.bias", "decoder.tp.u0.conv.weight", "decoder.tp.u3.dense.units.0.preact_bna/bn.bias", "decoder.tp.u2.dense.blk_bna.bn.running_mean", "decoder.tp.u3.dense.units.3.preact_bna/bn.running_var", "decoder.tp.u3.dense.units.3.conv1/bn.weight", "decoder.tp.u2.dense.units.1.preact_bna/bn.bias", "decoder.tp.u3.dense.units.3.conv1/bn.running_mean", "decoder.tp.u2.dense.units.2.conv1.weight", "decoder.tp.u3.dense.units.2.conv2.weight", "decoder.tp.u0.conv.bias", "decoder.tp.u3.dense.units.7.preact_bna/bn.running_var", "decoder.tp.u2.dense.units.3.preact_bna/bn.weight", "decoder.tp.u2.dense.units.1.preact_bna/bn.running_var", "decoder.tp.u2.dense.units.3.conv2.weight", "decoder.tp.u3.dense.units.2.preact_bna/bn.running_var", "decoder.tp.u3.dense.units.3.conv1.weight", "decoder.tp.u2.dense.units.3.preact_bna/bn.bias", "decoder.tp.u3.dense.units.0.conv1/bn.running_mean", "decoder.tp.u0.bn.weight", "decoder.tp.u3.dense.units.7.conv1/bn.bias", "decoder.tp.u2.dense.units.3.conv1/bn.running_var", "decoder.tp.u3.dense.units.1.preact_bna/bn.weight", "decoder.tp.u2.dense.units.3.conv1/bn.weight", "decoder.tp.u2.dense.units.3.conv1/bn.running_mean", "decoder.tp.u2.dense.units.0.preact_bna/bn.weight", "decoder.tp.u3.dense.units.3.conv1/bn.bias", "decoder.tp.u3.dense.units.7.conv2.weight", "decoder.tp.u3.dense.units.0.preact_bna/bn.running_var", "decoder.tp.u2.dense.units.2.preact_bna/bn.running_var", "decoder.tp.u3.dense.units.2.conv1/bn.running_var", "decoder.tp.u3.dense.units.1.preact_bna/bn.running_var", "decoder.tp.u3.dense.units.7.conv1.weight", "decoder.tp.u3.dense.units.1.preact_bna/bn.bias", "decoder.tp.u3.dense.units.6.conv1/bn.running_mean", "decoder.tp.u3.dense.units.2.preact_bna/bn.running_mean", "decoder.tp.u3.dense.units.6.conv1/bn.running_var", "decoder.tp.u3.dense.units.5.preact_bna/bn.running_mean", "decoder.tp.u2.dense.units.0.conv1.weight".

I tried several environments with different versions of pytorch, cuda, python ..., different models (fast and original) ... nothing to do.
I must be making a mistake somewhere, but where?
Thank you for your help

Phil, big fan of HOVERNET!

**Comment by simongraham** [comment]
Hi Phil - really nice to hear that you are a fan of our work. 

Please can you confirm that you are not unzipping the files and that you are supplying the path to the `tar` file.

**Comment by vqdang** [comment]
CoNSeP model or checkpoint for model with typing must provide the following arguments
>  --nr_types=<n>              Number of nuclei types to predict. [default: 0]
else the `decoder.tp` branch wont be defined. Additionally, please check the sample run script.

**Comment by Filoudataset** [comment]
Thank you very much, it works!
for those who would be facing this problem, here is the command line that worked for me:
python run_infer.py --gpu=0 --nr_types=5 --type_info_path=type_info.json --batch_size=64 --model_mode=fast --model_path=HVN_fast_monusac.tar --nr_inference_workers=8 --nr_post_proc_workers=16 tile --input_dir=C:/Users/rocha/HVN_infer_depart/ --output_dir=C:/Users/rocha/HVN_infer_arrivee/ --mem_usage=0.1 --draw_dot --save_qupath

PS: If I'm a Hovernet fan it's just because it's by far the best nuclear segmentation technique I've been able to test.
