### ISSUE TITLE
Generate `.mat` files from custom segmentations

### ISSUE THREAD

**Issue by Tato14** [vqdang/hover_net#123]
I have some segmentations generated with our samples which I would like to use for retraining HoverNet. Somethink like:
![segmentation](https://user-images.githubusercontent.com/33808607/119660062-1c272580-be2f-11eb-9121-f87b93daf2ee.png)

We performed the segmentation using [QuPath](https://qupath.github.io/) and I am able to generate the image-mask pair as you see in the previous image. However, I am not quite sure how to generate the .mat file from here. Sorry if there is any code explanation of this in the repo but I didn't find any hint on how to generate those. Any advice?

**Comment by simongraham** [comment]
Hi @Tato14 ,

To make the `.mat` file. You need to create an 'instance map` and a 'type map'. The instance map is a 2D map the same size as the input image where each nucleus is uniquely labelled. For example, 0 would be background and nuclei must be labelled between 1 and N, where N is the number of nuclei. I see that in your example above nuclei may not be uniquely labelled. Also, there seems to be some artefacts around the nuclei that you may need to deal with. The type map then is also a 2D map, but with each nucleus labelled from 1-C, where C is the number of classes. You can download the CoNSeP dataset and take a look at the instance and type map to investigate this further. When you have these 2 arrays, you can save it like this:

```
import scipy.io as sio

label = sio.savemat('label.mat', {'inst_map': inst_map, 'type_map': type_map})
```

You can see that we first specify the path for where to save the `mat` file and then provide a dictionary to save. Then, you can extract patches like we do with `extract_patches.py`. Hope this helps.

**Comment by Tato14** [comment]
Hi @simongraham. Thanks for the accurate reply. I was aware of the content of the `mat` file but I was wondering if you have any hint to create the 'instance map', the 'type map' and the 'centroid map' starting from an image-mask similar to the previous post image (without the artifacts, of course).

Concretely, I was hoping to some kind of notebook or code to perfrom this. If this is not the case I would try to produce one by myself. In any case, any help would be very welcome :smile:

**Comment by simongraham** [comment]
It is hard to give any advice on the generation of this map because people use different software to generate the annotation and so the format of the output can be different. For this project, we drew the nuclear boundaries using a transparency layer in GIMP. Then we saved the transparency layer before converting it to an instance map. For this, we made sure that any touching nuclei were different colours to make sure that they were separated. Then, we used `measurements.label()` on each colour separately before combining them into the overall prediction map.

**Comment by Tato14** [comment]
Thanks for the feedback. I found a quite easy way to get the `instance map` and `type map` using QuPath. If anyone is interested, see this discussion in the [image.sc forum](https://forum.image.sc/t/qupath-python-import-export-instance-segmentation-masks-for-binary-classification/49410/8). Then I was wondering if the centroid coordinates are needed for the `extract_patches.py`

**Comment by simongraham** [comment]
Great! The centroid coordinates are only needed for computing the detection stats in `compute_stats.py`. You won't need them for training the model. If you wanted to get the centroids, then you can easily get them from the instance map, by using:

```
binary_map = inst_map[inst_map > 0] = 1
label_idx = np.unique(inst_map)
centroids = measurements.center_of_mass(binary_map, inst_map, label_idx[1:])
```

**Comment by OmarAshkar** [comment]
Hi @simongraham and @Tato14, 

I want to jump in here as I had a relevant question. I have two 2D matrices. One is 0,1,2 for 2 classes. Then I applied watershed to it to get the second matrix representing instance segmentation.  Is the concept of instance_map and  type_map?

Second, I used the snippet here in this thread, but I get an error "MatWriteError: Matrix too large to save with Matlab 5 format". So, I am doing something wrong here?


Any thread is appreciated.
Thanks!

> Hi @Tato14 ,
> 
> To make the `.mat` file. You need to create an 'instance map` and a 'type map'. The instance map is a 2D map the same size as the input image where each nucleus is uniquely labelled. For example, 0 would be background and nuclei must be labelled between 1 and N, where N is the number of nuclei. I see that in your example above nuclei may not be uniquely labelled. Also, there seems to be some artefacts around the nuclei that you may need to deal with. The type map then is also a 2D map, but with each nucleus labelled from 1-C, where C is the number of classes. You can download the CoNSeP dataset and take a look at the instance and type map to investigate this further. When you have these 2 arrays, you can save it like this:
> 
> ```
> import scipy.io as sio
> 
> label = sio.savemat('label.mat', {'inst_map': inst_map, 'type_map': type_map})
> ```
> 
> You can see that we first specify the path for where to save the `mat` file and then provide a dictionary to save. Then, you can extract patches like we do with `extract_patches.py`. Hope this helps.

**Comment by vqdang** [comment]
> I want to jump in here as I had a relevant question. I have two 2D matrices. One is 0,1,2 for 2 classes. Then I applied watershed to it to get the second matrix representing instance segmentation. Is the concept of instance_map and type_map?

The 1st matrix is the `type_map` and the 2nd matrix is the `instance_map`. Each non-zero value within `instance_map` denotes a different instance.

> Second, I used the snippet here in this thread, but I get an error "MatWriteError: Matrix too large to save with Matlab 5 format". So, I am doing something wrong here?

Saving in `.mat` is an old legacy. `.mat` can not store large matrices. I do not know the size (HxW) but its likely beyond what can be saved.

**Comment by OmarAshkar** [comment]
@vqdang Thanks! Can I store them as .npy? Is it allowable by the current implementation or I have to alter the code?
