### ISSUE TITLE
About training on the Pannuke dataset

### ISSUE THREAD

**Issue by kiven1213** [vqdang/hover_net#127]
Hello, I would like to ask how I should run the code on Pannuke? Is there any difference in how these two data sets are used? I saw in the code that there is no relevant script for the Pannuke data set. I downloaded the Pannuke data set from the official website and found that the mask and image in it are already in the format of.npy. Then do I not need to implement extract_patcher.py? But how do I process the Pannuke data set and then input it into the model for training? I hope you can answer my doubts. Thank you.

**Comment by simongraham** [comment]
Please refer to #125 . If you have more specific questions after looking at that issue, please comment back in #125
