### ISSUE TITLE
WSI inference time and removing branches in network for binary images prediction only

### ISSUE THREAD

**Issue by pranathivemuri** [vqdang/hover_net#128]
Hi again @simongraham and @vqdang Thanks again for your previous replies and the hovernet. I was wondering two things as below

1. What is the usual inference time you have observed for a WSI? 
2. How would I go about removing branches in the model .npz files network for binary images prediction only?

Any input would be appreciated! Thank you!

**Comment by simongraham** [comment]
Hi @pranathivemuri ,

This depends a lot on your setup. For example, the number of GPUs used for inference, the number of workers used during post processing, the size of the WSI etc etc. So it is quite hard to give a reliable estimate. Can you provide your current configuration, your computer specification and current estimated WSI processing time and we can speak further. 

For 2., we would need more information to help you out with this. The network will inherently perform binary segmentation and then perform pixel-wise classification for each segmented nucleus. So you don't need to do anything to any files, you just need to appropriately use the output. Please provide more information on this and we can give a better response. For example, are you processing image tiles, WSIs etc etc?

**Comment by pranathivemuri** [comment]
1. GPU - NVIDIA Corporation GV100 [TITAN V]
2. Number of post porcessing workers - 10,   --gpu=<id>  0 = default arguments and using https://github.com/simongraham/hovernet_inference
3. Size of WSI - (67343, 143424, 4) - max size,4 resolutions, 2.44 GB file
4. Time taken - 4.25 hours
5. I understand that we are currently just getting the binary output we would need from the output from hovernet, but I do not need the default classes detected but I am just looking for the binary classification output from the network, so I was just wondering if I could save time by removing the parts of network that do the instance classification

**Comment by vqdang** [comment]
Simon version as far as i known doesn't support Parallelism very well. Have you tried the one in this repos? This version will scale near linearly wrt #GPU (or batch size). For example, with 4 1080Ti I would expect the WSI in your specs would take around 1h30-2h30 (in case the entire WSI is tissue and there is little background).

5. For this repos, you can strip off the type branch yourself by removing variable with `decoder.tp` prefix in the npz. You can load it up as a dict. To run with this new npz, you need to set `nr_type=0` in the cmd.

**Comment by pranathivemuri** [comment]
I am going to try both options suggested and let you know how it goes, thanks so much for the input!

**Comment by simongraham** [comment]
Good point @vqdang - @pranathivemuri you should try using the PyTorch version, as opposed to the inference code you are using in [this repo](https://github.com/simongraham/hovernet_inference). We are actively maintaining the PyTorch version, so please use this one :)
