### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by ciaobladoo** [vqdang/hover_net#129]
I keep getting bus errors while running WSI inference.
Here is the error message:
>|2021-06-06|14:50:59.640| [INFO] .... Detect #GPUS: 2
|2021-06-06|14:51:03.707| [INFO] ................ Process: 1331660
|2021-06-06|14:51:12.716| [INFO] ........ Preparing Input Output Placement: 9.001625396311283
Process Chunk 4/20:   0%|                                | 0/12 [00:00<?, ?it/s]./run_wsi.sh: line 14: 44530 Bus error               (core dumped) python run_infer.py --gpu=0,1 --nr_types=6 --type_info_path=type_info.json --model_mode=fast --model_path=pretrained/hovernet_fast_pannuke_type_tf2pytorch.tar --nr_inference_workers=8 --nr_post_proc_workers=16 wsi --proc_mag=20

input_dir output_dir and cache_path are omitted.

And also:
>UserWarning: semaphore_tracker: There appear to be 35 leaked semaphores to clean up at shutdown
  len(cache))

Any idea what could have caused the problems and how to resolve them? Thanks!

**Comment by simongraham** [comment]
Hi. Can you confirm whether you are running a single script or whether you are running multiple scripts in parallel. On a side note, I see that you are using 20x for processing. We trained using 40x and so ideally you should process with the same magnification.

**Comment by ciaobladoo** [comment]
Hi Simon, thank you for your reply!

This happens when I run a single WSI and in the middle of inference. I managed to resolve this issue for most of the slides by setting --nr_inference_workers=1 (which is also faster).  But now it gives me a new error at the beginning of post-processing (silence crash assertion failure). I am trying to see if different nr_post_proc_workers values could help.

With respect to the magnification, I have always resized when I was using the TensorFlow code for tile inference. I assumed this code should take care resizing for me when I set -proc_mag=20, is that not the case?

**Comment by simongraham** [comment]
Is it during the inference or post processing stage that it crashes? Try setting `nr_inference_workers` and `nr_post_processing_workers` to 0. Can you post the entire terminal output so we can maybe dig into it a bit more.

With regards to `--proc_mag`, you are explicitly saying above that you want to process at 20x. It doesn't mean that this is the bae resolution of your WSI, but it means that you want to process the slide at that desired resolution.

**Comment by ciaobladoo** [comment]
Thank you! I will try setting both nr_inference_workers and nr_post_processing_workers  to 0 and see if this resolves my problem. I will post the terminal output if there is more error message. 

I am confused about the --proc_mag argument. I see that the code does load metadata of my XXX.svs file which says the magnification level is 20X. Was this information not used? I was able to get the inference finished for some of the slides and the result looks good to me.

**Comment by vqdang** [comment]
`--proc_mag` indicates which resolution will the patch be loaded from WSI and input to the network. For example, if an WSI has baseline of 10x, the patch will be up-scale by 2x. If an WSI has baseline of 40x, the patch will be down-scaled. This is a very rought explanation and internally the code will do not just that.

The important thing is the checkpoint was trained at 40x, so by declaring `--proc_mag 20`, you are inputting patch being of resolution different from the checkpoint. And this may lead to bogus result. If you have alrd verified visually that the output still make sense to you, then there may be no problem.

On another note, if you still have the BUS problem, please also provide your hardware info. We know for a while that the code has some unexpected behaviors on cloud or cluster so more info is better.

**Comment by ciaobladoo** [comment]
Actually when setting workers to 0 I immediately get the following error:


|2021-06-07|14:08:09.118| [INFO] .... Detect #GPUS: 1
|2021-06-07|14:08:21.129| [INFO] ................ Process: 1015893
|2021-06-07|14:08:38.892| [INFO] ........ Preparing Input Output Placement: 17.761795919388533
Process Chunk 0/30:   0%|                                | 0/33 [00:00<?, ?it/s]|2021-06-07|14:08:44.712| [ERROR] Crash
Traceback (most recent call last):
  File "/histopathology/nuclear_segmentation/hover_net/infer/wsi.py", line 749, in process_wsi_list
    self.process_single_file(wsi_path, msk_path, self.output_dir)
  File "/histopathology/nuclear_segmentation/hover_net/infer/wsi.py", line 552, in process_single_file
    self.__get_raw_prediction(chunk_info_list, patch_info_list)
  File "/histopathology/nuclear_segmentation/hover_net/infer/wsi.py", line 376, in __get_raw_prediction
    chunk_patch_info_list[:, 0, 0], pbar_desc
  File "/histopathology/nuclear_segmentation/hover_net/infer/wsi.py", line 289, in __run_model
    for batch_idx, batch_data in enumerate(dataloader):
  File "/anaconda3/envs/hovernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/anaconda3/envs/hovernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/anaconda3/envs/hovernet/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/anaconda3/envs/hovernet/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/anaconda3/envs/hovernet/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/anaconda3/envs/hovernet/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 86, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'numpy.memmap'>
Process Chunk 0/30:   0%|                                | 0/33 [00:00<?, ?it/s]


About --proc_mag, is there a place to modify the code to resize the tiles before applying the neural network in WSI mode?

**Comment by vqdang** [comment]
You dont need to do resize, but you have to provide `proc_mag` correctly, by default ist 40. `proc_mag` means run inference with patches at this `proc_mag` resolution.

For the first error, try adding `patch_data  = np.array(patch_data )` above this https://github.com/vqdang/hover_net/blob/abf6d891357393b651b954203647331602919bb6/dataloader/infer_loader.py#L98
For the 2nd one, how much memory do you have? It seems there is not enough for thread communication. The version of the code you are using doesnt have polling till queue has slot, so you likely you can only set `postproc_worker=0`  to mitigate this.

**Comment by ciaobladoo** [comment]
Thank you I will try. I am still confused about the proc_mag. From your last comment it seems like even if I set proc_mag to 20 I am still sending the 20X tile as input to the network. That is technically wrong since the weights are trained on 40X, correct? I was using the tensorflow code for tile inference before and I always resized my tiles first,  but it is not convenient to do this in WSI mode.

**Comment by ciaobladoo** [comment]
I am still having "Bus error (core dumped)" somewhat randomly. I have set both workers to 0 and did the modification suggested by @vqdang. I am using a computer cluster. Here is an example of lscpu output on one of the node:

>Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                80
On-line CPU(s) list:   0-79
Thread(s) per core:    2
Core(s) per socket:    20
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
Stepping:              7
CPU MHz:               2552.069
CPU max MHz:           3900.0000
CPU min MHz:           800.0000
BogoMIPS:              4200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              28160K
NUMA node0 CPU(s):     0-19,40-59
NUMA node1 CPU(s):     20-39,60-79
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities

and once again the error message:

>|2021-06-08|09:16:14.587| [INFO] .... Detect #GPUS: 1
|2021-06-08|09:16:23.357| [INFO] ................ Process: 1718691
|2021-06-08|09:16:35.058| [INFO] ........ Preparing Input Output Placement: 11.699457224924117
Process Chunk 0/25: 100%|#########################| 7/7 [00:07<00:00,  1.08s/it]
Process Chunk 1/25: 100%|#######################| 24/24 [00:29<00:00,  1.22s/it]
Process Chunk 2/25: 100%|#########################| 8/8 [00:11<00:00,  1.41s/it]
Process Chunk 5/25: 100%|#######################| 59/59 [01:12<00:00,  1.23s/it]
Process Chunk 6/25: 100%|#####################| 113/113 [02:21<00:00,  1.25s/it]
Process Chunk 7/25: 100%|#######################| 79/79 [01:41<00:00,  1.29s/it]
Process Chunk 8/25: 100%|#######################| 28/28 [00:34<00:00,  1.23s/it]
Process Chunk 10/25: 100%|######################| 28/28 [00:33<00:00,  1.21s/it]
Process Chunk 11/25:  17%|###8                  | 17/98 [00:22<01:45,  1.30s/it]/anaconda3/envs/hovernet/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Process Chunk 11/25: 100%|######################| 98/98 [02:05<00:00,  1.28s/it]
Process Chunk 12/25:  48%|##########1          | 52/108 [01:07<01:13,  1.32s/it]./run_wsi.sh: line 14: 369264 Bus error               (core dumped) python run_infer.py --gpu=0 --nr_types=6 --type_info_path=type_info.json --model_mode=fast --model_path=pretrained/hovernet_fast_pannuke_type_tf2pytorch.tar --nr_inference_workers=0 --nr_post_proc_workers=0 wsi --proc_mag=20 

> Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/home/fengc/anaconda3/envs/hovernet/lib/python3.6/multiprocessing/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/fengc/anaconda3/envs/hovernet/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/home/fengc/anaconda3/envs/hovernet/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/fengc/anaconda3/envs/hovernet/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/home/fengc/anaconda3/envs/hovernet/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

Thank you!

**Comment by ciaobladoo** [comment]
I figured out the problem. It's kind of embarassing. I modified the code so that I can all WSI in parallel on the cluster. But I was using the same cache path...
