### ISSUE TITLE
errors running inference

### ISSUE THREAD

**Issue by Ghulam111** [vqdang/hover_net#13]
![Untitled](https://user-images.githubusercontent.com/55826990/66179905-41fc2700-e65a-11e9-8aef-3fa3f445660a.png)
i run into this error when running inference

**Comment by vqdang** [comment]
A quick search on Google indicates that this error is due to corrupted checkpoints. I suggest you trying another saved checkpoints. The checkpoint should be at least 500MB in total. 

Each checkpoint consists of 2 files, `model-XXXXXX.data-00000-of-00001` and `model-XXXXXX.index` with XXXXXX is some number, such as 16280. Your checkpoint path should point to the .index file.

**Comment by Ghulam111** [comment]
alright. let me check

**Comment by Ghulam111** [comment]
files are 344,562 KB , is that not alright i reduced to 40 epochs , not 50

**Comment by Ghulam111** [comment]
![Untitled](https://user-images.githubusercontent.com/55826990/66180728-aa003c80-e65d-11e9-8f8b-1767dd798b2a.png)

i also saw this error ,resolved it by putting all files in that directory instead of folder "00"

**Comment by vqdang** [comment]
Ok, so let's start again, I'm lost on what you have done and what I know about the situation. So first please try to answer subsequent questions:
1. How did you try to run the inference?
2. Did you modify anything in the source code/output directories?

**Comment by Ghulam111** [comment]
i ran inference with `python infer.py --gpu="0"` and code changes in config.py are as under
![Untitled](https://user-images.githubusercontent.com/55826990/66181005-9ef9dc00-e65e-11e9-9cad-651615c6728f.png)

**Comment by Ghulam111** [comment]
![Untitled](https://user-images.githubusercontent.com/55826990/66181082-f730de00-e65e-11e9-9e9b-0d8b442e3960.png)

**Comment by vqdang** [comment]
> i ran inference with `python infer.py --gpu="0"` and code changes in config.py are as under
> ![Untitled](https://user-images.githubusercontent.com/55826990/66181005-9ef9dc00-e65e-11e9-9cad-651615c6728f.png)

Ok, from this, I can see that you are trying to supply your checkpoint of choice. To do that, you first have to set `self.inf_auto_find_chkpt=False` else it will try to search within the training folder using `stats.json`. If you move everything out to another folder, it will fail.

Secondly, your checkpoint path is incorrect, it should be `self.inf_model_path = "sthg_sthg.index"`. As I mentioned above, you have to point the path to the *.index* file of the checkpoint.

And from your 2nd images, lots of checkpoint have 0KB so I think sthg is seriously wrong there.
> ![Untitled](https://user-images.githubusercontent.com/55826990/66181082-f730de00-e65e-11e9-9e9b-0d8b442e3960.png)

Also, the training finishes with folder `01` so you should use the checkpoint within that folder, not `00`.

**Comment by Ghulam111** [comment]
inference is somehow running after suggested changes.

**Comment by sidmanowa** [comment]
Could I know where the trained weights are stored for inference?

Thanks,
Sid

**Comment by Ghulam111** [comment]
where can we see the final AJI and F1 score after running inference.py and process.py

**Comment by vqdang** [comment]
@Ghulam111, hi, you have to run the https://github.com/vqdang/hover_net/blob/master/src/compute_stats.py to calculate the statistics, it will be printed out on the terminal. Please read https://github.com/vqdang/hover_net/blob/6969ef33819d0180e37d8a89b7afb4b2a57c05f5/src/compute_stats.py#L196-L209 to know how to provide the file with correct input arguments.

**Comment by Ghulam111** [comment]
im getting these errors
![image](https://user-images.githubusercontent.com/55826990/66764826-284cb200-ee9a-11e9-8882-180b07aaade3.png)

**Comment by Ghulam111** [comment]
![image](https://user-images.githubusercontent.com/55826990/66764896-487c7100-ee9a-11e9-858c-95c40f13f711.png)

**Comment by vqdang** [comment]
You cant provide the path like that in Windows, try wrapping the entire path around `"` and switching `\` to `/` .

**Comment by Ghulam111** [comment]
alright ill let you know

**Comment by Ghulam111** [comment]
by the way .mat file print gives this 
![image](https://user-images.githubusercontent.com/55826990/66766301-5089e000-ee9d-11e9-89e5-78b160e2a732.png)

**Comment by vqdang** [comment]
What do you want to ask about the output? `inst_map` contain the nuclei instances, each instance is coded as non-zero integer.

**Comment by Ghulam111** [comment]
does it look fine

**Comment by Ghulam111** [comment]
r im putting directories in function call ,still getting same error
![image](https://user-images.githubusercontent.com/55826990/66766823-95624680-ee9e-11e9-823d-6c210af09e97.png)

**Comment by vqdang** [comment]
```
run_nuclei_inst_stat('D:/kumar/test_same/labels/', 'etc/_proc')
```
Ok, I looked back again, you point to the wrong output directory. You should point to the `*/_proc`, it contains the post-processing output (final output). You are pointing it to the raw outputs.

**Comment by Ghulam111** [comment]
yes i fixed that earlier, but im still getting the same error 
![image](https://user-images.githubusercontent.com/55826990/66767731-95fbdc80-eea0-11e9-8148-ce8c402e655d.png)

**Comment by vqdang** [comment]
Hmn, may be you try commenting this one out?
https://github.com/vqdang/hover_net/blob/6969ef33819d0180e37d8a89b7afb4b2a57c05f5/src/compute_stats.py#L167

I dont rmb exactly what is the shape of kumar GT (HxWx1 or HxW), but CoNSeP data is (HxWx2) so may be that line was for CoNSeP. 

It would be nice if I know where the error was thrown.

**Comment by Ghulam111** [comment]
kumar dataset groundtruth is 1000 x 1000 , i just checked
i have commeted out that line as well
![image](https://user-images.githubusercontent.com/55826990/66768450-2555bf80-eea2-11e9-85d7-6a3fba319d77.png)

**Comment by Ghulam111** [comment]
i think its not reading npy files properly

**Comment by vqdang** [comment]
From your screenshot, I only see sthg wrong with numpy and I have no idea which line in my code that it came from.

**Comment by Ghulam111** [comment]
can simon graham help me

**Comment by vqdang** [comment]
He is in the same area as me now. I will discuss with him tmr and see what we can do to help you.
In the meantime, could you put 
```
plt.subplot(1,2,1)
plt.imshow(true)
plt.subplot(1,2,2)
plt.imshow(pred)
plt.show()
```
before this https://github.com/vqdang/hover_net/blob/6969ef33819d0180e37d8a89b7afb4b2a57c05f5/src/compute_stats.py#L173

If the input is correct, you should see 2 images displayed.

**Comment by Ghulam111** [comment]
![image](https://user-images.githubusercontent.com/55826990/66769439-b168e680-eea4-11e9-8ce4-0a0e6609ce58.png)

**Comment by Ghulam111** [comment]
![image](https://user-images.githubusercontent.com/55826990/66769487-c9406a80-eea4-11e9-9cea-589e5b80e22c.png)

**Comment by vqdang** [comment]
Please edit the code as provided to see the display and provide the screenshot of the plot. Your attached code is different from what I wrote.

**Comment by simongraham** [comment]
Hi @Ghulam111 ,

I agree with @vqdang - it seems that you are not pointing to the correct directory and it is probably to do with minor things such as `/`. First of all, please can I suggest that you remove the `/` at the end of your `pred_dir`. Please inform us of what happens here. After you have done this, comment line 167 as @vqdang also suggested. Let us know the outcome of this and we will go from there.

**Comment by Ghulam111** [comment]
i have rechecked directories and i have also commented out line 167 , but getting same error
![image](https://user-images.githubusercontent.com/55826990/66769967-fd685b00-eea5-11e9-9d9f-fa10c5b98e79.png)

this is predictions directory 
![image](https://user-images.githubusercontent.com/55826990/66770015-153fdf00-eea6-11e9-9a00-be7e785ca773.png)

this is the labels
![image](https://user-images.githubusercontent.com/55826990/66770060-30aaea00-eea6-11e9-9777-bc1a8d3f3f58.png)

this is the code at compute_stats.py 
![image](https://user-images.githubusercontent.com/55826990/66770120-520bd600-eea6-11e9-9457-e58018bdcfc0.png)

this is what .mat file looks like 
![image](https://user-images.githubusercontent.com/55826990/66770171-77004900-eea6-11e9-9a4e-5f22ed709186.png)

**Comment by vqdang** [comment]
OK I figure what stupid thing happened, please invert the input so that
`run_nuclei_inst_stat('D:/kumar/test_same/labels/', 'etc/_proc/')`
becomes
`run_nuclei_inst_stat('etc/_proc/', 'D:/kumar/test_same/labels/')`

The param is inverted in the function. I should have done a better refactor check.
Nice call @Ghulam111

**Comment by Ghulam111** [comment]
ok ill update you

**Comment by Ghulam111** [comment]
ok the code is running and output is produced , thanks a lot 👍

**Comment by vqdang** [comment]
You are welcome :D, thanks for letting us find out a quite comical but fatal bug.

**Comment by siddharthamantrala** [comment]
@vqdang and @simongraham I trained the network and ran the inference on the CoNSeP trest set. The following is the output (Left is the overlay and right is the prediction). Could I know if the output is right and why is there a difference between the overlay colors and the predicted colors. Please advice.

Thanks,
Sid
![Screenshot (138)](https://user-images.githubusercontent.com/35974925/66918603-53233b80-f03d-11e9-9319-a53537df4e19.png)

**Comment by vqdang** [comment]
@siddharthamantrala Each color of the overlay on the left represents the type of each nuclei instance, each nuclei type is of 1 color, please check the paper for the color meaning. 

On the other hand, each color of the overlay on the prediction on the right indicate 1 instance i.e each instance will have 1 color. We don't output the overlay for nuclei type for the prediction.

**Comment by siddharthamantrala** [comment]
Thanks for the information @vqdang , could I know if there is a way to overlay the nuclear type also?

Thanks,
Sid

**Comment by simongraham** [comment]
Hi @siddharthamantrala ,

The visualisation code assigns a random colour for each positive unique value within the prediction map. Currently, this is only done for the instance prediction. You can do this in the same way for the nuclear types, but if done in the same way as the default setting, this will lead to random colour assignment of each nuclear type and therefore the types will not have the same colour boundary from image to image. Instead, determine the colour of each image within the `visualize_instanes()` function by using the `colour` argument, which is a list of RGB values. For instance, if there are 3 types of nuclei within the image, you can use:

`visualize_instances(mask, canvas, color=[[255,0,0], [0,255,0], [0,0,255]])`

**Comment by siddharthamantrala** [comment]
@simongraham, thanks for the suggestion,  if that's the case could I know if there is way to know about nuclear classification results?

**Comment by simongraham** [comment]
@siddharthamantrala please can you open up a new issue - this issue is specifically about inference. We will then address your question there.

**Comment by Ghulam111** [comment]
- While running `compute_stats` for `type` classification the console produces no output.

- The ground_truth labels in ConSep dataset are in npy format , but the code is reading ground_truth as .mat files. ?

**Comment by zerodohero** [comment]
> inference is somehow running after suggested changes.
Hello, how did you solve the problem?I have the same problem, and my saved node is also 0K for a lot of files, as you showed
