### ISSUE TITLE
How to reduce memory usage?

### ISSUE THREAD

**Issue by ciaobladoo** [vqdang/hover_net#130]
I am trying to run WSI inference on a folder of large WSIs. I requested 40G memory and many of them exceeded this memory limit even with a batch size of 4. What is the most effective way to reduce memory usage?

Thank you!

**Comment by ciaobladoo** [comment]
Seems like there is no way around it. I requested 80G instead and solved the problem.

**Comment by vqdang** [comment]
The memory usage depends mostly on the `nr_postproc_worker` rather than the batch size (batch size affects GPU memory).
