### ISSUE TITLE
How is the JSON file generated in the output

### ISSUE THREAD

**Issue by aasrith9988** [vqdang/hover_net#131]
Hi again @simongraham and @vqdang  and Thanks again for your previous replies and the hovernet. I was wondering 
How does the json file is generated for the predicted test images, and "self.__save_json(save_path, inst_info_dict, None)", what does this statement do , and i also want the json in a particular format so that i can display the annotations on Histomicks UI, is that possible , what changes have to be made for that?

**Comment by vqdang** [comment]
`self.__save_json` will convert the prediction dict to json compatible.
>i also want the json in a particular format so that i can display the annotations on Histomicks UI

You better do the conversion basing on the output .json (i.e create an external function). You can create a proto annotation on Histomic and see how to match hovernet json over.
