### ISSUE TITLE
Masking for WSI 

### ISSUE THREAD

**Issue by xingyi19** [vqdang/hover_net#132]
Hi, What is the masking method used for processing the WSI? If we are going to provide our own mask, what file format will that be?

**Comment by vqdang** [comment]
https://github.com/vqdang/hover_net/blob/abf6d891357393b651b954203647331602919bb6/infer/wsi.py#L489
Naive morphology operation, main purpose is only to reduce inference time. I recommend using your own mask if possible. The mask should be save as .png and in gray scale. Any value > 0 is assumed to be the masked area.
https://github.com/vqdang/hover_net/blob/abf6d891357393b651b954203647331602919bb6/infer/wsi.py#L480

**Comment by xingyi19** [comment]
Thanks for the information, so should the supplied mask have the same scale as the WSI, i.e. exact same number of pixels?

**Comment by vqdang** [comment]
No, it can be at the downsample size. The auto-generated mask is at x1.25 objective power for example.
