### ISSUE TITLE
compute_stats.py [for type mode]

### ISSUE THREAD

**Issue by MTalhaAbdullah** [vqdang/hover_net#133]
I failed to get compute_stats output using this command: 

`python compute_stats.py --mode=type --pred_dir=/home/hovernet/mydrive/HoverNet/hover_net/logs/infer_output/mat  --true_dir=/home/hovernet/mydrive/HoverNet/hover_net/dataset/CoNSeP/Test/Labels`

> Traceback (most recent call last):
>   File "compute_stats.py", line 248, in <module>
>     run_nuclei_type_stat(args.pred_dir, args.true_dir)
>   File "compute_stats.py", line 104, in run_nuclei_type_stat
>     paired_all = np.concatenate(paired_all, axis=0)
>   File "<__array_function__ internals>", line 6, in concatenate
> ValueError: need at least one array to concatenate

Apparently, the code failed to get the correct .mat files in the predictions folder. After opening the prediction .mat file, I only got  "inst_map"  and inst_type. I wonder there is no "inst_centroid" in the prediction folder got through inference.

**Comment by MTalhaAbdullah** [comment]
Please guide what am I doing wrong?

`python run_infer.py --nr_types=5 --type_info_path=/home/hovernet/mydrive/HoverNet/hover_net/type_info.json --model_path=logs/01/net_epoch=50.tar --model_mode=original tile --input_dir=/home/hovernet/mydrive/HoverNet/hover_net/dataset/CoNSeP/Test/Images --output_dir=/home/hovernet/mydrive/HoverNet/hover_net/logs/infer_output
`
I am using this command for inference

**Comment by vqdang** [comment]
You are not doing anything wrong. The current saving format for .mat is infact quite different compared to the format expected by the old stat code. Rerun inference should now have format as expected by metric code. Still, for consep  you need to uncomment

https://github.com/vqdang/hover_net/blob/a0f80c7acb9a14964d597d15d7ebd9688a0230cb/compute_stats.py#L62-L64

**Comment by MTalhaAbdullah** [comment]
> You are not doing anything wrong. The current saving format for .mat is infact quite different compared to the format expected by the old stat code. Rerun inference should now have format as expected by metric code. Still, for consep you need to uncomment
> 
> https://github.com/vqdang/hover_net/blob/a0f80c7acb9a14964d597d15d7ebd9688a0230cb/compute_stats.py#L62-L64

Still same error, compute_stats.py is not working for type mode.

**Comment by MTalhaAbdullah** [comment]
> I failed to get compute_stats output using this command:
> 
> `python compute_stats.py --mode=type --pred_dir=/home/hovernet/mydrive/HoverNet/hover_net/logs/infer_output/mat --true_dir=/home/hovernet/mydrive/HoverNet/hover_net/dataset/CoNSeP/Test/Labels`
> 
> > Traceback (most recent call last):
> > File "compute_stats.py", line 248, in 
> > run_nuclei_type_stat(args.pred_dir, args.true_dir)
> > File "compute_stats.py", line 104, in run_nuclei_type_stat
> > paired_all = np.concatenate(paired_all, axis=0)
> > File "<**array_function** internals>", line 6, in concatenate
> > ValueError: need at least one array to concatenate
> 
> Apparently, the code failed to get the correct .mat files in the predictions folder. After opening the prediction .mat file, I only got "inst_map" and inst_type. I wonder there is no "inst_centroid" in the prediction folder got through inference.

Same issue as earlier, maybe the order of dictionary keys in pediction .mat files causing error. Shouldn't the order of inst_uid and inst_type be the same as GT ?

**Comment by MTalhaAbdullah** [comment]
@vqdang Thank you so much, now it's working. I just had to add "/" at the end of the path to make it run.
