### ISSUE TITLE
Is there a faster way for prediction?

### ISSUE THREAD

**Issue by aasrith9988** [vqdang/hover_net#136]
Hi @simongraham and @vqdang , i am actually predicting result for a whole slide image ,which is around 10gb in size and has dimensions 250000 X 350000 , i am dividing it into tiles of size 1024 X 1024 and giving it for prediction using the following command :- 
python run_infer.py \
--gpu='0,1,2,3' \
--nr_types=5 \
--type_info_path=type_info.json \
--batch_size=32 \
--model_mode='original' \
--model_path=assrith_hovernet.tar \
--nr_inference_workers=4 \
--nr_post_proc_workers=4 \
tile \
--input_dir=exp_output/sample/imgs/ \
--output_dir=exp_output/sample/pred/ \
--draw_dot \
--save_qupath

but  it is taking around 16 hours just to predict the tiles , is there any faster approach to get the work done in lesser time.

**Comment by simongraham** [comment]
Hi @aasrith9988 

 It seems that your WSI is huge, so we should expect it to take a while, but there are some things you can do. 

One way woiuld be to instead train using `fast` mode. The difference here is that we output a slightly lager patch size and therefore can use a larger stride during inference. Try increasing the number of inference and post processing workers. Try increasing the batch size.

**Comment by aasrith9988** [comment]
Hi @simongraham  my WSI slide is around 10 GB , and i already removed the --save_qupath from the CLI , since the WSI i am using is huge , will the WSI mode would be able to handle such huge image ?

**Comment by simongraham** [comment]
Yes it will be able to handle it, but because it generates memory maps for the WSI as temporary files, you may need a large amount of space free at your specified `cache` location.

**Comment by aasrith9988** [comment]
@simongraham  thank you for your swift response and guidance , our lab is more than happy to use this project

**Comment by simongraham** [comment]
We are glad that your lab finds it useful 😊
