### ISSUE TITLE
Color Map

### ISSUE THREAD

**Issue by luantunez** [vqdang/hover_net#137]
Thank you for sharing your work! It ran successfully!
I was just wondering where can I find the labels for the colors for each model. I can see the color but not the specifics of which type of cell is each model identifying.
Thank you very much in advance!

**Comment by simongraham** [comment]
Hi @luantunez ,

This depends on the model that you are using. 

*PanNuke*
0: Background
1: Neoplastic
2: Inflammatory
3: Connective
4: Dead
5: Non-Neoplastic Epithelial

*MoNuSAC*
0: Background
1: Epithelial
2: Lymphocyte
3: Macrophage
4: Neutrophil

**Comment by luantunez** [comment]
Thank you! But which colors do those number belong to?

**Comment by simongraham** [comment]
Which model are you using? If using PanNuke model, then the overlay colours are getting pulled from [here](https://github.com/vqdang/hover_net/blob/master/type_info.json).

**Comment by luantunez** [comment]
Great! and is there a similar file for the rest of the models?

**Comment by simongraham** [comment]
No this is left to be modified by the user in case they trained with their own dataset. We will specify the class id : class name mapping in the next couple of days, but will leave `type_info.json` to be defined by the user.
