### ISSUE TITLE
{opt.py}

### ISSUE THREAD

**Issue by AliOlamat** [vqdang/hover_net#139]
Hi again,
I have a question regarding the parameter "phase_list" in opt.py!!!
Why do we have two identical sub variable: "run_info" inside the "phase_list" ?

![image](https://user-images.githubusercontent.com/81868638/124384598-c0c43f00-dcda-11eb-9f03-28b024da46f0.png)

Thank you

**Comment by simongraham** [comment]
If you refer to the paper, we train the network in 2 stages: i) freeze the imagenet weights in encoder and train the decoders for 50 epochs, 2) unfreeze the entire network and train all layers. Each dict refers to the `run_info` for each of these stages.

**Comment by AliOlamat** [comment]
Thank you very much
I got the idea
👍
