### ISSUE TITLE
Cannot reproduce the monusac result

### ISSUE THREAD

**Issue by TEPPEIKNS** [vqdang/hover_net#142]
Hi. I found the result that was applied your model to monusac test dataset the below website.
We tried to reproduce the result but we couldn't.
Could you tell me how to reproduce the result. Is there problem our command ? The code is cloned from this github.

https://monusac-2020.grand-challenge.org/Data/

Command and color pattern
```
command 
!python run_infer.py \
--nr_types=5 \
--type_info_path=PATH_TO_JSON \
--batch_size=48 \
--model_mode=fast \
--model_path=PATH_TO_hovernet_fast_monusac_type_tf2pytorch.tar \
--nr_inference_workers=16 \
--nr_post_proc_workers=16 \
tile \
--input_dir=PATH_TO_IMAGES \
--output_dir=PATH_TO_OUT

color pattern
{
    "0" : ["background", [255,   255,  255]],
    "1" : ["Epithelial", [255,   0,   0]],
    "2" : ["Lymphocyte", [0  , 255,   0]],
    "3" : ["Macrophage", [0  ,   0, 255]],
    "4" : ["Neutrophil", [255, 255,   0]]
}
```

Dataset
https://drive.google.com/file/d/1G54vsOdxWY1hG7dzmkeK3r0xz9s-heyQ/view?usp=sharing

**Our result**
![image](https://user-images.githubusercontent.com/5231107/125070317-c236a280-e0f2-11eb-9d0c-5bb9f0df3060.png)
![TCGA-2Z-A9JG-01Z-00-DX1_1](https://user-images.githubusercontent.com/5231107/125103244-1f444f80-e117-11eb-8b49-f2eb8655c184.png)
![TCGA-49-6743-01Z-00-DX2_001](https://user-images.githubusercontent.com/5231107/125103388-43079580-e117-11eb-96ac-da04ad578c06.png)

**Your result from the web site (L1 - TIA Lab result)**
![image](https://user-images.githubusercontent.com/5231107/125070330-c662c000-e0f2-11eb-9739-7ef4b566817e.png)

![image](https://user-images.githubusercontent.com/5231107/125103369-3edb7800-e117-11eb-8438-5c9e7aab2c97.png)

![image](https://user-images.githubusercontent.com/5231107/125103443-50bd1b00-e117-11eb-8fcc-fc266acb3309.png)

**Comment by simongraham** [comment]
For some reason, the MoNuSAC test images are saved as BGR. You will need to convert them back to RGB before processing. You can do this simply be applying `img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)`.

Try that and let us know how you get on :)

**Comment by TEPPEIKNS** [comment]
Thanks for your reply ! 
I tried to convert color order and I got the result.
The first and second images are be able to be reproduced, but it seems that the third one is not enough. 
Is there any another reason ? 

![image](https://user-images.githubusercontent.com/5231107/125192755-656af180-e284-11eb-92f8-3776eca8044b.png)

![image](https://user-images.githubusercontent.com/5231107/125192747-5e43e380-e284-11eb-90e4-0710163a5750.png)

![image](https://user-images.githubusercontent.com/5231107/125192765-6c91ff80-e284-11eb-9368-12f32c8e8175.png)

**Comment by TEPPEIKNS** [comment]
@simongraham 
> The first and second images are able to be reproduced, but it seems that the third one is not enough.
> Is there any another reason ?

What do you think about this ?

**Comment by simongraham** [comment]
The results look fine to me. Macrophages were a real challenge in MoNuSAC because we were required to segment the cytoplasm as well as the nuclei. 

I think your results are good. We used cross validation and averaged the results over multiple runs to get the final result. This strategy was used by other competitors too and is commonly used to get a performance boost in challenges.

**Comment by vqdang** [comment]
Regarding PQ, the challenge has its own version of PQ. I remember it is a variant and may not be the same. Additionally, the PQ in this repository has a default IoU threshold of 0.5 (any less is set to FP), if you set it to 0.0 (exhaustive matching of everything), the results will likely go up.

**Comment by simongraham** [comment]
You can refer to [this repo](https://github.com/TIA-Lab/PanNuke-metrics) for an implementation of multi class PQ which was done in the same way as MoNuSAC

**Comment by TEPPEIKNS** [comment]
Thanks I got it. I'll try the metrics code for calculating PQ.

**Comment by TEPPEIKNS** [comment]
@simongraham @vqdang 
I tried to calculate the each class PQ value. The result is as below.
The monusac checkpoint can't segmentate "Macrophage", "Neutrophil". 
How did you make the multi fold dataset ? 

Train PQ
["Epithelial", "Lymphocyte", "Macrophage", "Neutrophil"] = [0.2795611797333212, 0.28338360815602187, 0.0, 0.0]
Test PQ
["Epithelial", "Lymphocyte", "Macrophage", "Neutrophil"] = [0.3003146014641786, 0.2530428906209276, 0.0, 0.0]

**Comment by simongraham** [comment]
Something seems wrong here, you shouldn't be getting 0 values for macrophage and neutrophil. In fact we got quite high PQ values for neutrophil. You should go over your evaluation code to make sure everything is correct.

**Comment by TEPPEIKNS** [comment]
@simongraham @vqdang
You said that you are able to detect neutrophils and macrophages, is this a case of **multifold**?
We evaluated the results using a single fold checkpoint that is provided from you in this repository, and the results are shown here.

**Comment by Lewislou** [comment]
> We were still able to detect neutrophils and macrophages with single fold. Have you looked at your results visually to make sure they line up with the stats? It seems from your previous visual results that in fact you are detecting neutrophils, which makes me suspect that there is something not quite right with the evaluation code you are using.

I notice that your model is trained with panuke pre-trained weights, I wonder if not using pre-trained weights or just using ImageNet pre-trained weights, what are the results for MoNuSac dataset? Because I recently trained the MoNuSac dataset using the pytorch hover-net codes, but get very pool results on  "Macrophage", and "Neutrophil" types as well.
