### ISSUE TITLE
--save_mask option for Tile Processing

### ISSUE THREAD

**Issue by sgudaparthi** [vqdang/hover_net#143]
Is there a way to save the instance mask separately (similar to --save_mask used in WSI processing) for Tile Processing?

**Comment by simongraham** [comment]
The instance map is saved [here](https://github.com/vqdang/hover_net/blob/master/infer/tile.py#L196) as a `.mat` file. You will need to specifically access the `inst_map` key when loading. If you wanted to save this as an image, then you can independently save `inst_map` as an image in the code as you wish. Make sure that your instance id's aren't effected by using specific data types such as uint8!
