### ISSUE TITLE
On the prediction problem of segmentation

### ISSUE THREAD

**Issue by kiven1213** [vqdang/hover_net#147]
Hi，@simongraham和@vqdang
I'm sorry to bother you again. Now I just want to do segmentation. After I successfully trained the segmentation model, I found that using the trained model to predict did not produce the predicted results. I would like to ask, what parameters need to be adjusted during the segmentation?
![image](https://user-images.githubusercontent.com/37852705/126422780-76efe029-cddd-40a0-9741-57b5690d3777.png)
![image](https://user-images.githubusercontent.com/37852705/126422826-2cec8a8f-cbb6-4fd4-8a44-768b2634eb56.png)
![image](https://user-images.githubusercontent.com/37852705/126422878-bfc6275e-bfe1-45c0-8186-acf914d97d36.png)

**Comment by simongraham** [comment]
Try setting the number of inference and post processing workers to 0 and rerun. You should hopefully get a more informative error message.
