### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by suke18** [vqdang/hover_net#148]
Dear developer, 

I recently started doing image analysis. I have some tiled images which are stored in the *.png format. I want to segment the nucleus from each tiled image by following the `https://github.com/vqdang/hover_net/blob/master/examples/usage.ipynb` example. I wonder what are the *.mat*, *.jason* files.  Why do we need these files plus the "Overlay" images? Do you know how can we generate these corresponding files given the tiled images? 

Best,
Timothy

**Comment by simongraham** [comment]
Hi,

To generate the output you will need to process your data with hover-net. All of the inference related information should be on the README.
