### ISSUE TITLE
About the PanNuke checkpoints

### ISSUE THREAD

**Issue by Kaiseem** [vqdang/hover_net#153]
Hello, 
it is known that the PanNuke have three dataset splits and there are three combination of those splits.
i wanna know if the chechpoints trained on the PanNuke in trained on the split 1?

**Comment by simongraham** [comment]
The trained with PanNuke on fold X and then fine-tuned on all of the data for the purpose of providing this checkpoint. I can not confirm which fold we used before fine-tuning I'm afraid.
