### ISSUE TITLE
No predictions for the 5th class of PanNuke

### ISSUE THREAD

**Issue by zeeshanalipanhwar** [vqdang/hover_net#154]
Hi, throughout the 100 training epochs for PanNuke, I am getting `valid-tp_dice_5` as `0`. After the inference, I do not get any `inst_type==5`. I do not understand why could this be happening. Can you suggest anything that I might be missing, anything that needs to be cross-checked? I have already made sure the input has all `5` types, and `nr_types=6`. Using `fast` model mode.
Following are the stats that are computed over the inference preds for `mode=type`:
```python
F1_d    | Acc_type  | F1_type_n   | F1_type_i  | F1_type_c | F1_type_d | F1_type_e
0.79896 | 0.70142   | 0.45735     | 0.53191    | 0.45735   | 0.21516   | 0
```

**Comment by zeeshanalipanhwar** [comment]
I just stumbled upon [this](https://github.com/vqdang/hover_net/blob/master/dataloader/train_loader.py#L100) line of code as follows:
```python
type_map[type_map == 5] = 1  # merge neoplastic and non-neoplastic
```
This could be the very reason. But, why is that merging being done?

**Comment by zeeshanalipanhwar** [comment]
That was the reason. Solved!

**Comment by FabianHoerst** [comment]
I also stumbled uppon this line. Was what the reason for this?
