### ISSUE TITLE
make inference on WSI will get a empty .json file

### ISSUE THREAD

**Issue by hitxiaoting** [vqdang/hover_net#158]
Hi @vqdang , I trained a hover-net model on our own dataset, it works well on tile mode. Thank you for your great work.
But when I make inferences on WSI files, the code runs well, and finally, outputs an empty json file, it looks like this: 

{"mag": 40, "nuc": {}}
It seems that the prediction result is not be saved. 

I try to debug line by line, you first create a cache to save the  WSI's pred_inst.npy and pred_map.npy. So, when dealing with each chunk (patch), the pred_inst.npy and pred_map.npy will be flushed on their corresponding coordinates. 

And I find that in wsi.py,  when **function def __get_raw_prediction(self, chunk_info_list, patch_info_list):**  call        
--> **proc_pool.apply_async(
                _assemble_and_flush,
                args=(wsi_pred_map_mmap_path, chunk_info, patch_output_list),
            )**
in  function  _**_assemble_and_flush()**_, it seems that the code did not re-write the result to the .npy file;  
<img width="787" alt="WeChat0fc957178904152d5c2357f1c6f19d0c" src="https://user-images.githubusercontent.com/13229444/130169119-c21670da-0709-41a8-b020-fea374682741.png">

I don't know if my problem is caused by this reason, does anyone has this trouble too? Could you please how to solve this, Thanks!

**Comment by vqdang** [comment]
Could you provide
- System information, is this local machine or cluster?
- The thumbnail of the WSI?
- Also, in case you havent deleted the cache folder, load up each the raw .npy and paste here the down-sampled version.
- Also please attach the log file.

**Comment by hitxiaoting** [comment]
> Could you provide
> 
>     * System information, is this local machine or cluster?
> 
>     * The thumbnail of the WSI?
> 
>     * Also, in case you havent deleted the cache folder, load up each the raw .npy and paste here the down-sampled version.
> 
>     * Also please attach the log file.

Sorry, I set a wrong out_ch, in " out_ch = 3 if self.method["model_args"]["nr_types"] is None else 4" , it should be corresponding with my nr_type. I changed it to be 5, then it can work well. 
Thank you so much, @vqdang
