### ISSUE TITLE
stats for classification error

### ISSUE THREAD

**Issue by Ghulam111** [vqdang/hover_net#16]
While running `compute_stats` for `type` classification the console produces no this error.
The ground_truth labels in ConSep dataset are in npy format , but the code is reading ground_truth as `.mat` files. ?
![image](https://user-images.githubusercontent.com/55826990/68478248-5918d080-0227-11ea-971d-ea612f618cdd.png)

**Comment by vqdang** [comment]
Hi @Ghulam111 

The calculation for classification statistics requires the info about each instance (centroid and type) in summarized form, which we saved as '.mat' file. You can obtain this via the following code, please change the path of `ann_dir` and `save_dir` according to your current folder. Afterward, you will need to the classification point to the `save_dir` as input for GT directory.

```
import numpy as np
import os
import glob
import scipy.io as sio
from misc.utils import get_inst_centroid, rm_n_mkdir
from metrics.stats_utils import remap_label

ann_dir = '../../../data/NUC_UHCW/CoNSeP/' # * directory contains .npy
filepath_list = glob.glob('%s/*.npy' % ann_dir)

save_dir = 'output/dump/' # directory to save summarized info about nuclei

rm_n_mkdir(save_dir)
for path in filepath_list:
    basename = os.path.basename(path).split('.')[0]

    true_map = np.load(path)
    true_inst = true_map[...,0]
    true_type = true_map[...,1]

    true_inst = remap_label(true_inst, by_size=True)
    true_inst_centroid = get_inst_centroid(true_inst)
    #### * Get class of each instance id, stored at index id-1
    # for ground truth instance blob
    true_id_list = list(np.unique(true_inst))[1:] # exclude background
    true_inst_type = np.full(len(true_id_list), -1, dtype=np.int32)
    for idx, inst_id in enumerate(true_id_list):
        inst_type = true_type[true_inst == inst_id]
        type_list, type_pixels = np.unique(inst_type, return_counts=True)
        inst_type = type_list[np.argmax(type_pixels)]
        if inst_type != 0: # there are artifact nuclei (background types)
            true_inst_type[idx] = inst_type

    sio.savemat('%s/%s.mat' % (save_dir, basename), 
                {
                'inst_type' :     true_inst_type[:, None], 
                'inst_centroid' : true_inst_centroid,
                })
```

**Comment by Ghulam111** [comment]
![image](https://user-images.githubusercontent.com/55826990/72201863-6d24bc80-347a-11ea-96eb-b9dab66711de.png)

i want to know whether the results for classification are of the same order as in the paper or is it :
1st one is f1 detection score ,
2nd is PQ 
3rd is for epithelial  f1 classification score
4rth is inflammatory
5th is spindle-shaped
6th is miscellaneous

**Comment by simongraham** [comment]
Hi @Ghulam111 ,

1) F1 detection score
2) Accuracy of nucleus class prediction (not reported in paper)
3) f1 score miscellaneous 
4) f1 score inflammatory
5) f1 score epithelial
6) f1 score  spindle

For getting the PQ score, this is a binary measure and therefore run `run_nuclei_inst_stat()`
