### ISSUE TITLE
About validation strategy

### ISSUE THREAD

**Issue by caprioGirl** [vqdang/hover_net#163]
> Hi!
> 
>     1. We don't use ensemble dice in the paper. We mention it, but don't use it due to the points we raise in the paper. The dice we report is standard dice score.
> 
>     2. You can divide your data as you wish, but for the paper we used the test as validation. This is why we had the extra generalisation experiment in Table 4. We used 50-50 because this a sufficient number of epochs to ensure that training had converged for each stage.

Does the same validation strategy hold true for the Kumar, cpm and other datasets? @simongraham

_Originally posted by @caprioGirl in https://github.com/vqdang/hover_net/issues/160#issuecomment-908688300_

**Comment by vqdang** [comment]
To be concrete, DICE2 was only reported in Table 1. It is normal dice in other tables.
![image](https://user-images.githubusercontent.com/24943262/131520699-9126cf3e-b846-4035-a982-5fb347144db6.png)

**Comment by vqdang** [comment]
I close this issue as it has already been answered in another one. Please reopening #160 rather than making another issue with the same questions.

**Comment by caprioGirl** [comment]
sorry, i guess i wasn't clear enough, i am asking about point2 not the dice one but the dataset split @vqdang
