### ISSUE TITLE
predict

### ISSUE THREAD

**Issue by Dogdog00** [vqdang/hover_net#165]
I have successfully completed the training,and want to make predictions. Then  i run the instructions first: 1. ` pythoninfler.py-GPU =' 0' `The results are shown in the following figure
![4fe0ee39d6081a3a289540402154a36](https://user-images.githubusercontent.com/64968282/132941593-ef573370-6602-4562-86ad-17334f8ac6d5.png)
2、`python process.py`
![aa81f10d3444563fb4c168a0c7c619c](https://user-images.githubusercontent.com/64968282/132941624-c7858c6f-26bb-4d98-a3b7-ab69e48883d3.png)
But doe not produce any segmentation results only a file：
![image](https://user-images.githubusercontent.com/64968282/132941678-9f68408b-6cd2-4ab7-8ecf-5bc42800e38b.png)

**Comment by simongraham** [comment]
Hi @Dogdog00 ,

Please can you send the entire command that you used for process the data? I suspect something is wrong there. Have a look at the README for detailed instuctions on how to run. Also take a look at the example `run_tile.sh` and `run_wsi.sh` scripts.

**Comment by Dogdog00** [comment]
Hi,i have solved successly  the problem.Thanks
