### ISSUE TITLE
Performance on Saltz Nuclei Dataset 

### ISSUE THREAD

**Issue by arp95** [vqdang/hover_net#170]
Hi,

Was the performance of each of the three pretrained models, namely, Pannuke, Consep and Monusac tested on the Saltz Dataset over here? (https://arxiv.org/pdf/2002.07913.pdf)
Thanks.

**Comment by simongraham** [comment]
Hi @arp95 - thanks for reaching out! We have not tested the performance on that dataset, but you are more than welcome to try it out :)
