### ISSUE TITLE
Overlay 

### ISSUE THREAD

**Issue by Dogdog00** [vqdang/hover_net#176]
Hi，I'm sorry to bother you again about changing the color of Overlay when I was training my datasets under the TensorFlow version.
![image](https://user-images.githubusercontent.com/64968282/140631862-ec7cfae5-2645-48d5-b815-d01816523fc7.png)

**Comment by simongraham** [comment]
Hi - can you be more specific with your question please?

**Comment by Dogdog00** [comment]
> Hi - can you be more specific with your question please?



> Hi - can you be more specific with your question please?

I mean, how to change the overlay colors under the TensorFlow version. Just like this file, 'type_ info .json' under the PyTorch version.
![8bba1fb0cc7d92c1fd0b82471d426f1](https://user-images.githubusercontent.com/64968282/140851902-4913155d-2df8-46ba-8c72-60087a82acfc.jpg)

**Comment by Dogdog00** [comment]
> Hi - can you be more specific with your question please?

我就是想问，用自己的数据集训练，最后overlay勾画的颜色我怎么改变？这个代码我没找到。我看到pytorch 版本中有type_info.json是直接可以改各个类代表的细胞，以及颜色的。谢谢你🙏

**Comment by simongraham** [comment]
You will need to modify [this function](https://github.com/vqdang/hover_net/blob/tensorflow-final/src/misc/viz_utils.py#L13) so that it returns preset RGB colours for each type, rather than random colours.

**Comment by simongraham** [comment]
Closing the issue as the above should solve things.
