### ISSUE TITLE
compute_stats.py is taking way too long

### ISSUE THREAD

**Issue by taimurhassan** [vqdang/hover_net#177]
Hi,

Thank you for the great contribution. I am using your 'compute_stats.py' to compute metrics on CRCHisto. However, it takes way too long to compute the results. I traced the code and found 'pair_coordinates(...)' in 'stats_utils.py' is taking much of the time. Can you please tell me what is the issue?

I am feeding 'inst_centroid' of size (9093x2) and 'inst_type' of size (9093x1).

Thanks,
Taimur

**Comment by simongraham** [comment]
Hi @taimurhassan ,

Can you provide us with more info please? In particular, exactly how long is it taking?

**Comment by taimurhassan** [comment]
Hi @simongraham 

Thank you so much for your time. The issue is solved now. Basically I was feeding a single consolidated mat file containing the predictions and true labels from all the scans within the dataset (i.e., ~9k samples) and since Kuhn-Munkres algorithm has a cubic time complexity, it was taking a lot of time. But when I generated a separate mat file for each scan, the time reduced drastically.
