### ISSUE TITLE
Use PanNuke trained model for retrain

### ISSUE THREAD

**Issue by Tato14** [vqdang/hover_net#178]
Thanks for the great repo!

I am trying to retrain Pannuke model `hovernet_fast_pannuke_type_tf2pytorch.tar` on a new dataset in order to see if I can improve metrics compared with the `ImageNet-ResNet50-Preact_pytorch.tar`.

However, when I replace it in the `opt.py` and `run_Train.py` I got a dimension error:

```
Detect #GPUS: 5
Using manual seed: 10
Dataset train: 766
Dataset valid: 264
Model `net` pretrained path: /mnt/isilon/Breast_HMAR/HoverNet/hovernet_fast_pannuke_type_tf2pytorch.tar
Traceback (most recent call last):
  File "run_train.py", line 305, in <module>
    trainer.run()
  File "run_train.py", line 289, in run
    phase_info, engine_opt, save_path, prev_log_dir=prev_save_path
  File "run_train.py", line 212, in run_once
    load_feedback = net_desc.load_state_dict(net_state_dict, strict=False)
  File "/home/jgibert/anaconda3/envs/hovernet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for HoVerNet:
	size mismatch for decoder.tp.u0.conv.weight: copying a param with shape torch.Size([6, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([8, 64, 1, 1]).
	size mismatch for decoder.tp.u0.conv.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([8]).
```

I understand that this is because PanNuke has 6 classes and the dataset I am using has 8. How should I change this to reuse the model?

**Comment by vqdang** [comment]
Setting this 
https://github.com/vqdang/hover_net/blob/be8ae2d621bfbddefd97591ef9df39252e108df9/config.py#L27
should be enough. Or you can hard-code it here
https://github.com/vqdang/hover_net/blob/61ffeca6d22bba8aae0727523192150175be8b18/models/hovernet/opt.py#L23

**Comment by Tato14** [comment]
Uhm... Sorry, I think I did not explained myself properly.

The idea here would be to use `hovernet_fast_pannuke_type_tf2pytorch.tar` in this line:
https://github.com/vqdang/hover_net/blob/61ffeca6d22bba8aae0727523192150175be8b18/models/hovernet/opt.py#L55

instead of `ImageNet-ResNet50-Preact_pytorch.tar`.

But, as mentioned before, I got an error dimension. My question was how to reuse Pannuke model the same way as Imagenet model.

Thanks!

**Comment by vqdang** [comment]
You can try the following to pop out the keys above and save as another checkpoint for pre-trained
```
import torch
state_dict = torch.load(PATH)
state_dict.pop('decoder.tp.u0.conv.weight')
state_dict.pop('decoder.tp.u0.conv.bias')
torch.save(state_dict, PATH)
```

**Comment by Tato14** [comment]
@vqdang 
It worked! Thanks for the feedback!
For the sake of completeness, in order to remove the two problematic layers you should:
```
import torch
state_dict = torch.load(PATH)
state_dict.get('desc').pop('decoder.tp.u0.conv.weight')
state_dict.get('desc').pop('decoder.tp.u0.conv.bias')
torch.save(state_dict, NEW_PATH)
```
