### ISSUE TITLE
extarce data

### ISSUE THREAD

**Issue by JiaYuHang** [vqdang/hover_net#182]
How to extrace data?How to perform this step?
![image](https://user-images.githubusercontent.com/58177651/147531245-76307a67-f52b-4bc3-8968-a345e089caac.png)

**Comment by simongraham** [comment]
You simply need to download the data, make a directory called `exp_output` and place the downloaded directories at that location. For a quicker response, you may want to use the [forum](https://grand-challenge.org/forums/forum/conic-challenge-613/) on the grand challenge website.
