### ISSUE TITLE
Asking for json file when running infer.py from tensorflow-final branch

### ISSUE THREAD

**Issue by lucas-sancere** [vqdang/hover_net#186]
Hi, 

  First of all thank you for your excellent work. 
  
  I faced some issues when running infer.py:

``` bash  
(hovernet_tensorflow) [lsancere@cheops41101 src]$ python infer.py --gpu='gpu_id'
 
-----Auto Selecting Checkpoint Basing On "valid_dice" Through ">" Comparison
Traceback (most recent call last):
  File "infer.py", line 183, in <module>
    inferer.run()    
  File "infer.py", line 137, in run
    model_path, stat = get_best_chkpts(self.save_dir, self.inf_auto_metric, self.inf_auto_comparator)
  File "infer.py", line 40, in get_best_chkpts
    with open(stat_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/projects/ag-bozek/lucas/Data_Hovernet/stats.json'
```

  It is asking for a json file whereas I just want to predict from your trained network and there is not such a file with the provided weights.
  
  I also used your tensorflow inference model trained with Pannuk and Monsec datasets and it worked well (thank you for that). But I would like to see the prediction with a training on Kumar, CoNSeP, CPM-17. I cannot use these weights on your last inference model because of the different convolution used and the fact I am only looking for instance segmentation.

  In case, here is my changes of config file: 
  
  ```Python3
  
 l23
      self.type_classification = False # whether to predict the nuclear type
 l84-1107
        exp_id = 'v1.0/'
        model_id = '%s' % self.model_type
        self.model_name = '%s/%s' % (exp_id, model_id)
        # loading chkpts in tensorflow, the path must not contain extra '/'
        self.log_path = '/projects/ag-bozek/lucas/Data_Hovernet/logs'
        self.save_dir = '/projects/ag-bozek/lucas/Data_Hovernet' # log file destination

        #### Info for running inference
        self.inf_auto_find_chkpt = True 
        # path to checkpoints will be used for inference, replace accordingly
        self.inf_model_path = self.save_dir + 'PreTrained_Weights/hover_seg_CoNSeP'

        # output will have channel ordering as [Nuclei Type][Nuclei Pixels][Additional]
        # where [Nuclei Type] will be used for getting the type of each instance
        # while [Nuclei Pixels][Additional] will be used for extracting instances

        self.inf_imgs_ext = '.png'
        self.inf_data_dir = '/projects/ag-bozek/lucas/Data_General/Predictions/IHC_HE_ScieboData1/tiles_png/'
        self.inf_output_dir = '/projects/ag-bozek/lucas/Data_General/Predictions/IHC_HE_ScieboData1/Outputs/'
```

 I probably missed something...  Hope you can help!
 
 Thank you very much,

**Comment by simongraham** [comment]
You need to set `self.inf_auto_find_chkpt` to  `False` - otherwise it will look for the best checkpoint from the provided log path. If you set to `False`, then it will instead load the checkpoint from `self.inf_model_path`.

**Comment by vqdang** [comment]
A warning here that we no longer support the tensorflow version for more than a year now. You can convert your tf checkpoint to pytorch and use the pytorch version.

**Comment by lucas-sancere** [comment]
Hi, thank you for your 2 answers!
