### ISSUE TITLE
train baseline for conic challenge 

### ISSUE THREAD

**Issue by Dorsa-Ziaei** [vqdang/hover_net#187]
Hi, Im trying to train the hovernet model from scratch on lizard dataset, patches of size 256x256, as a baseline for CoNIC challenge, without changing any hyperparameter, the same environment , here is a screenshot of my training result (from 01 folder, phase 2):

[32mtrain-loss_tp_bce [0m : 0.24518
[32mtrain-loss_tp_dice[0m : 2.02948
[32mtrain-loss_np_bce [0m : 0.14096
[32mtrain-loss_np_dice[0m : 0.22427
[32mtrain-loss_hv_mse [0m : 0.02250
[32mtrain-loss_hv_msge[0m : 0.33003
[32mtrain-overall_loss[0m : 2.99242
[32mtrain-lr-net      [0m : 0.00001

[32minfer-valid-np_acc   [0m : 0.95440
[32minfer-valid-np_dice  [0m : 0.84733
[32minfer-valid-tp_dice_0[0m : 0.97061
[32minfer-valid-tp_dice_1[0m : 0.31560
[32minfer-valid-tp_dice_2[0m : 0.81184
[32minfer-valid-tp_dice_3[0m : 0.77906
[32minfer-valid-tp_dice_4[0m : 0.57733
[32minfer-valid-tp_dice_5[0m : 0.42900
[32minfer-valid-tp_dice_6[0m : 0.71767
[32minfer-valid-hv_mse   [0m : 0.03839

I tried to infer the model using inference script of the conic challenge, which leads to "zero" predictions, and when using "run_infer.py" of hovernet repo, seems that the tile script doesn't work, below is the script:
(can I use the tile mode to infer on 256x256 patches?) 

#!/bin/bash

#SBATCH --job-name=conicTile
#SBATCH --error=./error/%J.err 
#SBATCH --output=./output/%J.out
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu

source ~/anaconda3/etc/profile.d/conda.sh
conda activate CoNIC

python /CoNIC/hover_net/run_infer.py \
--gpu='1' \
--nr_types=7 \
--type_info_path=type_info.json \
--batch_size=6 \
--model_mode=fast \
--model_path=/CoNIC/hover_net/exp_output/local/models/baseline/00/model/01/net_epoch=50.tar \
--nr_inference_workers=8 \
--nr_post_proc_workers=16 \
tile \
--input_dir=/CoNIC/hover_net/exp_output/local/baseline/imgs/ \
--output_dir=/CoNIC/hover_net/exp_output/local/baseline/preds/ \
--mem_usage=0.1 \
--draw_dot \
--save_qupath

Im got the error "to check the usage of run_infer options and commands"
Im asking for any hints regarding inferencing the model.

**Comment by simongraham** [comment]
Hi,

It seems that you are using the `master` branch for training. Can you please confirm this? We do not recommend using the CoNIC baseline notebook unless you train using the `conic` branch of this repository.  In fact, the network is slightly different in the `conic` branch (we used PyTorch encoder and padded convolution in the decoder). However, if you chose to train using the `master` branch, then you should also be able to process using this branch too.

The good news is that you have completed the training. 

Can you dump out the entire error that you get in the terminal and we can better diagnose the problem.

**Comment by Dorsa-Ziaei** [comment]
Im using "conic" branch for training, and I tried run_infer from master branch, didn't notice the encoder and and padded convolution in decoder are different in master and conic hovernet models.
I tried the challenge inference script as well, Im getting all zero predictions. 
This is the tile inference print out in error file:


Usage:
  run_infer.py [options] [--help] <command> [<args>...]
  run_infer.py --version
  run_infer.py (-h | --help)
Options:
  -h --help                   Show this string.
  --version                   Show version.
  --gpu=<id>                  GPU list. [default: 0]
  --nr_types=<n>              Number of nuclei types to predict. [default: 0]
  --type_info_path=<path>     Path to a json define mapping between type id, type name, 
                              and expected overlaid color. [default: '']
  --model_path=<path>         Path to saved checkpoint.
  --model_mode=<mode>         Original HoVer-Net or the reduced version used PanNuke and MoNuSAC, 
                              'original' or 'fast'. [default: fast]
  --nr_inference_workers=<n>  Number of workers during inference. [default: 8]
  --nr_post_proc_workers=<n>  Number of workers during post-processing. [default: 16]
  --batch_size=<n>            Batch size per 1 GPU. [default: 32]
Two command mode are `tile` and `wsi` to enter corresponding inference mode
    tile  run the inference on tile
    wsi   run the inference on wsi
Use `run_infer.py <command> --help` to show their options and usage.

**Comment by vqdang** [comment]
You input the command incorrectly, check here for template script. 
https://github.com/vqdang/hover_net/blob/master/run_tile.sh

On the matter of the conic, unless you know exactly what you and the are doing, we advise against using the `master` branch inference (pytorch) because you need to understand how to modify the network definition files. For new python user, this would not be easy.

Hence, you should use the one that is already in here https://github.com/TissueImageAnalytics/CoNIC . Additionally, to get the weights correctly from the checkpoint, doing as followings:
```python

import torch

# the checkpoint from training also containing the optimizer states
# which are not used in the inference code, we retrieve only the model weights

checkpoint = torch.load(CHECKPOINT_PATH)['desc']
checkpoint = convert_pytorch_checkpoint(checkpoint)  # to turn from Multiple GPU Mode to Single GPU Mode
torch.save(checkpoint, "PATH")

```

The function `convert_pytorch_checkpoint` is here https://github.com/vqdang/hover_net/blob/61ffeca6d22bba8aae0727523192150175be8b18/run_utils/utils.py#L15.

```

Other than that matter, please detail exactly what do you mean by

> I tried the challenge inference script as well, Im getting all zero predictions.

- Describe how did you run the inference code, command line and run directory specific
- Describe what did you receive on the terminal

**Comment by Dorsa-Ziaei** [comment]
The lines for correctly getting the weights plus the single GPU conversion, was the solution.
For inferencing the model, I was trying to use conic inference script from the notebook folder of https://github.com/TissueImageAnalytics/CoNIC. 
There was error for mismatch of the parameters, i was trying to fix it with setting the "strict" flag, and I was getting all zeros in prediction.
I just ran the inference and compute_stats and I could reproduce the metrics. Thank you.

**Comment by vqdang** [comment]
Great, I will close the issue.
