### ISSUE TITLE
Nuclei not found

### ISSUE THREAD

**Issue by JMBokhorst** [vqdang/hover_net#188]
Hi all, 

I was processing a lot of cases, and found that for this cohort a lot of nuclei are not found. In other cohorts it is doing a very good job, so I'm a bit surprised about this result and wondering what is going on. To figure this out I was wondering if you have any ideas? Maybe if possible, we could setup a short meeting to discuss? 

Below a screenshot of one of the results: 

![Screenshot 2022-01-24 at 11 16 03](https://user-images.githubusercontent.com/21331645/150764289-0c940862-e6f8-4f0a-ac83-8d50a9a2f44a.png)

**Comment by vqdang** [comment]
Can you provide us the RGB of this sample? It can be because the code did not pick up correct magnification.

**Comment by JMBokhorst** [comment]
Would you like to have an RGB patch of the entire slide or just a small part of the slide? Would you like me to extract an patch of 0.24um/px or a different scale?

**Comment by JMBokhorst** [comment]
I also just checked the spacial resolution of the image, it has a resolution of 0.24. I do believe the resolution was found correctly (if I place a breakpoint during loading, I see the correct information).

**Comment by simongraham** [comment]
Hi @JMBokhorst 

Can you clarify whether you can reproduce this error? I.e if you run it again on this slide, does the same thing happen? Also, can you provide us with the exact command that you used to produce the results. Once you have again processed the slide, we can have a better idea on the best plan of action.

**Comment by JMBokhorst** [comment]
Hi, 

Yes, I have tried to run the algorithm again on the same slide (or just a small part with a mask to speed the process up). The result is identical to the image I pasted above. 

The command I use is this: 

```
python3 /home/user/source/hover_net/run_infer.py \
    --gpu="0,1" \
    --nr_types=6 \
    --type_info_path=/home/user/source/hover_net/type_info.json \
    --batch_size=32 \
    --model_mode=fast \
    --model_path=/home/user/source/hover/hovernet_fast_pannuke_type_tf2pytorch.tar \
    --nr_inference_workers=8 \
    --nr_post_proc_workers=8 \
    wsi \
    --input_dir=/home/user/input_image/*.${extension} \
    --output_dir=/home/user/result_image \
    --input_mask_dir=/home/user/input_mask \
    --proc_mag=20 \
    --save_mask

```

**Comment by JMBokhorst** [comment]
I think I have found the issue. For some reason the image channels are being flipped (from RGB to BGR in the image). 

I will try again with the correct image (and pretty sure it will solve the issue :) ) I will let you guys know, thanks for the quick response!

**Comment by simongraham** [comment]
Hi @JMBokhorst 

Interesting that it is using BGR. Is it only for that image? Also, we recommend processing at 40x as this is what we trained on.
