### ISSUE TITLE
Issue running code in Kumar dataset

### ISSUE THREAD

**Issue by JinghanWang041315** [vqdang/hover_net#19]
Hi，Excuse me! Thank you so much for your excellent code and paper :‘HoVer-Net’.

I want to train HoVer-Net using Kumar，but i have some problems:

1.  I have changed the Monseg dataset(Kumar) . xml file into  .npy file by [https://github.com/vqdang/hover_net/blob/master/src/misc/proc_kumar_ann.py].For a start, I want use https://github.com/vqdang/hover_net/blob/master/src/extract_patches.py to generate training and validation patches.How to choose 'extract_type'?I have used “extract_type = 'mirror' "generate training patches?How to generate validation patches?

2. When training , [https://github.com/vqdang/hover_net/blob/master/src/train.py],How to set  self.train_dir = ['../../../CoNSeP/train/%s/'  % data_code_dict[self.model_type]]
        self.valid_dir = ['../../../CoNSeP/valid/%s/' % data_code_dict[self.model_type]] in config.py .
 
![image](https://user-images.githubusercontent.com/53046658/70215648-e7299d80-1778-11ea-8dea-545ed0b208a4.png)

Sorry to bother you, you can reply in your free time. Thank you.

**Comment by JinghanWang041315** [comment]
OKOK ,I have training in the ConSeg. I  closed.
![image](https://user-images.githubusercontent.com/53046658/70224150-b866f380-1787-11ea-93d4-7ef62007eba2.png)

**Comment by simongraham** [comment]
Hi @JinghanWang041315 ,

When using HoVer-Net, use mirror as the extract type. This will pad the image before extracting the patches. We use this when the output size of the network is smaller than the input size and we set the stride of patch extraction to the size of the output of the network. Therefore, for HoVer-Net we use 80x80 stride. 

When extracting patches using `extract_patches.py` , you need to do it separately for train and validation images by accordingly modifying lines 36, 37 and 39. 

Then, when running the code, you need to make sure that lines 61 and 62 in `config.py` point to the right directories where the patches were extracted. I.e it should match with line 39 in `extract_patches.py`.

I hope this clears up any confusion, but besides this it seems that you have got the code working above, so I will close the issue.
