### ISSUE TITLE
pannuke metric

### ISSUE THREAD

**Issue by Afsaneh299** [vqdang/hover_net#192]
Hi
I run this script for pannuke dataset
python run_infer.py --nr_types=6 --type_info_path='type_info.json' --batch_size=16 --model_mode='fast' --model_path='/logs/net_epoch=19.tar' --nr_inference_workers=4 --nr_post_proc_workers=4  tile --input_dir='/Fold 3/images/' --output_dir='/outputs/' --draw_dot --save_qupath 
it created outputs and  pannuke metric need pred mask address 
But tile script of output don't have masks.npy 
Please help me

**Comment by simongraham** [comment]
Refer [here](https://github.com/TissueImageAnalytics/PanNuke-metrics) for PanNuke metrics. We didn't use PanNuke in the original publication.
