### ISSUE TITLE
'HoVerNetExt' object has no attribute 'module'

### ISSUE THREAD

**Issue by EdwardZhao1991** [vqdang/hover_net#193]
Dear all,

Thanks for sharing the great work.

I want to train the model on one GPU and comment this line
> \# net_desc = DataParallel(net_desc)

https://github.com/vqdang/hover_net/blob/9b21c8620313b2cd2458611b244e4a4ef4ee8865/run_train.py#L218-L220

However, I got this error
> AttributeError: 'HoVerNetExt' object has no attribute 'module'

How can I fix this error?

**Comment by EdwardZhao1991** [comment]
BTW, to make the code fit on one GPU(11G), are there other things that I need to modify?

**Comment by vqdang** [comment]
`DataParallel` works even when there is only 1 GPU. Put it back and lower your batch size.
