### ISSUE TITLE
Some problems with running baseline.ipynb

### ISSUE THREAD

**Issue by JiaYuHang** [vqdang/hover_net#197]
When I run the file with the trained weighted,i get the following error.
 
![image](https://user-images.githubusercontent.com/58177651/155830874-7fdcbc67-e18e-404e-a24b-4d2607050fea.png)
I think the problem comes from loading weights.As shown below:
![image](https://user-images.githubusercontent.com/58177651/155830935-5db680a8-bd46-44d8-be68-b8df7c0f2507.png)
I can't solve this problem and hope to get some help.Very thankful!

**Comment by vqdang** [comment]
https://github.com/vqdang/hover_net/issues/187#issuecomment-1019243052
