### ISSUE TITLE
Compute stats error

### ISSUE THREAD

**Issue by gemitrick** [vqdang/hover_net#200]
Hello, good work! I met a problem  when I was trying to compute the metrics for classification on CoNSeP  by compute_stats.py. I got a output as [0.00046 0 0 0 0 0]. It seems that in the .mat files the array for "inst_type" were empty. 
My command for inference and metric computation:
python run_infer.py --gpu='0' --nr_types=5 --type_info_path=type_info.json --model_mode=original --model_path=hovernet_original_consep_type_tf2pytorch.tar tile --input_dir=dataset/CoNSeP/Test/Images/ --output_dir=logs/consep/pred_type/ --draw_dot

 python compute_stats.py --mode=type --pred_dir=logs/consep/pred_type/mat/ --true_dir=dataset/CoNSeP/Test/Labels/
What should I do or what should I check

**Comment by gemitrick** [comment]
@vqdang

**Comment by gemitrick** [comment]
@simongraham

**Comment by xiaoshuomin** [comment]
@gemitrick I met the same problem. Please tell me how to solve the problem. Thanks！
