### ISSUE TITLE
Google Colab usage problem

### ISSUE THREAD

**Issue by Ghulam111** [vqdang/hover_net#21]
![image](https://user-images.githubusercontent.com/55826990/74080339-e5c06e00-4a64-11ea-9cfb-3c2d1e5fef74.png)

i run into this error while trying to run this project on google colab.any idea to resolve this
```
tensorflow-gpu==1.12
tensorpack==0.9.0.1
python 3.6.9
CUDA 10.0.130
```

**Comment by simongraham** [comment]
We have not tested our code with google colob, but you should be able to get it to work. The error looks like it is trying to use CUDA 9.0, when you say you are using version 10.0.130. This is not specific to our code, but is to do with your own setup and therefore we are closing the issue.
