### ISSUE TITLE
Pretrained weights damaged. Winrar cant extract anything

### ISSUE THREAD

**Issue by YUSRA100** [vqdang/hover_net#212]
Downloaded from the link given but it says its damaged. I have found [somewhere](https://github.com/simongraham/hovernet_inference) inference .[npz](https://drive.google.com/drive/folders/1NwnF71vuhMB3QeV9R5CFDyYFBGaexf_f) files. Could they be used?

**Comment by simongraham** [comment]
Hi - these weights are not damaged. Simply point the code to the zipped file and the code will do it's job. You should not try and extract.

**Comment by YUSRA100** [comment]
> Hi - these weights are not damaged. Simply point the code to the zipped file and the code will do it's job. You should not try and extract.
Thankyou for the prompt response. Did as you said, got this runtime error : 

![error](https://user-images.githubusercontent.com/14943888/170679773-39dcb6aa-777e-4e2b-882c-1f7fe22f9d72.png)

**Comment by eshasadia** [comment]
Hi, I am also facing damaged pretrained weights issue. Have you resolved this problem or it still persists?

**Comment by YUSRA100** [comment]
> Hi, I am also facing damaged pretrained weights issue. Have you resolved this problem or it still persists?

Yes just like he mentioned above, you dont need to unzip them. Pass as an argument as is. check the image i have attached above.

**Comment by eshasadia** [comment]
Yes, I did the same but It's giving the same runtime error of missing keys. Can you please let me know how you managed to resolve that issue?

**Comment by eshasadia** [comment]
Like, Have you used the .npz file instead of .tar weights available in the original repo?

**Comment by YUSRA100** [comment]
> i had the error but didnt dig deeper into it. My main goal was the repo Nuc2Vec which has one component of hovernet so i skipped it.

**Comment by vqdang** [comment]
There are 2 HoVerNet repositories, the one by Simon was for inference using **Tensorflow** checkpoints. This repository is **solely for Pytorch now**. Any pretrained weights that are included [here](https://github.com/vqdang/hover_net#inference) should be used only you know well what you are doing.

Any checkpoints obtained by training the model using the code in this repos can be loaded and accessed via brief template here https://github.com/vqdang/hover_net/issues/213#issuecomment-1141128669 . Please make sure that you instantiate the model with correct number of types.
