### ISSUE TITLE
Horizontal and Vertical Maps Visualization

### ISSUE THREAD

**Issue by lauraacostac** [vqdang/hover_net#213]
We have already obtained the predictions for our trained models, and now we want to visualize the output for each one of the net branches. We are particularly interested in the horizontal and vertical maps, but when trying to execute run_train.py --view = 'train', there's no output because the dictionary that allegedly has the targets it appears to be empty. This is how the mentioned dictionary looks on the opt.py file:

![image](https://user-images.githubusercontent.com/98632551/170913045-f303c5ad-3dee-4c8c-b172-933a9c596685.png)

We would appreciate if you could give us any guide to succesfully visualize what we need. Thank you!

**Comment by juanitapuentes** [comment]
It happens the same to me! SOS

**Comment by vqdang** [comment]
The `train.py` view mode is kind of ancient now, and it is for generating training targets rather than the predictions. The easiest way is to perform the inference and grab what you need. Here is a simple template

```python
from model.hovernet.net_desc import HoVerNet
import torch
import matplotlib.pyplot as plt
import cv2

checkpoints = torch.load(PATH)
model = HoVerNet()
model.load_state_dict(checkpoints["desc"])

image = cv2.imread(IMAGE_PATH)
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# ---
model = model.to("cuda")

image = torch.from_numpy(image)[None]  # fake NxHxWxC
image = image.to("cuda")
image = image.permute(0, 3, 1, 2) # NHWC -> NCHW

predictions = model(image)

# --- plotting whatever you want with plt
```

**Comment by juanitapuentes** [comment]
Thank you! When I tried to implement that template the following error appear:

RuntimeError: Error(s) in loading state_dict for HoVerNet:
	Missing key(s) in state_dict:  "conv0./.weight", "conv0.bn.weight", "conv0.bn.bias", "conv0.bn.running_mean", "conv0.bn.running_var", "d0.units.0.conv1.weight", "d0.units.0.conv1/bn.weight", "d0.units.0.conv1/bn.bias", "d0.units.0.conv1/bn.running_mean", "d0.units.0.conv1/bn.running_var", ...

Do you know how to solve it?

**Comment by vqdang** [comment]
Check the updated

**Comment by juanitapuentes** [comment]
I already changed what you told me, but I still having the same error:

<img width="1099" alt="Screen Shot 2022-05-30 at 10 12 44 AM" src="https://user-images.githubusercontent.com/106543608/171021008-f8fb7268-ee92-4be7-9b5c-ebc9675172c5.png">

The code I used is the following:
from turtle import pd
from models.hovernet.net_desc import HoVerNet
from run_utils.utils import convert_pytorch_checkpoint
import torch
import matplotlib.pyplot as plt
import cv2
import pdb

checkpoints = torch.load('./dataset/checkpoints/checkpoints_ResNet50_32_0.001_Adam_50/00/net_epoch=50.tar')
checkpoints = convert_pytorch_checkpoint(checkpoints["desc"])
pdb.set_trace()
model = HoVerNet()
model.load_state_dict(checkpoints)

image = cv2.imread('./dataset/training_data/consep/consep/train/540x540_164x164/train_1_000.npy')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# ---
model = model.to("cuda")

image = torch.from_numpy(image)[None]  # fake NxHxWxC
image = image.to("cuda")
image = image.permute(0, 3, 1, 2) # NHWC -> NCHW

predictions = model(image)

# --- plotting whatever you want with plt

**Comment by lauraacostac** [comment]
I already checked other issues related to mismatching of keys. I understand one way to solve this is by setting --nr_types to 0, but doesn't that mean we are not able to perform nuclei classification? I'm really confused in why this is not working, would appreciate help on this.

**Comment by vqdang** [comment]
@juanitapuentes 
It spits out that error because you **trained** your network **with type arguments**. You should edit `model = HoVerNet(nr_type=A_NUMBER)` approriately.

**Comment by vqdang** [comment]
@lauraacostac Please double check your training recipe, if you trained the model **with type arguments**, the variables should already be there.

**Comment by lauraacostac** [comment]
We were able to index the result dictionary in which the maps (hv) are stored. However, the shape of the corresponding matrix is not compatible with matplotlib, given that it is (2, 80, 80, 2). I already tried to do hv.squeeze(), but because none of the values is 3 or 4, the output is not taking an image form. Do you know how can I visualize it? Thank you!

**Comment by simongraham** [comment]
Are you using the same image input dimensions that we use? For example, if using `fast` mode, you should use an input size of 256x256. Otherwise you may get errors like you are getting above due to valid convolution used in the decoder.
