### ISSUE TITLE
Overlay Output and Type Map

### ISSUE THREAD

**Issue by Ahbli101** [vqdang/hover_net#214]
I trained the same model that you propose in the repository. However, the prediction overlays have different colors than the ground truth (Figure). This is normal? (I ask because the metrics are good) I would also like to know how I can obtain the type maps through the results obtained when running infer.py since the function returns:

'bbox': bounding box coordinates for each nucleus
'centroid': centroid coordinates for each nucleus
'contour': contour coordinates for each nucleus
'type_prob': per class probabilities for each nucleus (default configuration doesn't output this)
'type': prediction of category for each nucleus
Image tiles output a mat file, with keys:
'raw': raw output of network (default configuration doesn't output this)
'inst_map': instance map containing values from 0 to N, where N is the number of nuclei
'inst_type': list of length N containing predictions for each nucleus
Image tiles output a png overlay of nuclear boundaries on top of original RGB image

<img width="315" alt="Screen Shot 2022-05-30 at 9 40 18 AM" src="https://user-images.githubusercontent.com/106543608/171019369-8036a964-6cd4-4c60-a5dc-551d7b8c159e.png">

<img width="312" alt="Screen Shot 2022-05-30 at 9 40 48 AM" src="https://user-images.githubusercontent.com/106543608/171020435-45e95d73-0c17-44d8-9288-8ec474f4e154.png">

**Comment by simongraham** [comment]
You can specify the colour of the overlay that you wish to see in [this file](https://github.com/vqdang/hover_net/blob/master/type_info.json).

**Comment by Ahbli101** [comment]
Thank you!!! And how could I get the type map prediction from the output .mat files while running tile.sh?
