### ISSUE TITLE
Output per-class probabilities for each nucleus (type_prob)

### ISSUE THREAD

**Issue by Luke3D** [vqdang/hover_net#223]
Dear authors, 

I would like to output the **per-class probabilities** for each nucleus. After running the inference on a tile, the ['type_prob'] field in my output json contains a scalar (e.g. 0.999999996742671), which I assume it is the probability of the predicted class (i.e. the max probability of the softmax across all classes) for that nucleus.

How do I run the inference to output the per class probabilities for each nucleus? (In the Readme it says that "the default configuration doesn't output this"; I am not clear how do I set a different configuration).
Regards,
Luca

**Comment by vqdang** [comment]
The class probability of each nucleus in the `['type_prob']` is not the pixel-wise softmax output. It is the proportion of that nucleus pixels belonging to the assigned type.

https://github.com/vqdang/hover_net/blob/842964dc5d26ffe196d236d16fad16643a103850/models/hovernet/post_proc.py#L179

By default, the inference will run a model w/o typing, so set the flag 
https://github.com/vqdang/hover_net/blob/842964dc5d26ffe196d236d16fad16643a103850/run_tile.sh#L3

should do the work.

**Comment by Luke3D** [comment]
Thank you for your reply! Sorry, I actually realized I didn't explain my question well. I was hoping to to measure how **confident** is the model about a **nucleus type prediction**. 

For example, say we have 4 classes (or instance types): "Tumor", "Immune", "Fibroblast", "Other".  
For a given nucleus, I would be interested in evaluating the probability of each class (with 4 classes this could be a 4D vector of probabilities, such as [0.85, 0.1, 0.03, 0.02]). 

However, given that the model is performing semantic segmentation, I was thinking I could get the pixel-wise softmax output, so to derive the **probability distribution of the class labels for each pixel**.  Could you point me to where in the code I could access this? 

Does it make sense? Would really appreciate your help.
Thanks!
Luca

**Comment by vqdang** [comment]
You will need to change how the output is aggregated

https://github.com/vqdang/hover_net/blob/842964dc5d26ffe196d236d16fad16643a103850/models/hovernet/run_desc.py#L183-L194

to return probabilities for caching

https://github.com/vqdang/hover_net/blob/842964dc5d26ffe196d236d16fad16643a103850/infer/wsi.py#L529-L534

to change the caching array to match with above

https://github.com/vqdang/hover_net/blob/842964dc5d26ffe196d236d16fad16643a103850/models/hovernet/post_proc.py#L109-L112

to retrieve the correct channels corresponding to the above

https://github.com/vqdang/hover_net/blob/842964dc5d26ffe196d236d16fad16643a103850/models/hovernet/post_proc.py#L161-L181

to retrieve pixel-wise probabilities per instance and add them to output dictionary.
