### ISSUE TITLE
Compute stats error

### ISSUE THREAD

**Issue by xiaoshuomin** [vqdang/hover_net#224]
Hello, good work! I met a problem when I was trying to compute the metrics for classification on CoNSeP by compute_stats.py. I got a output as [0.00046 0 0 0 0 0]. It seems that in the .json files the array for "inst_type" were empty.
My command for inference and metric computation:
python run_infer.py --gpu='0' --nr_types=5 --type_info_path=type_info.json --model_mode=original --model_path=logs/01/net_epoch=50.tar tile --input_dir=dataset/CoNSeP/Test/Images/ --output_dir=logs/consep50/ 

python compute_stats.py --mode=type --pred_dir=logs/consep50/ json/ --true_dir=dataset/CoNSeP/Test/Labels/
What should I do or what should I check

**Comment by xiaoshuomin** [comment]
![1666360829040](https://user-images.githubusercontent.com/43821417/197214340-718a04cb-5b22-450b-a7a9-3e76c0e20646.jpg)
The log for train and valid

**Comment by vqdang** [comment]
`compute_stats.py` receives folders containg `.mat` as input. Also, you should have some overlayed images for predictions for sanity check.
