### ISSUE TITLE
Error during training ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by jorgegaticav** [vqdang/hover_net#226]
Hi, 
I am using a custom dataset. 
I'm encountering this error during training (around epoch 5):

```
File "hover_net/models/hovernet/targets.py", line 40, in gen_instance_hv_map
    inst_list_remove(0)  # 0 is background
ValueError: list.remove(x): x not in list
```

I'm using `nr_type = 2`, `model_mode = "original"`,` aug_shape = [500, 500]`

Any suggestions?

**Comment by qdqzy** [comment]
hi, have you solved this problem?

**Comment by sumanthdonapati** [comment]
```
if 0 in inst_list:
    inst_list.remove(0)
```
add that 'if condition' at line 40 in target.py
