### ISSUE TITLE
evaluating indicator

### ISSUE THREAD

**Issue by zcb006** [vqdang/hover_net#232]
During the test, I want to read the evaluation indicators and loss values. How do I read them

**Comment by vqdang** [comment]
I'm quite unsure what do you mean by this. If you want to calculate the test statistics (PQ, DICE, etc,) , refer to this
https://github.com/vqdang/hover_net/tree/master/metrics

**Comment by zcb006** [comment]
I'm quite unsure what do you mean by this. If you want to calculate the test statistics (PQ, DICE, etc,) , refer to this
https://github.com/vqdang/hover_net/tree/master/metrics

**Comment by zcb006** [comment]
thank you But I want to know where this number is stored

**Comment by vqdang** [comment]
It prints out on the console, you can do `python sthg.py > log.txt` if you need persistent files
