### ISSUE TITLE
Where is the output answer to the result

### ISSUE THREAD

**Issue by zhouyi-git** [vqdang/hover_net#233]
Why can't I find the value of the three output indicators of the test, for example, Dice=0.85, where is the output?

**Comment by vqdang** [comment]
I'm not sure what you meant by `output indicators`, you mean the raw forward output? The processed prediction output? And please stop spamming all other issues.

If you simply want to calculate the test statistics (DICE, PQ, etc) refer to https://github.com/vqdang/hover_net/tree/master/metrics
