### ISSUE TITLE
HV_map

### ISSUE THREAD

**Issue by MukulKadaskar** [vqdang/hover_net#235]
Can you explain the generation of distance maps in targets.py i.e. gen_instance_hv_map...? x_map and y_map are returned but not assigned any values anywhere, won't that lead to all zeros as output.

**Comment by simongraham** [comment]
Hi @MukulKadaskar 

Horiz maps assigned [here](https://github.com/vqdang/hover_net/blob/master/models/hovernet/targets.py#L90).
Vert maps assigned [here](https://github.com/vqdang/hover_net/blob/master/models/hovernet/targets.py#L93).
