### ISSUE TITLE
how to Use DIST,Unet to train conic datase

### ISSUE THREAD

**Issue by mqbin** [vqdang/hover_net#236]
@simongraham @vqdang  ，hello，I want to train conic dataset using DIST, Unet methods and I found that these methods are only available in tensorflow implementation.  If I want to use the tensorflow version of the codes to train conic datasets using DIST and other methods, how should I modify it? Thanks.

**Comment by vqdang** [comment]
1. Convert https://github.com/vqdang/hover_net/blob/195ed9b6cc67b12f908285492796fb5c6c15a000/src/loader/augs.py#L283 to an approriate form like https://github.com/vqdang/hover_net/blob/326f17e0121b4338fd05caa83cfbb16a6851175e/models/hovernet/targets.py#L17 and replace https://github.com/vqdang/hover_net/blob/326f17e0121b4338fd05caa83cfbb16a6851175e/models/hovernet/targets.py#L102 with the new function
2. Define your UNet strcucture and slot it in https://github.com/vqdang/hover_net/blob/326f17e0121b4338fd05caa83cfbb16a6851175e/models/hovernet/net_desc.py#L149 as a replacement.
3. Change https://github.com/vqdang/hover_net/blob/master/models/hovernet/run_desc.py to what you want to do with UNet DIST.

**Comment by mqbin** [comment]
@vqdang Thank you very much for your reply, I will try it later. I want to extract 256*256 patches on the CoNSeP dataset (win_size = [512,512], step_size = [256*256]) and set the output of the model to 256*256 as well, just like on the conic branch. Do I need to change the code in the training code, and where do I need to change in the inference code? This will be useful for my research, thanks.
