### ISSUE TITLE
Issue about the annotations cropped by patch borders

### ISSUE THREAD

**Issue by ShangWeiKuo** [vqdang/hover_net#238]
Hello, @vqdang @simongraham I'm sorry to bother you. I would like to realize if it is possible to improve classification accuracy of model by removing the copped annotations touching with borders of patchs like the picture below ?

![image](https://user-images.githubusercontent.com/26018604/212222881-5a5c4ad1-2663-46b0-bff7-4de4da18cbdf.png)

**Comment by simongraham** [comment]
In the tile-level code, we merge the raw probability maps and then apply post processing. Therefore, we don't have any issues with nuclei at tile borders. It's a bit different when working with the WSI as it is very memory intensive to work with probability maps at high resolution. Therefore, we use a different strategy and apply a custom post processing technique to deal with border nuclei.

Refer to [this part](https://github.com/vqdang/hover_net/blob/master/infer/wsi.py#L559) of the code for more info.
