### ISSUE TITLE
Unable to reproduce the results on the CoNSeP dataset

### ISSUE THREAD

**Issue by mqbin** [vqdang/hover_net#239]
Hi, @vqdang @simongraham  I'm sorry to bother you. I used the model `hovernet_original_consep_type_tf2pytorch.tar`  for testing and ran `compute_stats.py` to get the following results
```
# type
[ 0.74810  0.87175  0.42644  0.63066  0.63511  0.56607] 
```

```
# instance [Dice, AJI, DQ, SQ, PQ, AJI+]
[ 0.84816  0.54643  0.66788  0.77082  0.51608  0.57441] 
```

DICE, PQ and AJI were [0.848 0.516 0.546], which did not reach the results you provided, and I am confused about this.

<html>
<body>

Platform | DICE | PQ | AJI
-- | -- | -- | --
TensorFlow | 0.8525 | 0.5477 | 0.5995
PyTorch | 0.8504 | 0.5464 | 0.6009

</body>
</html>

**Comment by vqdang** [comment]
The results in the table are **not for typing**. The models that were used for the table were trained for Instance segmentation only. That model is the one we provide as `hovernet_original_consep_notype_pytorch.tar` and `hovernet_original_consep_notype_tf2pytorch.tar`, please notice the **notype** in the file name.

**Comment by mqbin** [comment]
Thanks, I understand. For the evaluation of models with type branches only the type mode of compute_stats.py needs to be used, is that right?
