### ISSUE TITLE
Please provide docstrings and param specifications

### ISSUE THREAD

**Issue by jgamper** [vqdang/hover_net#24]
https://github.com/vqdang/hover_net/blob/38bf1e849f7ed04f6d14769837a9ca3f9cc66fe1/src/model/graph.py#L210

hey @simongraham and @vqdang, I am trying to reproduce hover-net. Could you please update the docstring of `get_gradient_hv` function. Specifically, what are the `h_ch, v_ch` here, and what are their dimensions. 

@navidstuv, this might be of interest to you

**Comment by vqdang** [comment]
@jgamper Updated, I hope it becomes clearer.

**Comment by jgamper** [comment]
Thanks for quick response @vqdang, that was useful!
