### ISSUE TITLE
Has PQ been tested?

### ISSUE THREAD

**Issue by jgamper** [vqdang/hover_net#26]
https://github.com/vqdang/hover_net/blob/909ef03d560a249a43d27bb8f4b677c7e4e410ee/src/metrics/stats_utils.py#L152

Hi @vqdang @simongraham 

When I feed this image (just random polygons with unique digits per polygon) for example into `get_fast_pq` function as both prediction and truth
![gt](https://user-images.githubusercontent.com/13080433/75785786-2c4f7280-5d5c-11ea-86c0-4dfaf33ab6f6.jpg)

I get an error:

```
----> 1 compute_fast_pq(y_t1, y_t2)

~/ds-field-boundaries/segmentation/utils/score.py in compute_fast_pq(true, pred, match_iou)
     55             if pred_id == 0: # ignore
     56                 continue # overlaping background
---> 57             p_mask = pred_masks[pred_id]
     58             total = (t_mask + p_mask).sum()
     59             inter = (t_mask * p_mask).sum()

IndexError: list index out of range
```

When it should produce a score of 1. 

Could you please clarify? Maybe I am missing something obvious here

**Comment by vqdang** [comment]
hi @jgamper check this please, https://github.com/vqdang/hover_net/blob/master/src/metrics/sample_stats.py
And about that error, that happened because the ID for each object in either `pred` or `true` likely isn't contiguous. Please call `remap_label` beforehand.

https://github.com/vqdang/hover_net/blob/909ef03d560a249a43d27bb8f4b677c7e4e410ee/src/metrics/stats_utils.py#L165-L168

**Comment by jgamper** [comment]
@vqdang as I pointed out above `pred` and `true` are exactly the same array, so the issue is not within  contiguous.

**Comment by vqdang** [comment]
@jgamper could you attach the .png of that image then? It's still working fine for `sample_stats.py`. Here is the piece I replaced to test same input.

```

import argparse
import math
import os
import random
import re  # regex

import cv2
import matplotlib.pyplot as plt
import numpy as np
import scipy.io as sio
from matplotlib import cm

from stats_utils import *

#####
def compute_stat():
    true   = cv2.imread('sample/true.png', cv2.IMREAD_GRAYSCALE)
    pred_1 = cv2.imread('sample/pred_1.png', cv2.IMREAD_GRAYSCALE)
    pred_2 = cv2.imread('sample/pred_2.png', cv2.IMREAD_GRAYSCALE)

    true   = remap_label(true, by_size=False)
    pred_1 = remap_label(pred_1, by_size=False)
    pred_2 = remap_label(pred_2, by_size=False)
    pq_info = get_fast_pq(pred_1, pred_1, match_iou=0.5)[0]
    print(pq_info)
    exit()

# ##
if __name__ == '__main__':
    compute_stat()
```

**Comment by jgamper** [comment]
![gt](https://user-images.githubusercontent.com/13080433/75791660-ce735880-5d64-11ea-94f1-3584c9ea885b.png)

here is a png ground truth as requested. Feed it as  prediction and ground truth as mentioned aboce.

**Comment by vqdang** [comment]
@jgamper 
Here is the content of your .png
>np.unique(jev)
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,\n       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,\n       34, 35, 36, 37, 38, 39, 40, 41, 43, 44], dtype=uint8)

I'm seeing 42 is missing there so your ID is not contiguous.
![jev_reponse](https://user-images.githubusercontent.com/24943262/75792699-3d04e600-5d66-11ea-920b-b3b93f57499a.png)

Fixing the label gives normal result

**Comment by jgamper** [comment]
Great! Thanks for pointing out the error on my side!

**Comment by vqdang** [comment]
@jgamper Additionally, your uploaded .png still has lots of artifacts. I think you should try to export the image again. May be that the reason it is not contiguous like you thought.

![jev_2](https://user-images.githubusercontent.com/24943262/75793576-77bb4e00-5d67-11ea-8ad8-1550da1bb9b1.png)

**Comment by jgamper** [comment]
Yep! Awesome, seems to be working now
