### ISSUE TITLE
CoNic implied on Mask-RCNN

### ISSUE THREAD

**Issue by zymissy** [vqdang/hover_net#268]

**Comment by zymissy** [comment]
Hello, I have a qestion about how to use the dataset CoNic on the model Mask-RCNN, since Mask-RCNN is a model with bbox. But the dasaset CoNic does not have bbox annotations.

**Comment by simongraham** [comment]
Hi, you could create bounding boxes from the instance segmentation masks. For example, minimum and maximum x and y coordinates of the contours.
