### ISSUE TITLE
Instace segmentation

### ISSUE THREAD

**Issue by zymissy** [vqdang/hover_net#269]
Hello, I am confused with the instance segmentation in your paper. Since the instance segmentation need to split every nuclei, tag every nuclei as different class. But in your paper, it seems like semantic segmentation. But you called it as instance segmentation. Looking forward to your reply.

**Comment by simongraham** [comment]
We have 3 branches. Binary segmentation, HoVer targets, semantic nuclei segmentation. HoVer targets are used to split the binary segmentation mask (achieved instance segmentation). The semantic segmentation output (TP branch) is used to determine the nuclear category for each segmented instance.
