### ISSUE TITLE
About CoNSeP Labels

### ISSUE THREAD

**Issue by GekFreeman** [vqdang/hover_net#27]
Hi, thanks for your excellent work!
I'm reproducing your work, but I have a problem here:
in src/compute_stats.py
`true_info = sio.loadmat(true_dir + basename + '.mat')`
the labels should be '.mat' format, however, the dataset I downloaded from the drive.google.com is '.npy' format, so my question is how to change the format, could you provide the source code?

**Comment by vqdang** [comment]
Hi, you can check this for related information https://github.com/vqdang/hover_net/issues/16#issuecomment-551842003 . And I think you should read that thread because It is related to evaluation code for CoNSeP

**Comment by simongraham** [comment]
Hi @GekFreeman ,

The numpy files can be loaded with np.load(filename). Thanks for positing this out- we will fix this issue this week.

**Comment by GekFreeman** [comment]
Thanks for your reply!
This #16  does solve my problem~

**Comment by vqdang** [comment]
@GekFreeman Feel free to reopen this if you have more question related to this topic.

**Comment by simongraham** [comment]
To update, we have now converted the ground truth such that all data is in `.mat` file format. Please refer to #31 for more information.
