### ISSUE TITLE
tiles are not adjacent in nuclei predictions (CAMELYON16)

### ISSUE THREAD

**Issue by kaczmarj** [vqdang/hover_net#280]
i have run hovernet on image `test_001.tif` from CAMELYON16, and there are empty regions between inference tiles. please see the attached image. i was the same command as https://github.com/vqdang/hover_net/blob/master/run_wsi.sh but with CAMELYON16 images. what could be the cause of this? and how can i fix it?

to download the image, you can use this:

```
aws s3 cp --no-sign-request s3://camelyon-dataset/CAMELYON16/images/test_001.tif .
```

![image](https://github.com/vqdang/hover_net/assets/17690870/6c14a0af-1e20-4b16-8b00-bde365c37ceb)

**Comment by kaczmarj** [comment]
this was my mistake. the intervening strips were present towards the end of the json file. i didn't load them all at once because it would crash the viewer i was using... anyway, no issue in hovernet.

**Comment by AhmadObeid** [comment]
Hi @kaczmarj, may I know which pre-trained weights you used to get these results on camleyon16? All datasets seem to have different nuclei sizes from camelyon16 (at least at 20x magnification), so when I tried the model on camelyon16 with the different pretrained weights I didn't get good results.
Thank you,

**Comment by AhmadObeid** [comment]
Edit:
Pannuke weights are actually quite good to segment camleyon16 at 20x, but not at 40x.
