### ISSUE TITLE
Issues testing data with certain images

### ISSUE THREAD

**Issue by luke2997** [vqdang/hover_net#29]
I am successfully able to test the image 'test_14.png' into the network, but for 'test_13.png' after I use infer.py I get a warning saying the instance type is of background type and the image does not load. Also when i enter compute_stats.py I just get the output in https://github.com/vqdang/hover_net/issues/13#issuecomment-541759157 even though the directories are correct and I followed the steps.

This implies the input is corrupt somehow. Either way, it shouldn't produce this for test_14 right as I got the correct output image from this and there were no errors in inference? 

So just to check, as the paths are definitely right, can I confirm how many test images should there be in the CoNSeP dataset? I had troubles unzipping the file so i'm not sure if it has become corrupt, i only get test_13 & test_14, perhaps causing the issue. Also, the output should give both .mat and .png files out right?

It could also be an error with Numpy as when I run infer.py I get this:

` FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])`

UPDATE: Although now I can't even seem to get test_14.png to work...

**Comment by vqdang** [comment]
I think your downloaded zip is corrupted, I have just redownloaded it and it's working fine on my side. Test set should contain the following images
``
test_10.png  test_13.png  test_2.png  test_5.png  test_8.png
test_11.png  test_14.png  test_3.png  test_6.png  test_9.png
test_12.png  test_1.png   test_4.png  test_7.png
```
I suggest you try to redownload it. Is there any host outside of China that you can reliably download from? I can upload to another host.

**Comment by luke2997** [comment]
OK i've managed to redownload it on my remote server successfully! 

After inference I get the .mat files of all the test images as below however annoyingly I still get NaNs when computing the statistic scores... 

<img width="623" alt="Screenshot 2020-03-08 at 20 29 25" src="https://user-images.githubusercontent.com/57980381/76162767-919bcd00-617b-11ea-9636-73b5161cbbe3.png">

Just to confirm, these are my changes:

Added this path:`self.inf_model_path  = 'user...../media/logs/v1.0/np_hv/01/model-34200.index'`

Inserted this line into compute_stats.py
        ```true_inst_type[(true_inst_type == 3) | (true_inst_type == 4)] = 3
        true_inst_type[(true_inst_type == 5) | (true_inst_type == 6) | (true_inst_type == 7)] = 4```

Also added
```plt.subplot(1,2,1)
plt.imshow(true)
plt.subplot(1,2,2)
plt.imshow(pred)
plt.show()```

**Comment by vqdang** [comment]
Have you run the `process.py` ? Once it is run, you will have a new `_proc` folder which contains new .mat . These .mat are the final output.

**Comment by luke2997** [comment]
Ah of course, I forgot to run that this time round... when I run compute stats with the new directories I get some files of background type.. does this mean it's not detected any nuclei? I'm not getting any score outputs either, should I be seeing that here?
<img width="897" alt="Screenshot 2020-03-08 at 22 09 14" src="https://user-images.githubusercontent.com/57980381/76164412-a2ebd600-6189-11ea-99a6-208bf8ef206d.png">

**Comment by vqdang** [comment]
Once you finish running `process.py`, you then run the `compute_stats.py` to get the scores. The warning is for 1 nuclei instance. That warning indicates that the nuclear is detected but the class segmentation is of subpar quality (i.e containing no pixels for any type at all).

https://github.com/vqdang/hover_net/blob/909ef03d560a249a43d27bb8f4b677c7e4e410ee/src/process.py#L112-L116

**Comment by luke2997** [comment]
Makes sense thanks a lot for helping!!

**Comment by luke2997** [comment]
Sorry one other thing - I'm trying to get the tables/figures in your evaluation metrics section of segmentation/classification by running `python compute_stats.py --mode=type --pred_dir='pred_dir' --true_dir='true_dir'`, however I just get the F1 scores and nothing changes.. Also what do i need to add to the code to find the pq score for classification?

**Comment by luke2997** [comment]
Sorry one other thing - I'm trying to get the tables/figures in your evaluation metrics section of segmentation/classification by running `python compute_stats.py --mode=type --pred_dir='pred_dir' --true_dir='true_dir'`, however I just get the F1 scores and nothing changes.. Also what do i need to add to the code to find the pq score for classification?

**Comment by vqdang** [comment]
To get the the PQ, you have to set `--mode="instance"` . The PQ should then be the 4th value from the printed out (order is DICE DQ SQ PQ AJI+ AJI)

**Comment by luke2997** [comment]
It seems to be the same scores for both `python compute_stats.py` and `python compute_stats.py--mode="instance`

**Comment by vqdang** [comment]
Default mode for `python compute _stats.py` is `mode='instance'` .

**Comment by luke2997** [comment]
Thanks - I'm not getting it running for the type. To confirm should `run_nuclei_type_stat` and `run_nuclei_inst_stat` have the same arguments, right? As it's expecting .mat files for the true_dir which i **thought** should be ground truth .npy labels?

**Comment by vqdang** [comment]
I'm sorry but please check this to deal with the .mat problem. https://github.com/vqdang/hover_net/issues/16#issuecomment-551842003 . We will resolve this sometimes later to align all input format.

**Comment by luke2997** [comment]
Thanks - just to confirm my output, this just produces the **overall** classification score though right, rather than for each individual image like segmentation does? If so why the discrepancy and can you advise how i can incorporate this into `run_nuclei_type_stat` so i can see a score for each image:

``` print(basename, end="\t")
            for scores in metrics:
                print("%f " % scores[-1], end="  ")
            print()

metrics = np.array(metrics)
    metrics_avg = np.mean(metrics, axis=-1)
    print(metrics_avg)
    metrics_avg = list(metrics_avg)
    return metrics
```

**Comment by simongraham** [comment]
For the instance segmentation stats, you can change this line to True:

https://github.com/vqdang/hover_net/blob/master/src/compute_stats.py#L154

We should really put this as an argument in the function. We will also fix this such that you can print the stats per image for the classification statistics. Leave this with us and we will integrate it.

**Comment by luke2997** [comment]
Thanks for clarifying!
