### ISSUE TITLE
Revision: Improving codebase clarity and usages

### ISSUE THREAD

**Issue by vqdang** [vqdang/hover_net#31]
Basing on recent created issues from other users. There are following problems need to be tidied up.

- [x] inconsistency between .mat and .npy files
- [x] hard coding of the dice loss number of nuclei types in graph
- [x] hard coding of nuclei types for stats collector in train.py

Any proposal and revision should be posted here for tracking.

**Comment by simongraham** [comment]
All GT has now been converted to .mat to solve inconsistency between `.npy` and `.mat` in the repo. 

Please refer to the `README.md` to download the updated data.
