### ISSUE TITLE
About data augmentation

### ISSUE THREAD

**Issue by Michaelsqj** [vqdang/hover_net#35]
Hi! I have a question about augmentation. Performing augmentation like rotation or affine to the images and masks always comes with interpolation, which I find will corrupt the instance map and class map of the GT masks.  I think maybe this will cause problem to the training. How do you solve this problem? 
Thank you so much for your time!!

**Comment by simongraham** [comment]
Hi @Michaelsqj 

Yes, you are right- you need to be careful with any transformation of the labels because of interpolation. We use nearest neighbour interpolation to make sure there are no issues here. This is set at:

https://github.com/vqdang/hover_net/blob/master/src/config.py#L132
