### ISSUE TITLE
Problem of using GPU in Hover-Net

### ISSUE THREAD

**Issue by aaronxie666** [vqdang/hover_net#39]
As I am using co-lab to train the model and it only has one physical GPU which makes the progress very slow.
I am trying to set up two logical GPUs using TensorFlow, however, the error always comes up and the picture below shows the error.

So, my question is can I use tensorpack.train.launch_train_with_config(config, SyncMultiGPUTrainerParameterServer(nr_gpus)) with logical gpus?

Here is my approach:

gpus = tf.config.experimental.list_physical_devices(‘GPU’)
    if gpus:
        # Create 2 virtual GPUs with 1GB memory each
        try:
            tf.config.experimental.set_virtual_device_configuration(
                gpus[0],
                [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024),
                tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])
            logical_gpus = tf.config.experimental.list_logical_devices(‘GPU’)
            print(len(gpus), "Physical GPU,", len(logical_gpus), "Logical GPUs”)
        except RuntimeError as e:
            # Virtual devices must be set before GPUs have been initialized
            print(e)

tf.device(logical_gpus) #original is os.environ['CUDA_VISIBLE_DEVICES'] = logical_gpus

The Error shows:
<img width="991" alt="Screen Shot 2020-04-08 at 11 48 52 PM" src="https://user-images.githubusercontent.com/37965905/79157848-38a00400-7dcd-11ea-9eec-cf93cb54d9ca.png">

Thanks,
Chang

**Comment by vqdang** [comment]
Hi, from the attached snipped, I assume you are using the current tensorflow [API doc](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth). In that case, I don't think what you are trying to do will work with our code, which was developed basing on tf 1.12 . From the [link](https://www.tensorflow.org/guide/gpu#using_multiple_gpus), the logical GPU are split from the physical GPU. The training required at least 1 11GB GPU. So, if your physical GPU doesn't even have 22GB, I don't think asking for 2 11GB will work.

In case that you still want to try. The modified config for tf session has to be provided into the TrainConfig, check [here](https://tensorpack.readthedocs.io/modules/train.html#tensorpack.train.TrainConfig) for the related parameters and modify it accordingly. However, if what you are doing is setting a flag within tensorflow, you have to perform that at the top of `train.py` file. In either case, we wont provide additional help for such usage .

**Comment by vqdang** [comment]
Close due to inactivity

**Comment by aishikhar** [comment]
The [Error](https://github.com/vqdang/hover_net/issues/39#issue-599114837) you're facing here is simply due to tensorpack backward compatibility issues b/w versions  >10.0 & <=0.9.
Just do the following:

`pip uninstall tensorpack`
`pip install tensorpack==0.9.0.1`

Should solve the issue. Cheers.
