### ISSUE TITLE
resampling code

### ISSUE THREAD

**Issue by CCz23** [vqdang/hover_net#41]
Excellent work - if i wanted to change the resampling techniques from NN to interpolation, please advise where is this part of the code? Also, have you trained on the PanNuke dataset? If so are any changes are needed? Thank-you.

**Comment by simongraham** [comment]
Thank you! I assume that you are referring to upsampling here. You can alternatively upsample with interpolation by using:

```
tf.image.resize_images(
    images,
    size,
    method=ResizeMethod.BILINEAR,
    align_corners=False
)
```

Here, you can also use `method=ResizeMethod.BICUBIC`. 

Yes, we did train on the PanNuke dataset. For this we changes the input size to 256x256, in line with the size of the pre-extracted patches. If you are simply reporting a model on the PanNuke dataset (patches of size 256x256), then you can use same padding in the decoder and similarly output a patch of size 256x256. The valid convolution is only necessary when using a sliding window approach to prevent border artefacts.

We will be releasing a repository of a HoVer-Net model trained on PanNuke that used to process ROIs and WSIs very soon. Please let me know if this is of interest.

**Comment by CCz23** [comment]
Thanks a lot and okay sure, i would be interested in seeing this!
