### ISSUE TITLE
error running train.py

### ISSUE THREAD

**Issue by Michaelsqj** [vqdang/hover_net#43]
![image](https://user-images.githubusercontent.com/47425492/82280717-113ae900-99c2-11ea-8d34-90eb9f48d11c.png)

Hi! When I ran train.py, I ran into this. I wonder where might be the problem?

**Comment by Michaelsqj** [comment]
![image](https://user-images.githubusercontent.com/47425492/82284200-09337700-99cb-11ea-93d3-56058d7484bf.png)
Hi! I've solved the problem above, but then I ran into NotImplemented problem.

**Comment by simongraham** [comment]
This will most likely be due to the versions of libraries you are using. Please set up a new environment using:

```
conda create --name hovernet python=3.6
conda activate hovernet
pip install opencv-python=3.2 scipy scikit-image pandas matplotlib
pip install --upgrade git+https://github.com/tensorpack/tensorpack.git@0.9.0.1
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.12.0-cp36-cp36m-linux_x86_64.whl
```
and try again.

**Comment by Michaelsqj** [comment]
Dear Graham, thank you so much for your help, the problem miraculously disappeared!

**Comment by Dogdog00** [comment]
> Dear Graham, thank you so much for your help, the problem miraculously disappeared!

您好，您这个问题是怎么解决的？

**Comment by Michaelsqj** [comment]
> > Dear Graham, thank you so much for your help, the problem miraculously disappeared!
> 
> 您好，您这个问题是怎么解决的？

Hi, I think it might be related to the version of tensorflow! Please try setting up the new environment with tensorflow 1.12.0, as  
Graham wrote.
> This will most likely be due to the versions of libraries you are using. Please set up a new environment using:
> 
> ```
> conda create --name hovernet python=3.6
> conda activate hovernet
> pip install opencv-python=3.2 scipy scikit-image pandas matplotlib
> pip install --upgrade git+https://github.com/tensorpack/tensorpack.git@0.9.0.1
> pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.12.0-cp36-cp36m-linux_x86_64.whl
> ```
> 
> and try again.
