### ISSUE TITLE
pre-trained model not found

### ISSUE THREAD

**Issue by JMBokhorst** [vqdang/hover_net#44]
Hi, 

I'm wanted to experiment with the model presented in your paper. Unfortunately however, I'm not capable of running the model out of box because the pre-trained model is missing. 

Also the link on the Warwick website seems to be broken, could you help me? 

Thanks in advance.

**Comment by simongraham** [comment]
Hi @JMBokhorst 

A list of the pre-trained models in this reppsitory can be found at the bottom of the README [here](https://github.com/vqdang/hover_net/blob/master/src/README.md). If you plan to use HoVer-Net out  of the box in another project, then you may instead by more interested in [this model](https://github.com/simongraham/hovernet_inference) that has been trained on around 200,000 nuclei and has been optimised for inference. Let me know if you have any further questions.

**Comment by simongraham** [comment]
Closing this issue, but please comment if you have any further questions
