### ISSUE TITLE
PQ calculation issue.

### ISSUE THREAD

**Issue by ValeAri** [vqdang/hover_net#48]
Hello!
I have a problem with the PQ value. I just run the code with the given samples and the PQ is 0 and not that one present in the readme file. I also tried with my samples but the results is the same.
Could you please help me?
Thank you in advance!

**Comment by vqdang** [comment]
Hi,

Could you provide more detail about what you have tried (command line setup) and what you want to do ? I could not clearly understand what you are trying to do here. Do you want to test run PQ calculation code? Do you want to use on your own dataset / our dataset?

About the sample results displayed here 
https://github.com/vqdang/hover_net/tree/master/src/metrics
They were obtained by running `sample_stats.py` using the `/src/metrics` as the root folder like this
![image](https://user-images.githubusercontent.com/24943262/83313335-a5505000-a20d-11ea-997c-be27b236aa42.png)

**Comment by ValeAri** [comment]
Hello! 
Thank you for the answer! I am sorry that I was not clear. I tested the code with your default data so I downloaded the metrics folder and run python sample_stats.py as you. But my output is:

![img](https://user-images.githubusercontent.com/49314711/83348427-23f3dd00-a335-11ea-9865-028c51554910.png)

I also tried with my data just to see if something change...of course not. I found that the values in the PQ function are very low so some variable are considered empty.
Anyway, I do not get why running the code as you, I obtained different results, I also downloaded again the folder but nothing....The results is always 0 for the PQ.

Thank you in advance!

**Comment by vqdang** [comment]
Hi, 

Thanks for you response. I suggest you first ensure that your code is the latest ones from the repos, then follow [this](https://github.com/vqdang/hover_net#set-up-environment) to setup an appropriate conda environment. I'm suspecting you are using different version of python/numpy/scipy or something. If you run directly from the terminal without extra setup, you likely were using python2, which will likely break the code.

Afterward, please insert `print(pairwise_iou)` at https://github.com/vqdang/hover_net/blob/f5419068da18a338509854b4f8260ee901bff88e/src/metrics/stats_utils.py#L211
and insert `print(paired_true, unpaired_true, unpaired_pred)` at
https://github.com/vqdang/hover_net/blob/f5419068da18a338509854b4f8260ee901bff88e/src/metrics/stats_utils.py#L239
for more debugging tracking.

Once they are done, run the `sample_stats.py` again, check if you have following results on the terminal.

![image](https://user-images.githubusercontent.com/24943262/83354086-cb313e00-a34e-11ea-8baf-f63fe2d67e59.png)

**Comment by ValeAri** [comment]
Thank you so much! Probably I had an old version as you thought and now it works! :)
