### ISSUE TITLE
Running inference on CoNSeP

### ISSUE THREAD

**Issue by tabibusairam** [vqdang/hover_net#51]
Hi, I'm trying to run the inference on ConSeP using the pretrained model on CoNSeP for instance segmentation. I put the CoNSep data folder as it is ( from the link given in Readme )

<img width="568" alt="Screen Shot 2020-07-08 at 5 42 06 PM" src="https://user-images.githubusercontent.com/12710772/86977564-7f8a6500-c142-11ea-87f5-6108d5496440.png">

Here are the changes I did in my config.py

i'm getting an error like this - 
<img width="1046" alt="Screen Shot 2020-07-08 at 5 44 25 PM" src="https://user-images.githubusercontent.com/12710772/86977634-ae084000-c142-11ea-9184-a1769a1853c4.png">

Any ideas on what's going wrong ? 
Your help is really appreciated. Thanks.

**Comment by tabibusairam** [comment]
I put the CoNSep data folder as it is ( from the link given in Readme )

**Comment by vqdang** [comment]
@tabibusairam Hi, that error likely occurs because you use a new version of tensorpack. Please refer to this to setup corresponding environment.
https://github.com/vqdang/hover_net#set-up-environment

**Comment by tabibusairam** [comment]
Hi @vqdang Thanks for the reply.

I updated the versions ( but only I'm using python 2.7 ( can't change on the system ) and have modified all the print statements too. When I run infer.py I get these None values. I don't understand if I'm not giving the model correctly or the data structure in the data folder has to be different.

[texrtfile.txt](https://github.com/vqdang/hover_net/files/4894283/texrtfile.txt)

**Comment by vqdang** [comment]
> I'm using python 2.7 ( can't change on the system )
Hi, I'm sorry, I don't think I can help in this case because this code, as well as some important library, was developed under python3. Any attempts to change to python2 may break the underlying behavior, and we don't have any intention to extend to python2.

**Comment by tabibusairam** [comment]
@vqdang Thanks for your reply. I'll see if I can shift is to Python3. Meanwhile closing the issue.
