### ISSUE TITLE
Hover net decoder

### ISSUE THREAD

**Issue by ChristianEschen** [vqdang/hover_net#6]
Hi

I am trying to reimplement your implementation in pytorch.
In Line 91 you do 1x1 convolution. However it looks like the output of the dense block with input 256 and growth rate 32 for 8 layers gives 512 already.   (     u3 = Conv2D('convf', u3, 512, 1, strides=1) )

Why do you do 1x1 convolution in line 91 when the volume already has dimension equal to 512?
Normally you do 1x1 convolution to do a linear combination of features.

best regard
Christian

**Comment by vqdang** [comment]
Hi

If you look into https://github.com/vqdang/hover_net/blob/81a82bc77d2c13f60df3a85055d09fe969be35b1/src/model/graph.py#L44
you can actually see the dense block doesn't have a final 1x1. Hence, although output of dense block, in `u3` case, is 512 concatenated feature maps, we additionally use  `u3 = Conv2D('convf', u3, 512, 1, strides=1)` to perform linear combination of 512 concatenated features map.

**Comment by simongraham** [comment]
Hi @ChristianEschen . First of all, thanks for your interest in our work.

In addition to @vqdang , 1x1 convolutions are not only used to increase/decrease the number of feature maps. Here, we simply view the 1x1 conv as a linear transformation to better merge the channel information. 

I will close this issue, as it has now been resolved.
