### ISSUE TITLE
Can't view the dataset

### ISSUE THREAD

**Issue by haiqinzhong** [vqdang/hover_net#60]
Hi, @simongraham and @vqdang .I have met a understanding issue when I run the train by used command "python train.py --view train", it only gave two warns and then the procedure was killed . I can't find any image to see. Just like this:

![无标题](https://user-images.githubusercontent.com/56585970/92326183-e238a800-f082-11ea-8bf5-a465370f09b6.png)
 
I search the MatplotlibDeprecationWarning online , and find someone say it not a problem. so what cause this issue , the last warn or others? ( by the way , train.py is run well if use the command : python train.py --gpu='0' )

**Comment by simongraham** [comment]
It appears you are not quite using the correct command. Instead use `python train.py --view='train'`

**Comment by haiqinzhong** [comment]
@simongraham ，Hi , Thanks for your reply . It seems that there is still a problem, the image is not displayed, is it because I am connecting to the Linux server through XShell ?

**Comment by haiqinzhong** [comment]
![3](https://user-images.githubusercontent.com/56585970/92394632-76267480-f154-11ea-90da-b5dc387f5da0.png)

It has been in this state for eight minutes

**Comment by vqdang** [comment]
If you are remoting like ssh, you dont have the GUI. The code will just stuck there.

**Comment by haiqinzhong** [comment]
thanks for your help .
