### ISSUE TITLE
Some models run errors

### ISSUE THREAD

**Issue by haiqinzhong** [vqdang/hover_net#62]
Well , I am sorry that the question did not start a new issue and made you feel duplicated twice. This is the reason why I did not edit the question well .  And that not duplicate 2 times. I'll show you the errors separately.
As the first :  when I train for dcan and np_dist . I just modify as follow(it can run well while run others model):
https://github.com/vqdang/hover_net/blob/5d1560315a3de8e7d4c8122b97b1fe9b9513910b/src/config.py#L20
https://github.com/vqdang/hover_net/blob/5d1560315a3de8e7d4c8122b97b1fe9b9513910b/src/config.py#L21
I modify it to `mode=other` and `self.model_type=dcan` (or `mode=hover` and `self.model_type=np_dist` , the two models , **DCAN** and **NP_DIST**) , and then it get the same error , such as:
![1](https://user-images.githubusercontent.com/56585970/92935609-953a4480-f47b-11ea-9868-ec0af7bd0b62.png)
it get error after finish first epoch .

**Comment by haiqinzhong** [comment]
As the second ,  when I train for fcn8 and segnet ,  I modify it to `mode=other` and `self.model_type=fcn8`(`self.model_type=segnet`) , and it get the follow error:
![2](https://user-images.githubusercontent.com/56585970/92937547-0b3fab00-f47e-11ea-9612-b702d0122bd4.png)
![3](https://user-images.githubusercontent.com/56585970/92937553-0d096e80-f47e-11ea-9c9d-e5ffd34057b6.png)

I don't know what error is , so I can only show you the wrong screenshot. 
Wish you can teach me what these errrors are and how to solove they?

**Comment by vqdang** [comment]
The error just indicates that the input has different shape than the shape declared in the network. You should focus on
```Can not feed value etc.```

>mode=other and self.model_type=fcn8

The code has been setup that only some corresponding model names and combination between these two variables are runnable. Typically, for `mode='hovernet'` it is `self.model_type=np_dist` or `self.model_type=np_hv`. As for other networks (dcan etc.), `mode='other'` and  `self.model_type` is the network name (`dcan`, `fcn8`). Additionally, not all models support typing, only those reported in Table 5 have it, so you must switch off https://github.com/vqdang/hover_net/blob/5d1560315a3de8e7d4c8122b97b1fe9b9513910b/src/config.py#L23
for dcan, fcn8, segnet . Anyways, I just made a clean clone of the current repos and tested run it again, so if you did above, the code should be running ok.

**Comment by haiqinzhong** [comment]
yes, when switch the `self.type_classification=true` off , dcan and np_dist work well . but the fcn8 and segnet also has erro , whether I should change the shape in network.

**Comment by vqdang** [comment]
I need additional info then. As I said, I tested run again by re-cloning the current repos and here are the changes
![image](https://user-images.githubusercontent.com/24943262/92997270-f27cd700-f509-11ea-8f92-8cfa50cc9d46.png)
The replacement of path leading to input patches is not included here. But these are enough to bootstrap the training for `fcn8` and `segnet`. I suggest you make a clean copy and double check that first.

**Comment by haiqinzhong** [comment]
Again, there may be some unpredictable error in my environment.Or maybe I modified some of the other code, but other than those two models everything worked fine.Fcn8 and Segnet still have errors so let's not test them.All in all, it's important that your model is good. Thank you again for your code and paper, and for coming to your guidance these days.
