### ISSUE TITLE
About pre-training

### ISSUE THREAD

**Issue by zerodohero** [vqdang/hover_net#63]
How can I start from scratch without using pre-training, where do I need to change

 'training_phase'    : [
        {
            'nr_epochs': 50,
            'manual_parameters' : { 
                # tuple(initial value, schedule)
                'learning_rate': (1.0e-4, [('25', 1.0e-5)]), 
            },
            'pretrained_path'  : '../../../pretrained/ImageNet-ResNet50-Preact.npz',
            'train_batch_size' : 8,
            'infer_batch_size' : 16,

            'model_flags' : {
                'freeze' : False
            }
        },

        {
            'nr_epochs': 50,
            'manual_parameters' : { 
                # tuple(initial value, schedule)
                'learning_rate': (1.0e-4, [('25', 1.0e-5)]), 
            },
            # path to load, -1 to auto load checkpoint from previous phase, 
            # None to start from scratch
            'pretrained_path'  : -1,
            'train_batch_size' : 4, # unfreezing everything will
            'infer_batch_size' : 16,

            'model_flags' : {
                'freeze' : False
            }
        }
    ],
Here,??

**Comment by vqdang** [comment]
The instruction is within the comment, set 'pretrained_path' to None.
