### ISSUE TITLE
How does the same color map to different Numbers

### ISSUE THREAD

**Issue by zerodohero** [vqdang/hover_net#67]
Sorry to bother you again.

https://github.com/vqdang/hover_net/issues/54
You have answered me about the comment, but I did not find that you said that when generating "inst_map", as long as touching nuclei were not annotated with the same colour. 
My problem now is how to map the same color to different Numbers to generate "inst_map"

**Comment by simongraham** [comment]
Hi @zerodohero 

We did this by using python. There are various ways to do it. First convert the image to a numpy array and then write a functioin to ensure that all nuclei have different values.

**Comment by zerodohero** [comment]
Thank you, I have solved it
