### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by Amiiirali** [vqdang/hover_net#69]
Hello,

I have a question regarding the labels. I was not able to find out which color belongs to which labels.

In the repo, you have mentioned that Blue: epithelial, Red: inflammatory, Green: spindle-shaped, Cyan: miscellaneous, but in the paper, there are different colors regarding to these labels. I have tested the code on a sample data, and have produced different colors too. Perhaps I think the colors are random (?) How can I find the exact label that corresponds to each color?

**Comment by vqdang** [comment]
Hi,

There are 6 nuclei typer manually labeled in CoNSeP, coded from 1-7 , from the dataset README.
```
Class values: 1 = other
	      2 = inflammatory
	      3 = healthy epithelial
	      4 = dysplastic/malignant epithelial
              5 = fibroblast
              6 = muscle
	      7 = endothelial
```
3 and 4 are merged to make Epithelium, and 5-7 are merged to make Spindle. You can extract the color out yourself from the paper and plot the nuclei with them via https://github.com/vqdang/hover_net/issues/59#issuecomment-688744946.

**Comment by Xu-bowen** [comment]
Hi,
I have a question regarding the labels generation like hv distance, unet weight map and coutour label, there operation treat with instance label one by one, thus may leading to data loading very slow. But pregenerate these labels and  crop would cause problem in the image border. So i wonder how pregeneration effect the finally performance, have you test it?  By the way in these operation, you drop the instance in the  image border, using:

`            if inst_map.shape[0] < 2 or \
                inst_map.shape[1] < 2:
                continue
`
it could also drop some instance with considerable size. What do you think?☺

**Comment by vqdang** [comment]
@Xu-bowen refer #17  for your question. Anyways, this is unrelated to this issue, so if you should create another one if you have other questions.
