### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.training.device_util'

### ISSUE THREAD

**Issue by suyouooooo** [vqdang/hover_net#71]
I got an error "ModuleNotFoundError: No module named 'tensorflow.python.training.device_util'" when I run train.py, my cuda version is 10.0, so I have to use tensorflow-gpu>=1.13.0, do you know how to slove it? I would appreciate it if you could answer my question.
<img width="1237" alt="截屏2020-11-16 下午9 32 42" src="https://user-images.githubusercontent.com/30383402/99258270-4500a980-2853-11eb-9f66-7adbfef162f4.png">

**Comment by simongraham** [comment]
Hi @suyouooooo ,

You must use the tensorflow version 1.12 to use this code.
