### ISSUE TITLE
Patch for Tensorflow 1.13

### ISSUE THREAD

**Issue by david-belinsky-sbu** [vqdang/hover_net#72]
On some systems we cannot use any version of tensorflow below 1.13. Is there any patch available which allows hovernet to function with tensorflow version 1.13 or greater?

**Comment by simongraham** [comment]
Hi @david-belinsky-sbu ,

Unfortunately for this repository we do not support tensorflow version > 1.12. However, within the next few days we will be releasing a PyTorch version of this code. Stay tuned!

**Comment by vqdang** [comment]
@david-belinsky-sbu We release the pytorch version. Happy holidays! 🚀
