### ISSUE TITLE
How to set training parameters on my own datasets

### ISSUE THREAD

**Issue by XiHuYan** [vqdang/hover_net#73]
Hi,  @vqdang, thanks for the great work.

I have tested your method on my own datasets, as shown in the figure below.
The left panel is the prediction, the right is the ground truth

![dic3](https://user-images.githubusercontent.com/41266664/101431915-d5a64300-3942-11eb-8a0b-e9e4de802631.png)
![dic4](https://user-images.githubusercontent.com/41266664/101432407-c70c5b80-3943-11eb-8758-b71dce9b4adb.png)

I followed exactly your training and testing pipline:  
   1) run extract_patch.py for training and valid samples
   2) training with default parameters
   3) used the maximum dice score to select the 'optimal' checkpoint
   3) run infer.py and process.py

Obviously, the results is unsatisfactory. 
Is this due to training parameters or other factors? How can I adjust to get the desired result?

**Comment by simongraham** [comment]
Hi @XiHuYan ,

What image domain is this? Please can you also supply the original images so that we can give a more informed answer.

**Comment by XiHuYan** [comment]
These images came from the Cell tracking Challenge([http://celltrackingchallenge.net/2d-datasets/](url)), and the data set I used was [DIC-C2DH-HeLa(http://data.celltrackingchallenge.net/training-datasets/DIC-C2DH-HeLa.zip).](url).

I guess the reason for poor performance is the input size(80*80) is too small

**Comment by simongraham** [comment]
It is important to note that the input size is not 80x80. This is the output size. In fact, the input size is 270x270 and the output is smaller due to valid convolution being used in the decoders. 

We did not experiment with the image domain that you are using and therefore can not comment on the expected performance.

**Comment by Dogdog00** [comment]
> These images came from the Cell tracking Challenge([http://celltrackingchallenge.net/2d-datasets/](url)), and the data set I used was [DIC-C2DH-HeLa(http://data.celltrackingchallenge.net/training-datasets/DIC-C2DH-HeLa.zip).](url).
> 
> 
> 
> I guess the reason for poor performance is the input size(80*80) is too small
> 
> 
> 
> 

你好，我想问一下你的数据集是怎么标注的？我现在想测试自己的数据，数据只有原始图片

**Comment by XiHuYan** [comment]
我并没有自己标注图像，我直接使用的一个挑战赛上的数据集，比赛链接已经在上文提到了。
