### ISSUE TITLE
About the release of pytorch version

### ISSUE THREAD

**Issue by musikisomorphie** [vqdang/hover_net#75]
Hi @simongraham, thanks for the great work. The hover_net paper is very inspiring. 
You mentioned in  #72 about the upcoming pytorch release of hover-net.
By any chance that you will release it before Christmas? Thank you very much.

**Comment by vqdang** [comment]
@musikisomorphie  Now release 🚀

**Comment by musikisomorphie** [comment]
@vqdang thank you very much,💯
