### ISSUE TITLE
Not working with windows

### ISSUE THREAD

**Issue by ChristianEschen** [vqdang/hover_net#8]
The model does not work with windows.

I get the following error:

[270, 270] [80, 80]
Traceback (most recent call last):
  File "train.py", line 268, in <module>
    trainer.run()
  File "train.py", line 236, in run
    self.run_once(opt, sess_init=init_weights, save_dir=log_dir)
  File "train.py", line 170, in run_once
    train_datagen = self.get_datagen(opt['train_batch_size'], mode='train')
  File "train.py", line 158, in get_datagen
    nr_procs=nr_procs)
  File "C:\Users\Administrator\hover_net\src\loader\loader.py", line 73, in train_generator
    ds = PrefetchDataZMQ(ds, nr_procs)
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\tensorpack\dataflow\parallel.py", line 320, in __init__
    super(MultiProcessRunnerZMQ, self).__init__()
  File "C:\ProgramData\Anaconda3\envs\tf_gpu\lib\site-packages\tensorpack\dataflow\parallel.py", line 90, in __init__
    assert os.name != 'nt', "ZMQ IPC doesn't support windows!"
AssertionError: ZMQ IPC doesn't support windows!

bh
Christian

**Comment by simongraham** [comment]
Hi Christian,

Please comment out this line:

https://github.com/vqdang/hover_net/blob/master/src/loader/loader.py#L73

Please let me know if this solves the issue.

Simon

**Comment by vqdang** [comment]
Hi Christian,

This is the issue with Tensorpack and as @simongraham  said, you can run the code if you remove 
https://github.com/vqdang/hover_net/blob/4d1c416bd8ca5833f1588a5db7b4a75b2c0d8083/src/loader/loader.py#L73
but you need something with the same functionality, namely caching the date processed from multiple threads, else your training speed may suffer.

You can see my question and response years ago regarding the ZMQ here
https://github.com/tensorpack/tensorpack/issues/393
maybe you can try that and see whether you can run on Windows or not. 

To be honest, I advise you to run the code on Linux, some functions from the supporting libraries have undefined behavior in Windows.

**Comment by vqdang** [comment]
Close due to lacking activity, feel free to reopen it if you / anyone have a similar question.

**Comment by vqdang** [comment]
Just attach this so later issue can track the possible solution.
https://github.com/tensorpack/tensorpack/issues/100
