### ISSUE TITLE
cannot run run_infer.by command

### ISSUE THREAD

**Issue by talkhanz** [vqdang/hover_net#82]
I have tried running infer.py but for some reason I cannot enter the right command.  I could not get an example command from the github repo so I am asking out here for help.

Please have a look at my example command. You can assume the paths entered are correct

![run_infer_command](https://user-images.githubusercontent.com/63508490/104087481-dacc1a00-5281-11eb-9bb1-bcd89d09fa88.PNG)

**Comment by vqdang** [comment]
we provide the cmd sample usage here.
https://github.com/vqdang/hover_net/blob/master/run_wsi.sh

**Comment by vqdang** [comment]
@talkhanz on another note, it seems you are running on windows, please keep us updated on any problems as we have limited feedback on windows.

**Comment by talkhanz** [comment]
@vqdang I have tried the command and it starts the script but I am getting out of memory CUDA errors for even small tiles. is it possible if I could instantiate the model from scratch with the pretrained weights of pannuke?

**Comment by vqdang** [comment]
@talkhanz you may need to change the batch size in the script down to 4 or 8 or lower. The provided default settings in the script are for systems with 4 gpus 11-12 GB eachs.

**Comment by talkhanz** [comment]
<img width="674" alt="exit" src="https://user-images.githubusercontent.com/63508490/104118350-2b0eaf00-534a-11eb-9133-dd67c362edb8.PNG">
I believe the exit() statement in the above picture in the run_infer.py is a bug since I can only run the file if I comment this line

**Comment by talkhanz** [comment]
I was able to successfully run tile inference but I need to know if my results are appropriate. I would be grateful if you could confirm if the following tile is at the correction magnificatoin (40X) and if the results are valid.

Beloew is my input tile 
![925](https://user-images.githubusercontent.com/63508490/104118970-56939880-534e-11eb-809f-76e3ffdf35ae.png)

and here is my overlay.png for the tile
![925](https://user-images.githubusercontent.com/63508490/104118978-7460fd80-534e-11eb-8aaf-6a25631031f6.png)

**Comment by vqdang** [comment]
Thanks, its an artfifacts when I test some settings.

**Comment by talkhanz** [comment]
@vqdang is it possible to create masks from the prediction (overlay.png) files and  could you please confirm if the above resolution is 40x?
