### ISSUE TITLE
about the datasets Kumar

### ISSUE THREAD

**Issue by Kaiseem** [vqdang/hover_net#86]
Hi, i found that the kumar datasets provided in this project is different from the original version "A Dataset and a Technique for Generalized Nuclear Segmentation for Computational Pathology" on webset url: http://nucleisegmentationbenchmark.weebly.com/

To be more specific, the following files are different, although they have the same name:
train:
TCGA-A7-A13E-01Z-00-DX1 
TCGA-B0-5711-01Z-00-DX1
test:
TCGA-21-5784-01Z-00-DX1
TCGA-AY-A8YK-01A-01-TS1
TCGA-B0-5698-01Z-00-DX1
TCGA-CH-5767-01Z-00-DX1

which is the correct one?

**Comment by simongraham** [comment]
I am confident that we are using the correct data. I will dig further into this issue and report back directly on here.

**Comment by Kaiseem** [comment]
Okay but i check Kumar (http://nucleisegmentationbenchmark.weebly.com/) and MoNuSeg (https://monuseg.grand-challenge.org/Data/) datasets, their images are the same, but some of the images in the provided kumar datasets are different from the above datasets, how to explain it?

**Comment by simongraham** [comment]
Email reply from the MoNuSeg organisers:

```
Thanks for pointing this out - we wanted to add some additional images for which we had nuclear annotations lying around - the names were messed while adding those to the original 2017 dataset. 

Now, we have fixed this and you will find 30 original +7 bonus images with nuclear annotations on the Nuclei Segmentation Benchmark website.

However, for MoNuSeg training data we have kept only the original 30 images on the monuseg website data page.
```

So, in short the data that we used in this repository is **correct**. The data from http://nucleisegmentationbenchmark.weebly.com/ was recently updated and a mistake was made. This has now been fixed. Please let me know if you have any further questions.

**Comment by Kaiseem** [comment]
thank you for your checking, it confused me for a long time
