### ISSUE TITLE
Is there any pytorch implementation of DCAN, DIST, MICRO-NET?

### ISSUE THREAD

**Issue by Thejas05** [vqdang/hover_net#87]

**Comment by simongraham** [comment]
If you require DCAN, DIST, Micro-Net, then please refer to the tensorflow branch of the repository. Currently we only support HoVer-Net in the PyTorch branch. We have organised things in such a way that separate models are contained within their own models directory, allowing users to easily add models if they would like. For example, you will see that HoVer-Net specific code is located [here](https://github.com/vqdang/hover_net/tree/pytorch/models/hovernet).
