### ISSUE TITLE
Cannot load the checkpoints except the "fast_monusac" one

### ISSUE THREAD

**Issue by liux0614** [vqdang/hover_net#88]
Dear @simongraham , 
When I tried to load the checkpoints, I can only succssfully loadthe checkpoint "hovernet_fast_monusac_type_tf2pytorch.tar". When I ran the checkpoint "hovernet_original_consep_notype_tf2pytorch.tar" using the following command
`python run_infer.py \
--gpu='0,1' \
--nr_types=6 \
--type_info_path=type_info.json \
--batch_size=64 \
--model_mode=orignal \
--model_path=weights/hovernet_original_consep_notype_tf2pytorch.tar \
--nr_inference_workers=8 \
--nr_post_proc_workers=16 \
tile \
--input_dir=infer_images \
--output_dir=inferred_images_pannuke \
--draw_dot \
--save_qupath`

**I got the following error: I was jsut wondering if the way I did to load the checkpoint was incorrect.**

`
![image](https://user-images.githubusercontent.com/3401577/104762511-7c47e580-5732-11eb-94b4-94f90b5d5995.png)

**Comment by vqdang** [comment]
@liux0614 You are loading `hovernet_original_consep_notype_tf2pytorch.tar` which doesnt do nuclei type classification. So you must set `--nr_types=` to 0 .

**Comment by liux0614** [comment]
I set nr_types to 0 with the following command
`python run_infer.py \
--gpu='0,1' \
--nr_types=0 \
--type_info_path=type_info.json \
--batch_size=64 \
--model_mode=orignal \
--model_path=weights/hovernet_original_consep_notype_tf2pytorch.tar \
--nr_inference_workers=8 \
--nr_post_proc_workers=16 \
tile \
--input_dir=infer_images \
--output_dir=inferred_images_pannuke \
--draw_dot \
--save_qupath`,
and still got the size mismatch error.
![image](https://user-images.githubusercontent.com/3401577/104762396-47d42980-5732-11eb-8c5b-b7320b39a8ae.png)

**Comment by vqdang** [comment]
@liux0614 It works normal for me, also Ive just realized that your cmd is slightly off at another place. Also, from your screenshot, the netdesc ksize is wrong which means your cmd input didnt get fed correctly.

Could you put the following into a .sh and run it ?
```
python run_infer.py \
--gpu='0,1' \
--nr_types=0 \
--type_info_path=type_info.json \
--batch_size=64 \
--model_mode=original \
--model_path=../pretrained/hovernet_original_consep_notype_tf2pytorch.tar \
--nr_inference_workers=8 \
--nr_post_proc_workers=16 \
tile \
--input_dir=exp_output/imgs/ \
--output_dir=exp_output/pred/ \
--draw_dot \
--save_qupath
```

**Comment by liux0614** [comment]
I think I did exactly what you said. The command line I ran is from run_tile.sh.
![image](https://user-images.githubusercontent.com/3401577/104764638-acdd4e80-5735-11eb-9941-231491bc1962.png)

**Comment by vqdang** [comment]
How did you run the `.sh` ? Also, which os systems are you running on? I'm using `bash run_tile.sh`.

**Comment by vqdang** [comment]
@liux0614 ah ok, I realize now. You have typo in your screenshot `orignal` not `original`.

**Comment by liux0614** [comment]
I tried bash run_tile.py. It works. Thanks very much.
