### ISSUE TITLE
.mrxs file support

### ISSUE THREAD

**Issue by jjhbw** [vqdang/hover_net#89]
Hi! Our lab has been really impressed with Hovernet.

We've been working on getting it set up on our dataset, and noticed that using `.mrxs` files is prevented by the below snippet.

https://github.com/vqdang/hover_net/blob/bf852fff50f345553ab7a9c5a5c6466286d27a4f/misc/wsi_handler.py#L194

OpenSlide supports mrxs files out of the box. What is the reason that you gatekeep the file extensions before feeding the file into openslide?

**Comment by vqdang** [comment]
Hi, thanks for using our approach.

To answer your question, when making the pytorch version, we had some other internal handlers that collide with those supported by openslide. On another note, you can change the code to suit your need.

**Comment by simongraham** [comment]
Closing this issue now as it should solve things going forward 😊

**Comment by jjhbw** [comment]
The change in 0845678 makes sense. Thanks!
