### ISSUE TITLE
Torch =1.1.0 and TorchVersion =0.3.0 

### ISSUE THREAD

**Issue by zerodohero** [vqdang/hover_net#92]
I trained on both Torch=1.1.0 and TorchVersion =0.3.0 (the device only supports this configuration) and found the following error
D:\Users\lzxie\hover_net-master\venv1\Scripts\python.exe D:/Users/lzxie/hover_net-master/hover_net-master/run_train.py --gpu=0,1
Detect #GPUS: 2
Using manual seed: 10
Dataset train: 4563
Dataset valid: 2366
Model `net` pretrained path: ./models/pretrained/ImageNet-ResNet50-Preact_pytorch.tar
Missing Variables: 
 ['conv_bot.weight', 'decoder.tp.u3.conva.weight', 'decoder.tp.u3.dense.units.0.preact_bna/bn.weight', 'decoder.tp.u3.dense.units.0.preact_bna/bn.bias', 'decoder.tp.u3.dense.units.0.preact_bna/bn.running_mean', 'decoder.tp.u3.dense.units.0.preact_bna/bn.running_var', 'decoder.tp.u3.dense.units.0.conv1.weight', 'decoder.tp.u3.dense.units.0.conv1/bn.weight', 'decoder.tp.u3.dense.units.0.conv1/bn.bias', 'decoder.tp.u3.dense.units.0.conv1/bn.running_mean', 'decoder.tp.u3.dense.units.0.conv1/bn.running_var', 'decoder.tp.u3.dense.units.0.conv2.weight', 'decoder.tp.u3.dense.units.1.preact_bna/bn.weight', 'decoder.tp.u3.dense.units.1.preact_bna/bn.bias', 'decoder.tp.u3.dense.units.1.preact_bna/bn.running_mean', 'decoder.tp.u3.dense.units.1.preact_bna/bn.running_var', 'decoder.tp.u3.dense.units.1.conv1.weight', 'decoder.tp.u3.dense.units.1.conv1/bn.weight', 'decoder.tp.u3.dense.units.1.conv1/bn.bias', 'decoder.tp.u3.dense.units.1.conv1/bn.running_mean', 'decoder.tp.u3.dense.units.1.conv1/bn.running_var', 'decoder.tp.u3.dense.units.1.conv2.weight', 'decoder.tp.u3.dense.units.2.preact_bna/bn.weight', 'decoder.tp.u3.dense.units.2.preact_bna/bn.bias', 'decoder.tp.u3.dense.units.2.preact_bna/bn.running_mean', 'decoder.tp.u3.dense.units.2.preact_bna/bn.running_var', 'decoder.tp.u3.dense.units.2.conv1.weight', 'decoder.tp.u3.dense.units.2.conv1/bn.weight', 'decoder.tp.u3.dense.units.2.conv1/bn.bias', 'decoder.tp.u3.dense.units.2.conv1/bn.running_mean', 'decoder.tp.u3.dense.units.2.conv1/bn.running_var', 'decoder.tp.u3.dense.units.2.conv2.weight', 'decoder.tp.u3.dense.units.3.preact_bna/bn.weight', 'decoder.tp.u3.dense.units.3.preact_bna/bn.bias', 'decoder.tp.u3.dense.units.3.preact_bna/bn.running_mean', 'decoder.tp.u3.dense.units.3.preact_bna/bn.running_var', 'decoder.tp.u3.dense.units.3.conv1.weight', 'decoder.tp.u3.dense.units.3.conv1/bn.weight', 'decoder.tp.u3.dense.units.3.conv1/bn.bias', 'decoder.tp.u3.dense.units.3.conv1/bn.running_mean', 'decoder.tp.u3.dense.units.3.conv1/bn.running_var', 'decoder.tp.u3.dense.units.3.conv2.weight', 'decoder.tp.u3.dense.units.4.preact_bna/bn.weight', 'decoder.tp.u3.dense.units.4.preact_bna/bn.bias', 'decoder.tp.u3.dense.units.4.preact_bna/bn.running_mean', 'decoder.tp.u3.dense.units.4.preact_bna/bn.running_var', 'decoder.tp.u3.dense.units.4.conv1.weight', 'decoder.tp.u3.dense.units.4.conv1/bn.weight', 'decoder.tp.u3.dense.units.4.conv1/bn.bias', 'decoder.tp.u3.dense.units.4.conv1/bn.running_mean', 'decoder.tp.u3.dense.units.4.conv1/bn.running_var', 'decoder.tp.u3.dense.units.4.conv2.weight', 'decoder.tp.u3.dense.units.5.preact_bna/bn.weight', 'decoder.tp.u3.dense.units.5.preact_bna/bn.bias', 'decoder.tp.u3.dense.units.5.preact_bna/bn.running_mean', 'decoder.tp.u3.dense.units.5.preact_bna/bn.running_var', 'decoder.tp.u3.dense.units.5.conv1.weight', 'decoder.tp.u3.dense.units.5.conv1/bn.weight', 'decoder.tp.u3.dense.units.5.conv1/bn.bias', 'decoder.tp.u3.dense.units.5.conv1/bn.running_mean', 'decoder.tp.u3.dense.units.5.conv1/bn.running_var', 'decoder.tp.u3.dense.units.5.conv2.weight', 'decoder.tp.u3.dense.units.6.preact_bna/bn.weight', 'decoder.tp.u3.dense.units.6.preact_bna/bn.bias', 'decoder.tp.u3.dense.units.6.preact_bna/bn.running_mean', 'decoder.tp.u3.dense.units.6.preact_bna/bn.running_var', 'decoder.tp.u3.dense.units.6.conv1.weight', 'decoder.tp.u3.dense.units.6.conv1/bn.weight', 'decoder.tp.u3.dense.units.6.conv1/bn.bias', 'decoder.tp.u3.dense.units.6.conv1/bn.running_mean', 'decoder.tp.u3.dense.units.6.conv1/bn.running_var', 'decoder.tp.u3.dense.units.6.conv2.weight', 'decoder.tp.u3.dense.units.7.preact_bna/bn.weight', 'decoder.tp.u3.dense.units.7.preact_bna/bn.bias', 'decoder.tp.u3.dense.units.7.preact_bna/bn.running_mean', 'decoder.tp.u3.dense.units.7.preact_bna/bn.running_var', 'decoder.tp.u3.dense.units.7.conv1.weight', 'decoder.tp.u3.dense.units.7.conv1/bn.weight', 'decoder.tp.u3.dense.units.7.conv1/bn.bias', 'decoder.tp.u3.dense.units.7.conv1/bn.running_mean', 'decoder.tp.u3.dense.units.7.conv1/bn.running_var', 'decoder.tp.u3.dense.units.7.conv2.weight', 'decoder.tp.u3.dense.blk_bna.bn.weight', 'decoder.tp.u3.dense.blk_bna.bn.bias', 'decoder.tp.u3.dense.blk_bna.bn.running_mean', 'decoder.tp.u3.dense.blk_bna.bn.running_var', 'decoder.tp.u3.convf.weight', 'decoder.tp.u2.conva.weight', 'decoder.tp.u2.dense.units.0.preact_bna/bn.weight', 'decoder.tp.u2.dense.units.0.preact_bna/bn.bias', 'decoder.tp.u2.dense.units.0.preact_bna/bn.running_mean', 'decoder.tp.u2.dense.units.0.preact_bna/bn.running_var', 'decoder.tp.u2.dense.units.0.conv1.weight', 'decoder.tp.u2.dense.units.0.conv1/bn.weight', 'decoder.tp.u2.dense.units.0.conv1/bn.bias', 'decoder.tp.u2.dense.units.0.conv1/bn.running_mean', 'decoder.tp.u2.dense.units.0.conv1/bn.running_var', 'decoder.tp.u2.dense.units.0.conv2.weight', 'decoder.tp.u2.dense.units.1.preact_bna/bn.weight', 'decoder.tp.u2.dense.units.1.preact_bna/bn.bias', 'decoder.tp.u2.dense.units.1.preact_bna/bn.running_mean', 'decoder.tp.u2.dense.units.1.preact_bna/bn.running_var', 'decoder.tp.u2.dense.units.1.conv1.weight', 'decoder.tp.u2.dense.units.1.conv1/bn.weight', 'decoder.tp.u2.dense.units.1.conv1/bn.bias', 'decoder.tp.u2.dense.units.1.conv1/bn.running_mean', 'decoder.tp.u2.dense.units.1.conv1/bn.running_var', 'decoder.tp.u2.dense.units.1.conv2.weight', 'decoder.tp.u2.dense.units.2.preact_bna/bn.weight', 'decoder.tp.u2.dense.units.2.preact_bna/bn.bias', 'decoder.tp.u2.dense.units.2.preact_bna/bn.running_mean', 'decoder.tp.u2.dense.units.2.preact_bna/bn.running_var', 'decoder.tp.u2.dense.units.2.conv1.weight', 'decoder.tp.u2.dense.units.2.conv1/bn.weight', 'decoder.tp.u2.dense.units.2.conv1/bn.bias', 'decoder.tp.u2.dense.units.2.conv1/bn.running_mean', 'decoder.tp.u2.dense.units.2.conv1/bn.running_var', 'decoder.tp.u2.dense.units.2.conv2.weight', 'decoder.tp.u2.dense.units.3.preact_bna/bn.weight', 'decoder.tp.u2.dense.units.3.preact_bna/bn.bias', 'decoder.tp.u2.dense.units.3.preact_bna/bn.running_mean', 'decoder.tp.u2.dense.units.3.preact_bna/bn.running_var', 'decoder.tp.u2.dense.units.3.conv1.weight', 'decoder.tp.u2.dense.units.3.conv1/bn.weight', 'decoder.tp.u2.dense.units.3.conv1/bn.bias', 'decoder.tp.u2.dense.units.3.conv1/bn.running_mean', 'decoder.tp.u2.dense.units.3.conv1/bn.running_var', 'decoder.tp.u2.dense.units.3.conv2.weight', 'decoder.tp.u2.dense.blk_bna.bn.weight', 'decoder.tp.u2.dense.blk_bna.bn.bias', 'decoder.tp.u2.dense.blk_bna.bn.running_mean', 'decoder.tp.u2.dense.blk_bna.bn.running_var', 'decoder.tp.u2.convf.weight', 'decoder.tp.u1.conva.weight', 'decoder.tp.u0.bn.weight', 'decoder.tp.u0.bn.bias', 'decoder.tp.u0.bn.running_mean', 'decoder.tp.u0.bn.running_var', 'decoder.tp.u0.conv.weight', 'decoder.tp.u0.conv.bias', 'decoder.np.u3.conva.weight', 'decoder.np.u3.dense.units.0.preact_bna/bn.weight', 'decoder.np.u3.dense.units.0.preact_bna/bn.bias', 'decoder.np.u3.dense.units.0.preact_bna/bn.running_mean', 'decoder.np.u3.dense.units.0.preact_bna/bn.running_var', 'decoder.np.u3.dense.units.0.conv1.weight', 'decoder.np.u3.dense.units.0.conv1/bn.weight', 'decoder.np.u3.dense.units.0.conv1/bn.bias', 'decoder.np.u3.dense.units.0.conv1/bn.running_mean', 'decoder.np.u3.dense.units.0.conv1/bn.running_var', 'decoder.np.u3.dense.units.0.conv2.weight', 'decoder.np.u3.dense.units.1.preact_bna/bn.weight', 'decoder.np.u3.dense.units.1.preact_bna/bn.bias', 'decoder.np.u3.dense.units.1.preact_bna/bn.running_mean', 'decoder.np.u3.dense.units.1.preact_bna/bn.running_var', 'decoder.np.u3.dense.units.1.conv1.weight', 'decoder.np.u3.dense.units.1.conv1/bn.weight', 'decoder.np.u3.dense.units.1.conv1/bn.bias', 'decoder.np.u3.dense.units.1.conv1/bn.running_mean', 'decoder.np.u3.dense.units.1.conv1/bn.running_var', 'decoder.np.u3.dense.units.1.conv2.weight', 'decoder.np.u3.dense.units.2.preact_bna/bn.weight', 'decoder.np.u3.dense.units.2.preact_bna/bn.bias', 'decoder.np.u3.dense.units.2.preact_bna/bn.running_mean', 'decoder.np.u3.dense.units.2.preact_bna/bn.running_var', 'decoder.np.u3.dense.units.2.conv1.weight', 'decoder.np.u3.dense.units.2.conv1/bn.weight', 'decoder.np.u3.dense.units.2.conv1/bn.bias', 'decoder.np.u3.dense.units.2.conv1/bn.running_mean', 'decoder.np.u3.dense.units.2.conv1/bn.running_var', 'decoder.np.u3.dense.units.2.conv2.weight', 'decoder.np.u3.dense.units.3.preact_bna/bn.weight', 'decoder.np.u3.dense.units.3.preact_bna/bn.bias', 'decoder.np.u3.dense.units.3.preact_bna/bn.running_mean', 'decoder.np.u3.dense.units.3.preact_bna/bn.running_var', 'decoder.np.u3.dense.units.3.conv1.weight', 'decoder.np.u3.dense.units.3.conv1/bn.weight', 'decoder.np.u3.dense.units.3.conv1/bn.bias', 'decoder.np.u3.dense.units.3.conv1/bn.running_mean', 'decoder.np.u3.dense.units.3.conv1/bn.running_var', 'decoder.np.u3.dense.units.3.conv2.weight', 'decoder.np.u3.dense.units.4.preact_bna/bn.weight', 'decoder.np.u3.dense.units.4.preact_bna/bn.bias', 'decoder.np.u3.dense.units.4.preact_bna/bn.running_mean', 'decoder.np.u3.dense.units.4.preact_bna/bn.running_var', 'decoder.np.u3.dense.units.4.conv1.weight', 'decoder.np.u3.dense.units.4.conv1/bn.weight', 'decoder.np.u3.dense.units.4.conv1/bn.bias', 'decoder.np.u3.dense.units.4.conv1/bn.running_mean', 'decoder.np.u3.dense.units.4.conv1/bn.running_var', 'decoder.np.u3.dense.units.4.conv2.weight', 'decoder.np.u3.dense.units.5.preact_bna/bn.weight', 'decoder.np.u3.dense.units.5.preact_bna/bn.bias', 'decoder.np.u3.dense.units.5.preact_bna/bn.running_mean', 'decoder.np.u3.dense.units.5.preact_bna/bn.running_var', 'decoder.np.u3.dense.units.5.conv1.weight', 'decoder.np.u3.dense.units.5.conv1/bn.weight', 'decoder.np.u3.dense.units.5.conv1/bn.bias', 'decoder.np.u3.dense.units.5.conv1/bn.running_mean', 'decoder.np.u3.dense.units.5.conv1/bn.running_var', 'decoder.np.u3.dense.units.5.conv2.weight', 'decoder.np.u3.dense.units.6.preact_bna/bn.weight', 'decoder.np.u3.dense.units.6.preact_bna/bn.bias', 'decoder.np.u3.dense.units.6.preact_bna/bn.running_mean', 'decoder.np.u3.dense.units.6.preact_bna/bn.running_var', 'decoder.np.u3.dense.units.6.conv1.weight', 'decoder.np.u3.dense.units.6.conv1/bn.weight', 'decoder.np.u3.dense.units.6.conv1/bn.bias', 'decoder.np.u3.dense.units.6.conv1/bn.running_mean', 'decoder.np.u3.dense.units.6.conv1/bn.running_var', 'decoder.np.u3.dense.units.6.conv2.weight', 'decoder.np.u3.dense.units.7.preact_bna/bn.weight', 'decoder.np.u3.dense.units.7.preact_bna/bn.bias', 'decoder.np.u3.dense.units.7.preact_bna/bn.running_mean', 'decoder.np.u3.dense.units.7.preact_bna/bn.running_var', 'decoder.np.u3.dense.units.7.conv1.weight', 'decoder.np.u3.dense.units.7.conv1/bn.weight', 'decoder.np.u3.dense.units.7.conv1/bn.bias', 'decoder.np.u3.dense.units.7.conv1/bn.running_mean', 'decoder.np.u3.dense.units.7.conv1/bn.running_var', 'decoder.np.u3.dense.units.7.conv2.weight', 'decoder.np.u3.dense.blk_bna.bn.weight', 'decoder.np.u3.dense.blk_bna.bn.bias', 'decoder.np.u3.dense.blk_bna.bn.running_mean', 'decoder.np.u3.dense.blk_bna.bn.running_var', 'decoder.np.u3.convf.weight', 'decoder.np.u2.conva.weight', 'decoder.np.u2.dense.units.0.preact_bna/bn.weight', 'decoder.np.u2.dense.units.0.preact_bna/bn.bias', 'decoder.np.u2.dense.units.0.preact_bna/bn.running_mean', 'decoder.np.u2.dense.units.0.preact_bna/bn.running_var', 'decoder.np.u2.dense.units.0.conv1.weight', 'decoder.np.u2.dense.units.0.conv1/bn.weight', 'decoder.np.u2.dense.units.0.conv1/bn.bias', 'decoder.np.u2.dense.units.0.conv1/bn.running_mean', 'decoder.np.u2.dense.units.0.conv1/bn.running_var', 'decoder.np.u2.dense.units.0.conv2.weight', 'decoder.np.u2.dense.units.1.preact_bna/bn.weight', 'decoder.np.u2.dense.units.1.preact_bna/bn.bias', 'decoder.np.u2.dense.units.1.preact_bna/bn.running_mean', 'decoder.np.u2.dense.units.1.preact_bna/bn.running_var', 'decoder.np.u2.dense.units.1.conv1.weight', 'decoder.np.u2.dense.units.1.conv1/bn.weight', 'decoder.np.u2.dense.units.1.conv1/bn.bias', 'decoder.np.u2.dense.units.1.conv1/bn.running_mean', 'decoder.np.u2.dense.units.1.conv1/bn.running_var', 'decoder.np.u2.dense.units.1.conv2.weight', 'decoder.np.u2.dense.units.2.preact_bna/bn.weight', 'decoder.np.u2.dense.units.2.preact_bna/bn.bias', 'decoder.np.u2.dense.units.2.preact_bna/bn.running_mean', 'decoder.np.u2.dense.units.2.preact_bna/bn.running_var', 'decoder.np.u2.dense.units.2.conv1.weight', 'decoder.np.u2.dense.units.2.conv1/bn.weight', 'decoder.np.u2.dense.units.2.conv1/bn.bias', 'decoder.np.u2.dense.units.2.conv1/bn.running_mean', 'decoder.np.u2.dense.units.2.conv1/bn.running_var', 'decoder.np.u2.dense.units.2.conv2.weight', 'decoder.np.u2.dense.units.3.preact_bna/bn.weight', 'decoder.np.u2.dense.units.3.preact_bna/bn.bias', 'decoder.np.u2.dense.units.3.preact_bna/bn.running_mean', 'decoder.np.u2.dense.units.3.preact_bna/bn.running_var', 'decoder.np.u2.dense.units.3.conv1.weight', 'decoder.np.u2.dense.units.3.conv1/bn.weight', 'decoder.np.u2.dense.units.3.conv1/bn.bias', 'decoder.np.u2.dense.units.3.conv1/bn.running_mean', 'decoder.np.u2.dense.units.3.conv1/bn.running_var', 'decoder.np.u2.dense.units.3.conv2.weight', 'decoder.np.u2.dense.blk_bna.bn.weight', 'decoder.np.u2.dense.blk_bna.bn.bias', 'decoder.np.u2.dense.blk_bna.bn.running_mean', 'decoder.np.u2.dense.blk_bna.bn.running_var', 'decoder.np.u2.convf.weight', 'decoder.np.u1.conva.weight', 'decoder.np.u0.bn.weight', 'decoder.np.u0.bn.bias', 'decoder.np.u0.bn.running_mean', 'decoder.np.u0.bn.running_var', 'decoder.np.u0.conv.weight', 'decoder.np.u0.conv.bias', 'decoder.hv.u3.conva.weight', 'decoder.hv.u3.dense.units.0.preact_bna/bn.weight', 'decoder.hv.u3.dense.units.0.preact_bna/bn.bias', 'decoder.hv.u3.dense.units.0.preact_bna/bn.running_mean', 'decoder.hv.u3.dense.units.0.preact_bna/bn.running_var', 'decoder.hv.u3.dense.units.0.conv1.weight', 'decoder.hv.u3.dense.units.0.conv1/bn.weight', 'decoder.hv.u3.dense.units.0.conv1/bn.bias', 'decoder.hv.u3.dense.units.0.conv1/bn.running_mean', 'decoder.hv.u3.dense.units.0.conv1/bn.running_var', 'decoder.hv.u3.dense.units.0.conv2.weight', 'decoder.hv.u3.dense.units.1.preact_bna/bn.weight', 'decoder.hv.u3.dense.units.1.preact_bna/bn.bias', 'decoder.hv.u3.dense.units.1.preact_bna/bn.running_mean', 'decoder.hv.u3.dense.units.1.preact_bna/bn.running_var', 'decoder.hv.u3.dense.units.1.conv1.weight', 'decoder.hv.u3.dense.units.1.conv1/bn.weight', 'decoder.hv.u3.dense.units.1.conv1/bn.bias', 'decoder.hv.u3.dense.units.1.conv1/bn.running_mean', 'decoder.hv.u3.dense.units.1.conv1/bn.running_var', 'decoder.hv.u3.dense.units.1.conv2.weight', 'decoder.hv.u3.dense.units.2.preact_bna/bn.weight', 'decoder.hv.u3.dense.units.2.preact_bna/bn.bias', 'decoder.hv.u3.dense.units.2.preact_bna/bn.running_mean', 'decoder.hv.u3.dense.units.2.preact_bna/bn.running_var', 'decoder.hv.u3.dense.units.2.conv1.weight', 'decoder.hv.u3.dense.units.2.conv1/bn.weight', 'decoder.hv.u3.dense.units.2.conv1/bn.bias', 'decoder.hv.u3.dense.units.2.conv1/bn.running_mean', 'decoder.hv.u3.dense.units.2.conv1/bn.running_var', 'decoder.hv.u3.dense.units.2.conv2.weight', 'decoder.hv.u3.dense.units.3.preact_bna/bn.weight', 'decoder.hv.u3.dense.units.3.preact_bna/bn.bias', 'decoder.hv.u3.dense.units.3.preact_bna/bn.running_mean', 'decoder.hv.u3.dense.units.3.preact_bna/bn.running_var', 'decoder.hv.u3.dense.units.3.conv1.weight', 'decoder.hv.u3.dense.units.3.conv1/bn.weight', 'decoder.hv.u3.dense.units.3.conv1/bn.bias', 'decoder.hv.u3.dense.units.3.conv1/bn.running_mean', 'decoder.hv.u3.dense.units.3.conv1/bn.running_var', 'decoder.hv.u3.dense.units.3.conv2.weight', 'decoder.hv.u3.dense.units.4.preact_bna/bn.weight', 'decoder.hv.u3.dense.units.4.preact_bna/bn.bias', 'decoder.hv.u3.dense.units.4.preact_bna/bn.running_mean', 'decoder.hv.u3.dense.units.4.preact_bna/bn.running_var', 'decoder.hv.u3.dense.units.4.conv1.weight', 'decoder.hv.u3.dense.units.4.conv1/bn.weight', 'decoder.hv.u3.dense.units.4.conv1/bn.bias', 'decoder.hv.u3.dense.units.4.conv1/bn.running_mean', 'decoder.hv.u3.dense.units.4.conv1/bn.running_var', 'decoder.hv.u3.dense.units.4.conv2.weight', 'decoder.hv.u3.dense.units.5.preact_bna/bn.weight', 'decoder.hv.u3.dense.units.5.preact_bna/bn.bias', 'decoder.hv.u3.dense.units.5.preact_bna/bn.running_mean', 'decoder.hv.u3.dense.units.5.preact_bna/bn.running_var', 'decoder.hv.u3.dense.units.5.conv1.weight', 'decoder.hv.u3.dense.units.5.conv1/bn.weight', 'decoder.hv.u3.dense.units.5.conv1/bn.bias', 'decoder.hv.u3.dense.units.5.conv1/bn.running_mean', 'decoder.hv.u3.dense.units.5.conv1/bn.running_var', 'decoder.hv.u3.dense.units.5.conv2.weight', 'decoder.hv.u3.dense.units.6.preact_bna/bn.weight', 'decoder.hv.u3.dense.units.6.preact_bna/bn.bias', 'decoder.hv.u3.dense.units.6.preact_bna/bn.running_mean', 'decoder.hv.u3.dense.units.6.preact_bna/bn.running_var', 'decoder.hv.u3.dense.units.6.conv1.weight', 'decoder.hv.u3.dense.units.6.conv1/bn.weight', 'decoder.hv.u3.dense.units.6.conv1/bn.bias', 'decoder.hv.u3.dense.units.6.conv1/bn.running_mean', 'decoder.hv.u3.dense.units.6.conv1/bn.running_var', 'decoder.hv.u3.dense.units.6.conv2.weight', 'decoder.hv.u3.dense.units.7.preact_bna/bn.weight', 'decoder.hv.u3.dense.units.7.preact_bna/bn.bias', 'decoder.hv.u3.dense.units.7.preact_bna/bn.running_mean', 'decoder.hv.u3.dense.units.7.preact_bna/bn.running_var', 'decoder.hv.u3.dense.units.7.conv1.weight', 'decoder.hv.u3.dense.units.7.conv1/bn.weight', 'decoder.hv.u3.dense.units.7.conv1/bn.bias', 'decoder.hv.u3.dense.units.7.conv1/bn.running_mean', 'decoder.hv.u3.dense.units.7.conv1/bn.running_var', 'decoder.hv.u3.dense.units.7.conv2.weight', 'decoder.hv.u3.dense.blk_bna.bn.weight', 'decoder.hv.u3.dense.blk_bna.bn.bias', 'decoder.hv.u3.dense.blk_bna.bn.running_mean', 'decoder.hv.u3.dense.blk_bna.bn.running_var', 'decoder.hv.u3.convf.weight', 'decoder.hv.u2.conva.weight', 'decoder.hv.u2.dense.units.0.preact_bna/bn.weight', 'decoder.hv.u2.dense.units.0.preact_bna/bn.bias', 'decoder.hv.u2.dense.units.0.preact_bna/bn.running_mean', 'decoder.hv.u2.dense.units.0.preact_bna/bn.running_var', 'decoder.hv.u2.dense.units.0.conv1.weight', 'decoder.hv.u2.dense.units.0.conv1/bn.weight', 'decoder.hv.u2.dense.units.0.conv1/bn.bias', 'decoder.hv.u2.dense.units.0.conv1/bn.running_mean', 'decoder.hv.u2.dense.units.0.conv1/bn.running_var', 'decoder.hv.u2.dense.units.0.conv2.weight', 'decoder.hv.u2.dense.units.1.preact_bna/bn.weight', 'decoder.hv.u2.dense.units.1.preact_bna/bn.bias', 'decoder.hv.u2.dense.units.1.preact_bna/bn.running_mean', 'decoder.hv.u2.dense.units.1.preact_bna/bn.running_var', 'decoder.hv.u2.dense.units.1.conv1.weight', 'decoder.hv.u2.dense.units.1.conv1/bn.weight', 'decoder.hv.u2.dense.units.1.conv1/bn.bias', 'decoder.hv.u2.dense.units.1.conv1/bn.running_mean', 'decoder.hv.u2.dense.units.1.conv1/bn.running_var', 'decoder.hv.u2.dense.units.1.conv2.weight', 'decoder.hv.u2.dense.units.2.preact_bna/bn.weight', 'decoder.hv.u2.dense.units.2.preact_bna/bn.bias', 'decoder.hv.u2.dense.units.2.preact_bna/bn.running_mean', 'decoder.hv.u2.dense.units.2.preact_bna/bn.running_var', 'decoder.hv.u2.dense.units.2.conv1.weight', 'decoder.hv.u2.dense.units.2.conv1/bn.weight', 'decoder.hv.u2.dense.units.2.conv1/bn.bias', 'decoder.hv.u2.dense.units.2.conv1/bn.running_mean', 'decoder.hv.u2.dense.units.2.conv1/bn.running_var', 'decoder.hv.u2.dense.units.2.conv2.weight', 'decoder.hv.u2.dense.units.3.preact_bna/bn.weight', 'decoder.hv.u2.dense.units.3.preact_bna/bn.bias', 'decoder.hv.u2.dense.units.3.preact_bna/bn.running_mean', 'decoder.hv.u2.dense.units.3.preact_bna/bn.running_var', 'decoder.hv.u2.dense.units.3.conv1.weight', 'decoder.hv.u2.dense.units.3.conv1/bn.weight', 'decoder.hv.u2.dense.units.3.conv1/bn.bias', 'decoder.hv.u2.dense.units.3.conv1/bn.running_mean', 'decoder.hv.u2.dense.units.3.conv1/bn.running_var', 'decoder.hv.u2.dense.units.3.conv2.weight', 'decoder.hv.u2.dense.blk_bna.bn.weight', 'decoder.hv.u2.dense.blk_bna.bn.bias', 'decoder.hv.u2.dense.blk_bna.bn.running_mean', 'decoder.hv.u2.dense.blk_bna.bn.running_var', 'decoder.hv.u2.convf.weight', 'decoder.hv.u1.conva.weight', 'decoder.hv.u0.bn.weight', 'decoder.hv.u0.bn.bias', 'decoder.hv.u0.bn.running_mean', 'decoder.hv.u0.bn.running_var', 'decoder.hv.u0.conv.weight', 'decoder.hv.u0.conv.bias']
Detected Unknown Variables: 
 []
Processing: |          | 0/142[00:00<?,?it/s]Batch = nan|EMA = nan----------------EPOCH 1
ss <torch.utils.data.dataloader.DataLoader object at 0x000000D7272D69B0>
Traceback (most recent call last):
  File "D:/Users/lzxie/hover_net-master/hover_net-master/run_train.py", line 303, in <module>
    trainer.run()
  File "D:/Users/lzxie/hover_net-master/hover_net-master/run_train.py", line 284, in run
    phase_info, engine_opt, save_path, prev_log_dir=prev_save_path
  File "D:/Users/lzxie/hover_net-master/hover_net-master/run_train.py", line 260, in run_once
    main_runner.run(opt["nr_epochs"])
  File "D:\Users\lzxie\hover_net-master\hover_net-master\run_utils\engine.py", line 172, in run
    for data_batch in self.dataloader:
  File "C:\Users\lzxie\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 560, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "C:\Users\lzxie\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\collate.py", line 63, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "C:\Users\lzxie\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\collate.py", line 63, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "C:\Users\lzxie\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\collate.py", line 52, in default_collate
    return default_collate([torch.from_numpy(b) for b in batch])
  File "C:\Users\lzxie\Anaconda3\envs\torch\lib\site-packages\torch\utils\data\_utils\collate.py", line 52, in <listcomp>
    return default_collate([torch.from_numpy(b) for b in batch])
TypeError: can't convert np.ndarray of type numpy.intc. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.
Processing: |          | 0/142[00:02<?,?it/s]Batch = nan|EMA = nan

Process finished with exit code 1

The code is located as follows：

in engine.py
for data_batch in self.dataloader:
                self.__trigger_events(Events.STEP_STARTED)

                step_run_info = [
                    self.state.run_info,
                    {
                        "epoch": self.state.curr_epoch,
                        "step": self.state.curr_global_step,
                    },
                ]
                step_output = self.run_step(data_batch, step_run_info)
                self.state.step_output = step_output

                self.__trigger_events(Events.STEP_COMPLETED)
                self.state.curr_global_step += 1
                self.state.curr_epoch_step += 1

                if self.engine_name == "train":
                    pbar.postfix[1]["Batch"] = step_output["EMA"]["overall_loss"]
                    pbar.postfix[1]["EMA"] = self.state.tracked_step_output["scalar"][
                        "overall_loss"
                    ]
                pbar.update()
            pbar.close()  # to flush out the bar be

What does this code do, and does it depend on the environment?
The self. dataLoader in the first step of this code, I printed it out as <;torch.utils.data.dataloader.DataLoader object at 0x0000008DCCB86978&gt; Can this type be iterated?

**Comment by zerodohero** [comment]
By the way, the environment is the same, except that Torch and TorchVision are different versions and run on Windows.

**Comment by simongraham** [comment]
We tested with the library versions as instructed in the README. Please use those specific versions and try again.
