### ISSUE TITLE
compute_stats.py, 

### ISSUE THREAD

**Issue by zerodohero** [vqdang/hover_net#93]
In compute_stats.py, there is the following code   
       true_centroid = (true_info["inst_centroid"]).astype("float32")
        true_inst_type = (true_info["inst_type"]).astype("int32")
But there is no ["inst_centroid"] property in the predicted generated.mat file  
![image](https://user-images.githubusercontent.com/38395598/106149341-1c7f1f00-61b5-11eb-8e02-993478591c9b.png)
So I ran compute_stats.py with the following error
![image](https://user-images.githubusercontent.com/38395598/106149466-46d0dc80-61b5-11eb-84b9-c6041a05f91f.png)
How do you fix the code??

**Comment by zerodohero** [comment]
Also, I'm going to command the following, and I'm going to make sure that the path is correct
![image](https://user-images.githubusercontent.com/38395598/106149619-6ff16d00-61b5-11eb-8b4a-c01321c9d54c.png)
![image](https://user-images.githubusercontent.com/38395598/106149823-a5965600-61b5-11eb-8673-b6df78a8b8af.png)

**Comment by vqdang** [comment]
Above is due to mismatch between 2 saving format of 2 versions.
Old version portion
```
        pred_info = sio.loadmat(os.path.join(pred_dir, basename + ".mat"))
        # dont squeeze, may be 1 instance exist
        pred_centroid = (pred_info["inst_centroid"]).astype("float32")
        pred_inst_type = (pred_info["inst_type"]).astype("int32")

        if pred_centroid.shape[0] != 0:
            pred_inst_type = pred_inst_type[:, 0]
        else:  # no instance at all
            pred_centroid = np.array([[0, 0]])
            pred_inst_type = np.array([0])
```
will match with this
```
        with open('%s/%s.json' % (pred_dir, base_name), "r") as handle:
            pred_info = json.load(handle)['nuc']
        pred_centroid = np.array([v['centroid'] for v in pred_info.values()]).astype(np.float32)
        pred_inst_type = np.array([v['type'] for v in pred_info.values()]).astype(np.int32)
        print(np.unique(pred_inst_type, return_counts=True))
        pred_inst_type[pred_inst_type > 0] = 1
        # pred_inst_type = np.array(pred_inst_type == 3).astype(np.int32)
        del pred_info
```

**Comment by zerodohero** [comment]
ok , However, I don't see it in the code
with open('%s/%s.json' % (pred_dir, base_name), "r") as handle:
            pred_info = json.load(handle)['nuc']
        pred_centroid = np.array([v['centroid'] for v in pred_info.values()]).astype(np.float32)
        pred_inst_type = np.array([v['type'] for v in pred_info.values()]).astype(np.int32)
        del pred_info

        if pred_centroid.shape[0] != 0:
            pred_inst_type = pred_inst_type[:, 0]
        else:  # no instance at all
            pred_centroid = np.array([[0, 0]])
            pred_inst_type = np.array([0])

**Comment by zerodohero** [comment]
To emphasize, I am using tiles, not WSI, and the code you mentioned is not in the latest version of compute_stats.py
         with open('%s/%s.json' % (pred_dir, base_name), "r") as handle:
            pred_info = json.load(handle)['nuc']
        pred_centroid = np.array([v['centroid'] for v in pred_info.values()]).astype(np.float32)
        pred_inst_type = np.array([v['type'] for v in pred_info.values()]).astype(np.int32)
        del pred_info

        if pred_centroid.shape[0] != 0:
            pred_inst_type = pred_inst_type[:, 0]
        else:  # no instance at all
            pred_centroid = np.array([[0, 0]])
            pred_inst_type = np.array([0])
And I'm just replacing the block of code that you pointed out, so I get an error.I got an error after changing the path to JSON, because it was one-dimensional, but this code gave it a two-dimensional one.

**Comment by vqdang** [comment]
Change
```
    if pred_centroid.shape[0] != 0:
        pred_inst_type = pred_inst_type[:, 0]
    else:  # no instance at all
        pred_centroid = np.array([[0, 0]])
        pred_inst_type = np.array([0])
 ```
to 
```
    # no instance at all
    if pred_centroid.shape[0] == 0:
        pred_centroid = np.array([[0, 0]])
        pred_inst_type = np.array([0])
```
This portion is mainly for sanity check.
