### ISSUE TITLE
unable to view train dataset

### ISSUE THREAD

**Issue by michalstepniewski** [vqdang/hover_net#95]
Using manual seed: 10
Traceback (most recent call last):
  File "run_train.py", line 291, in <module>
    trainer.view_dataset(args["--view"])
  File "run_train.py", line 79, in view_dataset
    dataloader = self.get_datagen(1, mode, target_info["gen"])
AttributeError: 'TrainManager' object has no attribute 'get_datagen'

**Comment by vqdang** [comment]
Should be able to view now. This is kind of legacy code.
