### ISSUE TITLE
Where did you do regression?

### ISSUE THREAD

**Issue by CCz23** [vqdang/hover_net#99]
Hello! Could you please direct me to where you run the regression for the HoVer branch and also where you calculate the MSE of this?

**Comment by simongraham** [comment]
The losses are computed [here](https://github.com/vqdang/hover_net/blob/master/models/hovernet/run_desc.py#L70). Here, these losses are defined at [this location](https://github.com/vqdang/hover_net/blob/master/models/hovernet/opt.py#L81), where the specific functions are located [here](https://github.com/vqdang/hover_net/blob/master/models/hovernet/utils.py#L87).
